# **FRAMEWORK V7 DATASET MAESTRO - MACHINE LEARNING**

## **M0. Carga y Validación del Dataset para Machine Learning**

In [1]:
#==========================================================================================
# LIBRERÍAS
#==========================================================================================

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

In [2]:
#==========================================================================================
# CARGA DEL DATASET
#==========================================================================================

url_dataset = (

"https://raw.githubusercontent.com/jriatiga/FRAMEWORK_V7/refs/heads/main/DATA/MASTER/C12_MASTER/Dataset_Machine_Learning/dataset_machine_learning.parquet"

)

dataset_ml = pd.read_parquet(url_dataset)

print()
print("=" * 90)
print("DATASET PARA MACHINE LEARNING")
print("=" * 90)

print()
print(f"Observaciones : {dataset_ml.shape[0]}")
print(f"Variables     : {dataset_ml.shape[1]}")
print(f"Duplicados    : {dataset_ml.duplicated().sum()}")
print(f"Nulos totales : {dataset_ml.isna().sum().sum()}")

display(dataset_ml.head())

==========================================================================================
DATASET PARA MACHINE LEARNING
==========================================================================================

Observaciones : 528
Variables     : 10
Duplicados    : 0
Nulos totales : 192

    ONI  PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS  Precipitacion_mm  Radiacion_Solar  irca  VolumenUtilDiarioMasa  Humedad_Relativa  Temp_Min_C  Mes  Velocidad_Viento
0  0.68                                               99.0                                     2.70            17.78   7.4                    NaN             77.88        8.45    1              1.37
1  0.57                                               99.0                                     2.22            17.16   7.4                    NaN             78.83       13.72    2              1.14
2  0.57                                               99.0                                     5.25            16.63   7.4                    NaN             80.28       13.52    3              1.09
3  0.82                                               99.0                                     6.16            16.56   7.4                    NaN             80.32       12.81    4              1.07
4  1.03                                               99.0                                     3.27            16.00   7.4                    NaN             79.57       12.24    5              1.14

In [3]:
#==========================================================================================
# VALIDACIÓN ESTRUCTURAL
#==========================================================================================

print()

print("="*90)
print("VALIDACIÓN ESTRUCTURAL")
print("="*90)

print()

print("Tipos de datos")

display(dataset_ml.dtypes)

==========================================================================================
VALIDACIÓN ESTRUCTURAL
==========================================================================================

Tipos de datos

ONI                                                                         float64
PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS    float64
Precipitacion_mm                                                            float64
Radiacion_Solar                                                             float64
irca                                                                        float64
VolumenUtilDiarioMasa                                                       float64
Humedad_Relativa                                                            float64
Temp_Min_C                                                                  float64
Mes                                                                           int32
Velocidad_Viento                                                            float64
dtype: object

In [4]:
#==========================================================================================
# VALORES FALTANTES
#==========================================================================================

faltantes = pd.DataFrame({

    "Variable": dataset_ml.columns,

    "Valores_Faltantes": dataset_ml.isna().sum(),

    "Porcentaje":

        (

            dataset_ml.isna().sum()

            /

            len(dataset_ml)

            *

            100

        ).round(2)

})

display(faltantes)

                                                                                             Variable  Valores_Faltantes  Porcentaje
ONI                                                                                               ONI                  0        0.00
PORCENTAJE DE LA POBLACION CON ACCESO A METODOS...  PORCENTAJE DE LA POBLACION CON ACCESO A METODO...                  0        0.00
Precipitacion_mm                                                                     Precipitacion_mm                  0        0.00
Radiacion_Solar                                                                       Radiacion_Solar                  0        0.00
irca                                                                                             irca                  0        0.00
VolumenUtilDiarioMasa                                                           VolumenUtilDiarioMasa                192       36.36
Humedad_Relativa                                                                     Humedad_Relativa                  0        0.00
Temp_Min_C                                                                                 Temp_Min_C                  0        0.00
Mes                                                                                               Mes                  0        0.00
Velocidad_Viento                                                                     Velocidad_Viento                  0        0.00

In [5]:
#==========================================================================================
# VARIABLES CONSTANTES
#==========================================================================================

constantes = dataset_ml.nunique()

constantes = constantes[constantes == 1]

print()

print("="*90)
print("VARIABLES CONSTANTES")
print("="*90)

print()

if len(constantes) == 0:

    print("No existen variables constantes.")

else:

    display(constantes)

==========================================================================================
VARIABLES CONSTANTES
==========================================================================================

No existen variables constantes.

In [6]:
#==========================================================================================
# RESUMEN
#==========================================================================================

print()

print("="*90)
print("RESUMEN DEL SCRIPT 25")
print("="*90)

print()

print(f"Observaciones           : {dataset_ml.shape[0]}")

print(f"Variables               : {dataset_ml.shape[1]}")

print(f"Valores faltantes       : {dataset_ml.isna().sum().sum()}")

print(f"Variables constantes    : {(dataset_ml.nunique()==1).sum()}")

==========================================================================================
RESUMEN DEL SCRIPT 25
==========================================================================================

Observaciones           : 528
Variables               : 10
Valores faltantes       : 192
Variables constantes    : 0

**¿Cuál será la variable objetivo (Target)?**

| Variable | Tipo |
| :--- | :--- |
| Precipitacion_mm | Predictora |
| ONI | Predictora |
| Radiacion_Solar | Predictora |
| Humedad_Relativa | Predictora |
| Temp_Min_C | Predictora |
| Mes | Predictora |
| Velocidad_Viento | Predictora |
| irca | ¿Predictora o Target? |
| VolumenUtilDiarioMasa | ¿Predictora o Target? |

---

**Escenario 1 (el que considero más fuerte) Predecir el volumen útil diario del embalse**

* Target:

  * VolumenUtilDiarioMasa

* Variables explicativas:

  * Precipitacion_mm
  * ONI
  * Radiacion_Solar
  * Humedad_Relativa
  * Temp_Min_C
  * Mes
  * Velocidad_Viento
  * irca

Este escenario responde preguntas como: ***¿Cómo evolucionará la disponibilidad hídrica?***

Es muy alineado con gestión del recurso hídrico.

---

**Escenario 2 Predecir el IRCA**

* Target:

  * irca

* Variables explicativas:

  * clima
  * volumen
  * estacionalidad

Este escenario responde: **¿Cómo evolucionará la calidad del agua?***

---

**Escenario 3**

El Framework no está diseñado para un único problema.

Está diseñado para seleccionar variables.

Por eso seria crear el Framework independiente del modelo.

Es decir:

* Construir un Dataset Optimizado

  * Modelo Hidrológico (Target: VolumenUtilDiarioMasa)
  * Modelo Calidad del Agua (Targe: irca)

De esta forma el Framework sirve para múltiples problemas.

## **M1. Diagnóstico Estadístico para Machine Learning**

In [7]:
#==========================================================================================
# SCRIPT 26
# DIAGNÓSTICO ESTADÍSTICO PARA MACHINE LEARNING
#==========================================================================================
#
# Objetivo
#
# Evaluar el comportamiento estadístico de las variables
# seleccionadas para determinar la necesidad de aplicar
# transformaciones previas al entrenamiento.
#
#==========================================================================================

In [8]:
print("="*90)
print("RESUMEN ESTADÍSTICO")
print("="*90)

display(dataset_ml.describe().T)

==========================================================================================
RESUMEN ESTADÍSTICO
==========================================================================================

                                                    count          mean           std           min           25%           50%           75%           max
ONI                                                 528.0  1.663636e-01  9.388242e-01 -1.360000e+00 -5.525000e-01 -1.500000e-02  6.650000e-01  2.770000e+00
PORCENTAJE DE LA POBLACION CON ACCESO A METODOS...  528.0  9.317750e+01  1.477326e+01  2.538000e+01  9.072000e+01  9.900000e+01  9.900000e+01  1.000000e+02
Precipitacion_mm                                    528.0  6.066307e+00  3.708268e+00  0.000000e+00  3.085000e+00  5.845000e+00  8.372500e+00  1.832000e+01
Radiacion_Solar                                     528.0  1.658672e+01  1.696319e+00  1.197000e+01  1.545750e+01  1.649500e+01  1.750250e+01  2.233000e+01
irca                                                528.0  2.600000e+00  2.411736e+00  0.000000e+00  4.000000e-01  2.200000e+00  3.600000e+00  9.500000e+00
VolumenUtilDiarioMasa                               336.0  4.375035e+08  9.357910e+07  2.901419e+08  3.569414e+08  4.321748e+08  5.013049e+08  6.195856e+08
Humedad_Relativa                                    528.0  8.468187e+01  5.181825e+00  6.584000e+01  8.156000e+01  8.620000e+01  8.854000e+01  9.216000e+01
Temp_Min_C                                          528.0  1.110265e+01  2.474984e+00  4.130000e+00  9.185000e+00  1.126000e+01  1.314250e+01  1.667000e+01
Mes                                                 528.0  6.500000e+00  3.455326e+00  1.000000e+00  3.750000e+00  6.500000e+00  9.250000e+00  1.200000e+01
Velocidad_Viento                                    528.0  1.092746e+00  2.613885e-01  4.800000e-01  9.000000e-01  1.030000e+00  1.260000e+00  1.880000e+00

In [9]:
print("="*90)
print("ASIMETRÍA")
print("="*90)

asimetria = pd.DataFrame({

    "Variable": dataset_ml.columns,

    "Asimetria": dataset_ml.skew().round(3)

})

display(asimetria)

==========================================================================================
ASIMETRÍA
==========================================================================================

                                                                                             Variable  Asimetria
ONI                                                                                               ONI      0.891
PORCENTAJE DE LA POBLACION CON ACCESO A METODOS...  PORCENTAJE DE LA POBLACION CON ACCESO A METODO...     -3.296
Precipitacion_mm                                                                     Precipitacion_mm      0.657
Radiacion_Solar                                                                       Radiacion_Solar      0.436
irca                                                                                             irca      1.018
VolumenUtilDiarioMasa                                                           VolumenUtilDiarioMasa      0.124
Humedad_Relativa                                                                     Humedad_Relativa     -1.056
Temp_Min_C                                                                                 Temp_Min_C     -0.216
Mes                                                                                               Mes      0.000
Velocidad_Viento                                                                     Velocidad_Viento      0.680

In [10]:
print("="*90)
print("CURTOSIS")
print("="*90)

curtosis = pd.DataFrame({

    "Variable": dataset_ml.columns,

    "Curtosis": dataset_ml.kurt().round(3)

})

display(curtosis)

==========================================================================================
CURTOSIS
==========================================================================================

                                                                                             Variable  Curtosis
ONI                                                                                               ONI     0.242
PORCENTAJE DE LA POBLACION CON ACCESO A METODOS...  PORCENTAJE DE LA POBLACION CON ACCESO A METODO...    10.609
Precipitacion_mm                                                                     Precipitacion_mm     0.220
Radiacion_Solar                                                                       Radiacion_Solar     0.519
irca                                                                                             irca     0.361
VolumenUtilDiarioMasa                                                           VolumenUtilDiarioMasa    -1.093
Humedad_Relativa                                                                     Humedad_Relativa     0.723
Temp_Min_C                                                                                 Temp_Min_C    -0.850
Mes                                                                                               Mes    -1.217
Velocidad_Viento                                                                     Velocidad_Viento    -0.071

In [11]:
#==========================================================================================
# DETECCIÓN DE VALORES ATÍPICOS (IQR)
#==========================================================================================

outliers = []

for columna in dataset_ml.columns:

    # Variables binarias
    if dataset_ml[columna].nunique() <= 2:

        cantidad = np.nan

    else:

        q1 = dataset_ml[columna].quantile(0.25)

        q3 = dataset_ml[columna].quantile(0.75)

        iqr = q3 - q1

        inferior = q1 - 1.5 * iqr

        superior = q3 + 1.5 * iqr

        cantidad = (

            (

                dataset_ml[columna] < inferior

            )

            |

            (

                dataset_ml[columna] > superior

            )

        ).sum()

    outliers.append(

        [

            columna,

            cantidad

        ]

    )

outliers = pd.DataFrame(

    outliers,

    columns=[

        "Variable",

        "Outliers"

    ]

)

print()

print("="*90)
print("DETECCIÓN DE VALORES ATÍPICOS (IQR)")
print("="*90)

display(outliers)

==========================================================================================
DETECCIÓN DE VALORES ATÍPICOS (IQR)
==========================================================================================

                                            Variable  Outliers
0                                                ONI        12
1  PORCENTAJE DE LA POBLACION CON ACCESO A METODO...        36
2                                   Precipitacion_mm         7
3                                    Radiacion_Solar        16
4                                               irca        12
5                              VolumenUtilDiarioMasa         0
6                                   Humedad_Relativa         6
7                                         Temp_Min_C         0
8                                                Mes         0
9                                   Velocidad_Viento         5

In [12]:
variable = "VolumenUtilDiarioMasa"

print("Mínimo:", dataset_ml[variable].min())
print("Máximo:", dataset_ml[variable].max())
print("Media:", dataset_ml[variable].mean())

print("\nValores únicos:")
print(
    sorted(
        dataset_ml[variable].unique()
    )
)

print("\nFrecuencias:")
print(
    dataset_ml[variable].value_counts(
        dropna=False
    ).sort_index()
)

Mínimo: 290141870.9677419
Máximo: 619585580.6451613
Media: 437503454.9203588

Valores únicos:
[np.float64(nan), np.float64(290141870.9677419), np.float64(294335733.3333333), np.float64(294729838.7096774), np.float64(296661366.6666667), np.float64(300381750.0), np.float64(300844166.6666667), np.float64(307606161.2903226), np.float64(308249466.6666667), np.float64(314703548.3870968), np.float64(318710096.7741935), np.float64(318859483.8709677), np.float64(321075166.6666667), np.float64(321782800.0), np.float64(321908612.9032258), np.float64(322214612.9032258), np.float64(323125516.1290323), np.float64(328335333.3333333), np.float64(333583677.4193549), np.float64(336433612.9032258), np.float64(341265620.6896552), np.float64(349228892.8571429), np.float64(359512233.3333333), np.float64(365105645.1612903), np.float64(366243806.4516129), np.float64(375310870.9677419), np.float64(381478322.5806451), np.float64(385040666.6666667), np.float64(390054870.9677419), np.float64(392567870.9677419), np.float64(393645387.0967742), np.float64(399258666.6666667), np.float64(404057525.22251344), np.float64(406067148.63389605), np.float64(408355533.3333333), np.float64(410084325.54677624), np.float64(415953221.1842923), np.float64(419985419.3548387), np.float64(420179937.2385342), np.float64(420453907.316438), np.float64(425201780.0626455), np.float64(431375571.8475586), np.float64(431913246.9590105), np.float64(432436285.7142857), np.float64(434575580.6451613), np.float64(436014398.6951263), np.float64(453196074.1935484), np.float64(453861348.6660087), np.float64(454864354.8387097), np.float64(456232800.0), np.float64(461579258.0645161), np.float64(467863193.5483871), np.float64(470190161.2903226), np.float64(474543580.6451613), np.float64(474841700.0), np.float64(478472875.0), np.float64(481237600.0), np.float64(481637366.6666667), np.float64(486531533.3333333), np.float64(486848766.6666667), np.float64(492346387.0967742), np.float64(498158200.0), np.float64(499495096.7741935), np.float64(500117677.4193549), np.float64(504866451.6129032), np.float64(525531655.1724138), np.float64(532957096.7741935), np.float64(540964821.4285715), np.float64(544803032.2580645), np.float64(545696451.6129032), np.float64(549053833.3333334), np.float64(550557806.451613), np.float64(554029645.1612903), np.float64(555273322.5806452), np.float64(556572100.0), np.float64(558005533.3333334), np.float64(563669580.6451613), np.float64(564248741.9354838), np.float64(577965033.3333334), np.float64(580021806.451613), np.float64(594481666.6666666), np.float64(597035354.8387097), np.float64(599453806.451613), np.float64(614449366.6666666), np.float64(619585580.6451613)]

Frecuencias:
VolumenUtilDiarioMasa
2.901419e+08      4
2.943357e+08      4
2.947298e+08      4
2.966614e+08      4
3.003818e+08      4
               ...
5.970354e+08      4
5.994538e+08      4
6.144494e+08      4
6.195856e+08      4
NaN             192
Name: count, Length: 85, dtype: int64

In [13]:
#==========================================================================================
# RECOMENDACIÓN PARA PREPROCESAMIENTO
#==========================================================================================

def recomendacion(variable, asimetria):

    # Variables binarias

    if dataset_ml[variable].nunique() <= 2:

        return "Variable binaria. No requiere transformación."

    if abs(asimetria) < 0.5:

        return "No requiere transformación."

    elif abs(asimetria) < 1:

        return "Evaluar estandarización."

    else:

        return "Considerar escalamiento robusto."

In [14]:
diagnostico = asimetria.merge(

    outliers,

    on="Variable"

)

diagnostico["Recomendacion"] = diagnostico.apply(

    lambda fila:

    recomendacion(

        fila["Variable"],

        fila["Asimetria"]

    ),

    axis=1

)

display(diagnostico)

                                            Variable  Asimetria  Outliers                     Recomendacion
0                                                ONI      0.891        12          Evaluar estandarización.
1  PORCENTAJE DE LA POBLACION CON ACCESO A METODO...     -3.296        36  Considerar escalamiento robusto.
2                                   Precipitacion_mm      0.657         7          Evaluar estandarización.
3                                    Radiacion_Solar      0.436        16       No requiere transformación.
4                                               irca      1.018        12  Considerar escalamiento robusto.
5                              VolumenUtilDiarioMasa      0.124         0       No requiere transformación.
6                                   Humedad_Relativa     -1.056         6  Considerar escalamiento robusto.
7                                         Temp_Min_C     -0.216         0       No requiere transformación.
8                                                Mes      0.000         0       No requiere transformación.
9                                   Velocidad_Viento      0.680         5          Evaluar estandarización.

**1. Resumen estadístico**

El conjunto de datos está conformado por 528 observaciones y 10 variables seleccionadas mediante el índice IPML.

Se evidencia que:

* Nueve variables presentan cobertura completa.
* `VolumenUtilDiarioMasa` presenta 192 valores faltantes (36.36%), conservando 336 registros disponibles.
* No existen variables constantes.
* Las variables conservan sus valores continuos originales; `irca` y `VolumenUtilDiarioMasa` no son variables binarias.

---

**2. Asimetría**

El diagnóstico de asimetría obtenido sobre el dataset vigente muestra:

| Variable | Asimetría |
| :--- | ---: |
| ONI | 0.891 |
| PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS | -3.296 |
| Precipitacion_mm | 0.657 |
| Radiacion_Solar | 0.436 |
| irca | 1.018 |
| VolumenUtilDiarioMasa | 0.124 |
| Humedad_Relativa | -1.056 |
| Temp_Min_C | -0.216 |
| Mes | 0.000 |
| Velocidad_Viento | 0.680 |

El diagnóstico se conserva como insumo para las decisiones posteriores de preprocesamiento.

---

**3. Curtosis**

La curtosis fue calculada sobre las 10 variables del dataset vigente.

Se destacan:

* Saneamiento: 10.609
* irca: 0.361
* VolumenUtilDiarioMasa: -1.093
* Humedad_Relativa: 0.723
* Mes: -1.217

Estos resultados sustituyen el diagnóstico histórico basado en las versiones binarias de `irca` y `VolumenUtilDiarioMasa`.

---

**4. Valores atípicos**

La detección mediante IQR se aplicó sobre las variables actuales sin modificar ni eliminar observaciones.

Resultados principales:

* ONI: 12
* Saneamiento: 36
* Precipitacion_mm: 7
* Radiacion_Solar: 16
* irca: 12
* VolumenUtilDiarioMasa: 0
* Humedad_Relativa: 6
* Temp_Min_C: 0
* Mes: 0
* Velocidad_Viento: 5

Los valores detectados se consideran únicamente un diagnóstico estadístico en esta etapa.

---

**5. Recomendaciones de preprocesamiento**

La función de recomendación genera el siguiente diagnóstico:

* `Evaluar estandarización`: ONI, Precipitacion_mm y Velocidad_Viento.
* `Considerar escalamiento robusto`: saneamiento, irca y Humedad_Relativa.
* `No requiere transformación`: Radiacion_Solar, VolumenUtilDiarioMasa, Temp_Min_C y Mes.

Estas recomendaciones son diagnósticas y no implican por sí mismas una modificación automática de los datos.

In [15]:
print("="*90)
print("Exportación")
print("="*90)

diagnostico.to_csv(

    "diagnostico_estadistico_ml.csv",

    index=False,

    encoding="utf-8-sig"

)

diagnostico.to_excel(

    "diagnostico_estadistico_ml.xlsx",

    index=False

)

==========================================================================================
Exportación
==========================================================================================

## **M2. Preparación, Transformación y Escalamiento del Dataset para Machine Learning - Experimentos**

Objetivo: Aplicar las transformaciones y técnicas de escalamiento definidas a partir del diagnóstico estadístico, generando un nuevo dataset optimizado para el entrenamiento de modelos de Machine Learning.

**Análisis de la Normalización y Optimización**

El proceso de normalización y optimización se realizó en varias etapas, buscando preparar el dataset de la mejor manera para el entrenamiento de modelos de Machine Learning. A continuación, se detalla el análisis de cada paso:

**1. Diagnóstico Estadístico**

Se realizó un diagnóstico exhaustivo de las variables del dataset para entender su distribución y detectar posibles problemas como asimetría, curtosis y valores atípicos. Los resultados clave fueron:

*   **Resumen Estadístico (`.describe().T`)**: Proporcionó una visión general de la centralidad, dispersión y forma de la distribución de cada variable.
*   **Asimetría (`.skew().round(3)`)**: Se calculó la asimetría para cada variable. Se identificaron variables con asimetría significativa (positiva o negativa), lo cual es crucial para la elección del método de escalado.
    *   `irca` y `VolumenUtilDiarioMasa` mostraron una fuerte asimetría positiva, debido a su naturaleza binaria.
    *   `Precipitacion_mm`, `ONI`, `Velocidad_Viento` mostraron ligera asimetría positiva.
    *   `Humedad_Relativa` mostró asimetría negativa.
*   **Curtosis (`.kurt().round(3)`)**: La curtosis confirmó la forma de las distribuciones, especialmente la concentración de valores en las variables binarias (`irca`, `VolumenUtilDiarioMasa`).
*   **Detección de Valores Atípicos (IQR)**: Se utilizó el método del rango intercuartílico (IQR) para identificar posibles valores atípicos. Se observó que este método identificaba 'outliers' en las variables binarias, lo cual se interpretó como una consecuencia de la naturaleza de estas variables y no como un problema real de datos atípicos, sugiriendo una mejora metodológica para excluir variables binarias de esta detección.

**2. Recomendación para Preprocesamiento**

Basado en el diagnóstico estadístico, se implementó una función (`recomendacion`) para sugerir el tipo de transformación necesario para cada variable:

*   **Variables binarias**: No requieren transformación.
*   **Asimetría `abs(asimetria) < 0.5`**: No requieren transformación.
*   **Asimetría `0.5 <= abs(asimetria) < 1`**: Evaluar estandarización.
*   **Asimetría `abs(asimetria) >= 1`**: Considerar escalamiento robusto (o transformación logarítmica si no es binaria).

Esta función generó un diagnóstico (`diagnostico`) que incluyó una columna de 'Recomendacion' para cada variable, guiando las decisiones de preprocesamiento.

**3. Aplicación Automática del Método de Transformación**

El Framework tomó una decisión automática sobre el método de escalado a aplicar a las variables predictoras (X) basándose en el número de variables con alta asimetría y/o presencia de outliers:

*   **Decisión**: Si el número de variables con asimetría `abs(asimetria) > 1` es igual o superior a 2, O si el número de variables con más de 10 outliers es igual o superior a 2, se opta por `RobustScaler`. En caso contrario, se selecciona `StandardScaler`.
*   **Ejecución**: Para el dataset actual, se determinó `RobustScaler` debido a la presencia de 3 variables muy asimétricas (`Precipitacion_mm`, `Humedad_Relativa`, `VolumenUtilDiarioMasa`) y 2 con outliers (`Precipitacion_mm`, `VolumenUtilDiarioMasa`).
*   **Resultado**: Las variables predictoras (`X`) fueron transformadas utilizando el `RobustScaler`, generando `X_transformado`. Esta transformación es más adecuada para datos que contienen muchos valores atípicos o no siguen una distribución normal, ya que utiliza la mediana y el rango intercuartílico, siendo menos sensible a los extremos.

Finalmente, el dataset transformado (`dataset_transformado`) fue reconstruido, uniendo las variables predictoras escaladas con la variable objetivo sin transformar. Este dataset está ahora optimizado y listo para la siguiente fase de construcción de secuencias temporales para el modelado de Machine Learning.

In [16]:
#==========================================================================================
# CARGA DEL DATASET MAESTRO
#==========================================================================================

import pandas as pd

url_dataset = (

"https://raw.githubusercontent.com/jriatiga/FRAMEWORK_V7/refs/heads/main/DATA/MASTER/C09_MASTER/Dataset_Maestro_Framework_v04.parquet"

)

dataset = pd.read_parquet(url_dataset)

print()

print("="*90)
print("DATASET MAESTRO")
print("="*90)

print()

print(f"Observaciones : {dataset.shape[0]}")

print(f"Variables     : {dataset.shape[1]}")

display(dataset.head())

==========================================================================================
DATASET MAESTRO
==========================================================================================

Observaciones : 528
Variables     : 52

,Nodo,Fecha,Precipitacion_mm,Temp_Max_C,Temp_Min_C,Temp_Media_C,Humedad_Relativa,Velocidad_Viento,Radiacion_Solar,Anio,Mes,ONI,Estado_ENSO,VolumenUtilDiarioMasa,irca,nivel_de_riesgo,POBLACION TOTAL,DENSIDAD POBLACIONAL,INDICE DE DESEMPENO INSTITUCIONAL,ACCESO A AGUA POTABLE ADECUADO,PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS,COBERTURA DE ACUEDUCTO URBANO,COBERTURA DE ACUEDUCTO RURAL,COBERTURA DE ALCANTARILLADO URBANO,COBERTURA DE ALCANTARILLADO RURAL,CONTINUIDAD DE ACUEDUCTO URBANO,CALIDAD DEL AGUA,AGUAS RESIDUALES TRATADAS,Nivel_Minimo,CONDUCTIVIDAD ELECTRICA,DEMANDA BIOQUIMICA DE OXIGENO (DBO5),DEMANDA QUIMICA DE OXIGENO (DQO),FOSFORO TOTAL,NITROGENO TOTAL,OXIGENO DISUELTO (OD),SOLIDOS SUSPENDIDOS TOTALES,TEMPERATURA,TURBIDEZ,pH,IRCA_Imputado,Volumen_Imputado,Poblacion_Imputada,Densidad_Imputada,AguaPotable_Imputada,Saneamiento_Imputado,AcueductoUrbano_Imputado,AcueductoRural_Imputado,AlcantarilladoUrbano_Imputado,AlcantarilladoRural_Imputado,Version_Dataset,IRCA_Fuente,Volumen_Fuente
0,Bogota_Sabana,2015-01-01,2.70,25.30,8.45,18.26,77.88,1.37,17.78,2015,1,0.68,Niño,NaN,7.4,Riesgo bajo,148415.0,1952.83,NaN,100.0,99.0,100.0,100.0,84.66,61.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,1,1,1,1,1,1,1,V04,Original,Sin dato
1,Bogota_Sabana,2015-02-01,2.22,26.14,13.72,19.02,78.83,1.14,17.16,2015,2,0.57,Niño,NaN,7.4,Riesgo bajo,148415.0,1952.83,NaN,100.0,99.0,100.0,100.0,84.66,61.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,1,1,1,1,1,1,1,V04,Original,Sin dato
2,Bogota_Sabana,2015-03-01,5.25,27.56,13.52,19.15,80.28,1.09,16.63,2015,3,0.57,Niño,NaN,7.4,Riesgo bajo,148415.0,1952.83,NaN,100.0,99.0,100.0,100.0,84.66,61.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,1,1,1,1,1,1,1,V04,Original,Sin dato
3,Bogota_Sabana,2015-04-01,6.16,25.50,12.81,19.07,80.32,1.07,16.56,2015,4,0.82,Niño,NaN,7.4,Riesgo bajo,148415.0,1952.83,NaN,100.0,99.0,100.0,100.0,84.66,61.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,1,1,1,1,1,1,1,V04,Original,Sin dato
4,Bogota_Sabana,2015-05-01,3.27,25.52,12.24,18.99,79.57,1.14,16.00,2015,5,1.03,Niño,NaN,7.4,Riesgo bajo,148415.0,1952.83,NaN,100.0,99.0,100.0,100.0,84.66,61.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,1,1,1,1,1,1,1,V04,Original,Sin dato

In [17]:
#==========================================================================================
# CARGA DE LA CLASIFICACIÓN IPML FINAL
#==========================================================================================

url_ipml = (
    "https://raw.githubusercontent.com/jriatiga/FRAMEWORK_V7/refs/heads/main/DATA/MASTER/C11_MASTER/Preparacion_Machine_Learning/ipm/clasificacion_ipml.csv"
)

ipml = pd.read_csv(url_ipml)

print()
print("=" * 90)
print("CLASIFICACIÓN IPML FINAL")
print("=" * 90)
print()

print(f"Variables : {ipml.shape[0]}")
print(f"Columnas  : {ipml.shape[1]}")

print()
print("Estado_Final:")
print(ipml["Estado_Final"].value_counts())

==========================================================================================
CLASIFICACIÓN IPML FINAL
==========================================================================================

Variables : 35
Columnas  : 23

Estado_Final:
Estado_Final
No Prioritaria             20
Seleccionada               10
Pendiente por Cobertura     5
Name: count, dtype: int64

In [18]:
#==========================================================================================
# VALIDACIÓN DE LA CLASIFICACIÓN IPML FINAL
#==========================================================================================

print()
print("=" * 90)
print("VALIDACIÓN DE ESTADO FINAL IPML")
print("=" * 90)
print()

conteo_estados = ipml["Estado_Final"].value_counts()

print(conteo_estados)

assert len(ipml) == 35, "ERROR: el universo IPML debe contener 35 variables."

assert conteo_estados.get("Seleccionada", 0) == 10, \
    "ERROR: se esperaban 10 variables seleccionadas."

assert conteo_estados.get("Pendiente por Cobertura", 0) == 5, \
    "ERROR: se esperaban 5 variables pendientes por cobertura."

assert conteo_estados.get("No Prioritaria", 0) == 20, \
    "ERROR: se esperaban 20 variables no prioritarias."

print()
print("Clasificación IPML final validada correctamente.")

==========================================================================================
VALIDACIÓN DE ESTADO FINAL IPML
==========================================================================================

Estado_Final
No Prioritaria             20
Seleccionada               10
Pendiente por Cobertura     5
Name: count, dtype: int64

Clasificación IPML final validada correctamente.

## **M3. Variable Objetivo**

In [19]:
#==========================================================
# M3
# VARIABLE OBJETIVO
#==========================================================

import pandas as pd

URL_CATALOGO = (
    "https://raw.githubusercontent.com/jriatiga/"
    "FRAMEWORK_V7/refs/heads/main/"
    "DATA/DISENO_EXPERIMENTAL/"
    "catalogo_experimentos.xlsx"
)

catalogo = pd.read_excel(URL_CATALOGO)

print("Catálogo Experimental cargado.")

display(catalogo.head())

Catálogo Experimental cargado.

,Experimento,Dominio,Pregunta_Investigacion,Objetivo_Experimento,Variable_Objetivo,Variable_Objetivo_Modelo,Tipo_Problema,Numero_Predictores,Registros_Disponibles,Cobertura_%,Registros_Objetivo_Modelo,Cobertura_Objetivo_Modelo_%,Ventana,Horizonte,Modelo,Estado,Umbral_Cobertura_%,Viabilidad,Motivo_Viabilidad
0,Exp01,Gestión Hídrica,¿Es posible anticipar el riesgo sanitario del ...,Evaluar la capacidad del Framework para predec...,irca,nivel_de_riesgo,Clasificación,9,528,100.00,528,100.00,12,1,LSTM,Pendiente,50,Viable,Cobertura de la variable objetivo suficiente p...
1,Exp02,Gestión Hídrica,¿Qué factores permiten anticipar el estado gen...,Evaluar la capacidad del Framework para predec...,CALIDAD DEL AGUA,CALIDAD DEL AGUA,Clasificación,10,96,18.18,96,18.18,12,1,LSTM,Pendiente,50,No viable,Cobertura de la variable objetivo inferior al ...
2,Exp03,Gestión Hídrica,¿Es posible anticipar la disminución del nivel...,Evaluar la capacidad predictiva del Framework ...,Nivel_Minimo,Nivel_Minimo,Regresión,10,87,16.48,87,16.48,12,1,LSTM,Pendiente,50,No viable,Cobertura de la variable objetivo inferior al ...
3,Exp04,Gestión Hídrica,¿Qué variables permiten anticipar el volumen ú...,Evaluar la capacidad del Framework para predec...,VolumenUtilDiarioMasa,VolumenUtilDiarioMasa,Regresión,9,336,63.64,336,63.64,12,1,LSTM,Pendiente,50,Viable,Cobertura de la variable objetivo suficiente p...
4,Exp05,Gestión Hídrica,¿Es posible anticipar procesos de contaminació...,Evaluar la capacidad predictiva del Framework ...,DEMANDA BIOQUIMICA DE OXIGENO (DBO5),DEMANDA BIOQUIMICA DE OXIGENO (DBO5),Regresión,10,26,4.92,26,4.92,12,1,LSTM,Pendiente,50,No viable,Cobertura de la variable objetivo inferior al ...

In [20]:
print(catalogo.columns.tolist())

['Experimento', 'Dominio', 'Pregunta_Investigacion', 'Objetivo_Experimento', 'Variable_Objetivo', 'Variable_Objetivo_Modelo', 'Tipo_Problema', 'Numero_Predictores', 'Registros_Disponibles', 'Cobertura_%', 'Registros_Objetivo_Modelo', 'Cobertura_Objetivo_Modelo_%', 'Ventana', 'Horizonte', 'Modelo', 'Estado', 'Umbral_Cobertura_%', 'Viabilidad', 'Motivo_Viabilidad']

In [21]:
# Seleccionar el Experimento
#EXPERIMENTO = "Exp04"
EXPERIMENTO = "Exp04"

In [22]:
# Buscar automáticamente la configuración
configuracion = catalogo.loc[
    catalogo["Experimento"] == EXPERIMENTO
].iloc[0]

In [23]:
#==========================================================================================
# RECUPERAR TODA LA CONFIGURACIÓN
#==========================================================================================

# Variable que define científicamente el experimento
VARIABLE_OBJETIVO = configuracion[
    "Variable_Objetivo"
]

# Variable realmente utilizada como y por el modelo
VARIABLE_OBJETIVO_MODELO = configuracion[
    "Variable_Objetivo_Modelo"
]

# Tipo de problema
TIPO_PROBLEMA = configuracion[
    "Tipo_Problema"
]

# Dominio experimental
DOMINIO = configuracion[
    "Dominio"
]

# Parámetros temporales
VENTANA = int(
    configuracion["Ventana"]
)

HORIZONTE = int(
    configuracion["Horizonte"]
)

In [24]:
print()

print("=" * 90)
print("CONFIGURACIÓN DEL EXPERIMENTO")
print("=" * 90)

print()

print(f"Experimento              : {EXPERIMENTO}")
print(f"Dominio                  : {DOMINIO}")
print(f"Variable objetivo        : {VARIABLE_OBJETIVO}")
print(f"Variable objetivo modelo : {VARIABLE_OBJETIVO_MODELO}")
print(f"Tipo de problema         : {TIPO_PROBLEMA}")
print(f"Ventana temporal         : {VENTANA}")
print(f"Horizonte                : {HORIZONTE}")

==========================================================================================
CONFIGURACIÓN DEL EXPERIMENTO
==========================================================================================

Experimento              : Exp04
Dominio                  : Gestión Hídrica
Variable objetivo        : VolumenUtilDiarioMasa
Variable objetivo modelo : VolumenUtilDiarioMasa
Tipo de problema         : Regresión
Ventana temporal         : 12
Horizonte                : 1

## **M4. Recuperación Automática de Variables Predictoras**

In [25]:
import pandas as pd

URL_VARIABLES = (
    "https://raw.githubusercontent.com/jriatiga/"
    "FRAMEWORK_V7/refs/heads/main/"
    "DATA/MASTER/C11_MASTER/"
    "Preparacion_Machine_Learning/ipm/"
    "variables_machine_learning.csv"
)

df_variables = pd.read_csv(
    URL_VARIABLES
)

print()
print("=" * 90)
print("M4.1 - VARIABLES SELECCIONADAS POR C11")
print("=" * 90)

print()
print("Registros :", len(df_variables))
print("Columnas  :", df_variables.shape[1])

print()

display(
    df_variables[
        [
            "Ranking",
            "Variable",
            "IPML",
            "Nivel_IPML",
            "Estado_Final"
        ]
    ]
)

==========================================================================================
M4.1 - VARIABLES SELECCIONADAS POR C11
==========================================================================================

Registros : 10
Columnas  : 23

   Ranking                                           Variable    IPML Nivel_IPML  Estado_Final
0        1                                                ONI  1.0000   Muy Alta  Seleccionada
1        2  PORCENTAJE DE LA POBLACION CON ACCESO A METODO...  1.0000   Muy Alta  Seleccionada
2        3                                   Precipitacion_mm  1.0000   Muy Alta  Seleccionada
3        4                                    Radiacion_Solar  1.0000   Muy Alta  Seleccionada
4        5                                               irca  1.0000   Muy Alta  Seleccionada
5        6                              VolumenUtilDiarioMasa  0.9636   Muy Alta  Seleccionada
6        7                                   Humedad_Relativa  0.9500   Muy Alta  Seleccionada
7       12                                         Temp_Min_C  0.9000   Muy Alta  Seleccionada
8       13                                                Mes  0.8668       Alta  Seleccionada
9       14                                   Velocidad_Viento  0.8668       Alta  Seleccionada

In [26]:
#==========================================================================================
# M4.2
# RECUPERACIÓN AUTOMÁTICA DE VARIABLES PREDICTORAS
#==========================================================================================

variables_predictoras = (

    df_variables["Variable"]

    .tolist()

)

print()

print("="*90)
print("VARIABLES RECUPERADAS DEL FRAMEWORK")
print("="*90)

print()

print(f"Total de variables : {len(variables_predictoras)}")

print()

for variable in variables_predictoras:

    print(f"- {variable}")

==========================================================================================
VARIABLES RECUPERADAS DEL FRAMEWORK
==========================================================================================

Total de variables : 10

- ONI
- PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS
- Precipitacion_mm
- Radiacion_Solar
- irca
- VolumenUtilDiarioMasa
- Humedad_Relativa
- Temp_Min_C
- Mes
- Velocidad_Viento

In [27]:
#==========================================================================================
# M4.3
# ELIMINACIÓN DE VARIABLES OBJETIVO DE LAS PREDICTORAS
#==========================================================================================

#------------------------------------------------------------------------------------------
# Recuperación defensiva de la configuración
#------------------------------------------------------------------------------------------

try:
    _ = VARIABLE_OBJETIVO
    _ = VARIABLE_OBJETIVO_MODELO

except NameError:

    import pandas as pd

    URL_CATALOGO = (
        "https://raw.githubusercontent.com/jriatiga/"
        "FRAMEWORK_V7/refs/heads/main/"
        "DATA/DISENO_EXPERIMENTAL/"
        "catalogo_experimentos.xlsx"
    )

    catalogo = pd.read_excel(
        URL_CATALOGO
    )

    configuracion = catalogo.loc[
        catalogo["Experimento"] == EXPERIMENTO
    ].iloc[0]

    VARIABLE_OBJETIVO = configuracion[
        "Variable_Objetivo"
    ]

    VARIABLE_OBJETIVO_MODELO = configuracion[
        "Variable_Objetivo_Modelo"
    ]

#------------------------------------------------------------------------------------------
# Exclusión de cualquier objetivo de X
#------------------------------------------------------------------------------------------

variables_predictoras = [
    variable
    for variable in variables_predictoras
    if variable not in {
        VARIABLE_OBJETIVO,
        VARIABLE_OBJETIVO_MODELO
    }
]

#------------------------------------------------------------------------------------------
# Controles
#------------------------------------------------------------------------------------------

fuga_objetivo = (
    VARIABLE_OBJETIVO
    in variables_predictoras
)

fuga_objetivo_modelo = (
    VARIABLE_OBJETIVO_MODELO
    in variables_predictoras
)

print()

print("=" * 90)
print("VARIABLES OBJETIVO EXCLUIDAS DE LAS PREDICTORAS")
print("=" * 90)

print()

print(
    f"Variable objetivo        : {VARIABLE_OBJETIVO}"
)

print(
    f"Variable objetivo modelo : {VARIABLE_OBJETIVO_MODELO}"
)

print()

print(
    f"Variables predictoras    : {len(variables_predictoras)}"
)

print(
    f"Fuga objetivo -> X       : {fuga_objetivo}"
)

print(
    f"Fuga objetivo modelo -> X: {fuga_objetivo_modelo}"
)

print()

for variable in variables_predictoras:
    print(f"- {variable}")

==========================================================================================
VARIABLES OBJETIVO EXCLUIDAS DE LAS PREDICTORAS
==========================================================================================

Variable objetivo        : VolumenUtilDiarioMasa
Variable objetivo modelo : VolumenUtilDiarioMasa

Variables predictoras    : 9
Fuga objetivo -> X       : False
Fuga objetivo modelo -> X: False

- ONI
- PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS
- Precipitacion_mm
- Radiacion_Solar
- irca
- Humedad_Relativa
- Temp_Min_C
- Mes
- Velocidad_Viento

In [28]:
#==========================================================================================
# VALIDACIÓN DE VARIABLES
#==========================================================================================

import pandas as pd

#------------------------------------------------------------------------------------------
# Recuperación defensiva del Dataset Maestro
#------------------------------------------------------------------------------------------

try:
    _ = dataset

except NameError:

    URL_DATASET = (
        "https://raw.githubusercontent.com/jriatiga/"
        "FRAMEWORK_V7/refs/heads/main/"
        "DATA/MASTER/C09_MASTER/"
        "Dataset_Maestro_Framework_v04.parquet"
    )

    dataset = pd.read_parquet(
        URL_DATASET
    )

#------------------------------------------------------------------------------------------
# Variables requeridas por el experimento
#
# Incluye:
# - Predictoras de X
# - Objetivo científico
# - Objetivo real del modelo
#
# dict.fromkeys evita duplicar el objetivo cuando ambos coinciden,
# como ocurre en Exp04.
#------------------------------------------------------------------------------------------

variables_experimento = list(
    dict.fromkeys(
        variables_predictoras
        + [
            VARIABLE_OBJETIVO,
            VARIABLE_OBJETIVO_MODELO
        ]
    )
)

#------------------------------------------------------------------------------------------
# Validación contra Dataset Maestro
#------------------------------------------------------------------------------------------

faltantes = [
    variable
    for variable in variables_experimento
    if variable not in dataset.columns
]

if faltantes:

    raise Exception(
        "Variables inexistentes en el Dataset Maestro: "
        f"{faltantes}"
    )

#------------------------------------------------------------------------------------------
# Controles
#------------------------------------------------------------------------------------------

print()

print("=" * 90)
print("VALIDACIÓN DE VARIABLES")
print("=" * 90)

print()

print(
    "Variables predictoras     :",
    len(variables_predictoras)
)

print(
    "Variable objetivo         :",
    VARIABLE_OBJETIVO
)

print(
    "Variable objetivo modelo  :",
    VARIABLE_OBJETIVO_MODELO
)

print(
    "Variables experimento     :",
    len(variables_experimento)
)

print(
    "Variables faltantes       :",
    len(faltantes)
)

print()

print("Todas las variables existen.")

==========================================================================================
VALIDACIÓN DE VARIABLES
==========================================================================================

Variables predictoras     : 9
Variable objetivo         : VolumenUtilDiarioMasa
Variable objetivo modelo  : VolumenUtilDiarioMasa
Variables experimento     : 10
Variables faltantes       : 0

Todas las variables existen.

## **M5. Construcción Automática Del Conjunto Predictor**

In [29]:
#==========================================================================================
# CONSTRUCCION DEL EXPERIMENTO
#==========================================================================================

dataset_ml = dataset[
    variables_experimento
].copy()

print()

print("=" * 90)
print("DATASET DEL EXPERIMENTO")
print("=" * 90)

print()

print(
    f"Observaciones : {dataset_ml.shape[0]}"
)

print(
    f"Variables     : {dataset_ml.shape[1]}"
)

display(
    dataset_ml.head()
)

==========================================================================================
DATASET DEL EXPERIMENTO
==========================================================================================

Observaciones : 528
Variables     : 10

    ONI  PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS  Precipitacion_mm  Radiacion_Solar  irca  Humedad_Relativa  Temp_Min_C  Mes  Velocidad_Viento  VolumenUtilDiarioMasa
0  0.68                                               99.0                                     2.70            17.78   7.4             77.88        8.45    1              1.37                    NaN
1  0.57                                               99.0                                     2.22            17.16   7.4             78.83       13.72    2              1.14                    NaN
2  0.57                                               99.0                                     5.25            16.63   7.4             80.28       13.52    3              1.09                    NaN
3  0.82                                               99.0                                     6.16            16.56   7.4             80.32       12.81    4              1.07                    NaN
4  1.03                                               99.0                                     3.27            16.00   7.4             79.57       12.24    5              1.14                    NaN

## **M6. Validación de Viabilidad del Experimento**

In [30]:
#==========================================================================================
# M4.1
# CARGA DEL CATÁLOGO EXPERIMENTAL
#==========================================================================================

import pandas as pd

URL_CATALOGO = (

    "https://raw.githubusercontent.com/"
    "jriatiga/FRAMEWORK_V7/"
    "refs/heads/main/"
    "DATA/DISENO_EXPERIMENTAL/"
    "catalogo_experimentos.xlsx"

)

catalogo = pd.read_excel(URL_CATALOGO)

configuracion = catalogo.loc[

    catalogo["Experimento"] == EXPERIMENTO

].iloc[0]

print()

print("="*90)
print("CATÁLOGO EXPERIMENTAL")
print("="*90)

print()

display(configuracion)

==========================================================================================
CATÁLOGO EXPERIMENTAL
==========================================================================================

Experimento                                                                Exp04
Dominio                                                          Gestión Hídrica
Pregunta_Investigacion         ¿Qué variables permiten anticipar el volumen ú...
Objetivo_Experimento           Evaluar la capacidad del Framework para predec...
Variable_Objetivo                                          VolumenUtilDiarioMasa
Variable_Objetivo_Modelo                                   VolumenUtilDiarioMasa
Tipo_Problema                                                          Regresión
Numero_Predictores                                                             9
Registros_Disponibles                                                        336
Cobertura_%                                                                63.64
Registros_Objetivo_Modelo                                                    336
Cobertura_Objetivo_Modelo_%                                                63.64
Ventana                                                                       12
Horizonte                                                                      1
Modelo                                                                      LSTM
Estado                                                                 Pendiente
Umbral_Cobertura_%                                                            50
Viabilidad                                                                Viable
Motivo_Viabilidad              Cobertura de la variable objetivo suficiente p...
Name: 3, dtype: object

In [31]:
#==========================================================================================
# M4.2
# VARIABLES DEL EXPERIMENTO
#==========================================================================================

# Recuperar objetivos desde el catálogo
VARIABLE_OBJETIVO = configuracion[
    "Variable_Objetivo"
]

VARIABLE_OBJETIVO_MODELO = configuracion[
    "Variable_Objetivo_Modelo"
]

# Predictoras ya determinadas por el Framework
predictoras = variables_predictoras

# Construcción del conjunto completo del experimento
# dict.fromkeys evita duplicados cuando ambos objetivos coinciden (ej. Exp04)
variables_experimento = list(
    dict.fromkeys(
        predictoras
        + [
            VARIABLE_OBJETIVO,
            VARIABLE_OBJETIVO_MODELO
        ]
    )
)

print()

print("=" * 90)
print("VARIABLES DEL EXPERIMENTO")
print("=" * 90)

print()

print(
    f"Objetivo científico : {VARIABLE_OBJETIVO}"
)

print(
    f"Objetivo del modelo : {VARIABLE_OBJETIVO_MODELO}"
)

print()

print(
    f"Predictoras         : {len(predictoras)}"
)

print(
    f"Total experimento   : {len(variables_experimento)}"
)

print()

for v in predictoras:
    print("-", v)

==========================================================================================
VARIABLES DEL EXPERIMENTO
==========================================================================================

Objetivo científico : VolumenUtilDiarioMasa
Objetivo del modelo : VolumenUtilDiarioMasa

Predictoras         : 9
Total experimento   : 10

- ONI
- PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS
- Precipitacion_mm
- Radiacion_Solar
- irca
- Humedad_Relativa
- Temp_Min_C
- Mes
- Velocidad_Viento

In [32]:
#==========================================================================================
# M4.3
# COBERTURA DEL EXPERIMENTO
#==========================================================================================

dataset_exp = dataset_ml[variables_experimento]

cobertura = pd.DataFrame({

    "Variable": dataset_exp.columns,

    "% Cobertura": (
        dataset_exp.notna().mean() * 100
    ).round(2)

})

print()

print("="*90)
print("COBERTURA DEL EXPERIMENTO")
print("="*90)

print()

display(cobertura)

==========================================================================================
COBERTURA DEL EXPERIMENTO
==========================================================================================

                                                                                             Variable  % Cobertura
ONI                                                                                               ONI       100.00
PORCENTAJE DE LA POBLACION CON ACCESO A METODOS...  PORCENTAJE DE LA POBLACION CON ACCESO A METODO...       100.00
Precipitacion_mm                                                                     Precipitacion_mm       100.00
Radiacion_Solar                                                                       Radiacion_Solar       100.00
irca                                                                                             irca       100.00
Humedad_Relativa                                                                     Humedad_Relativa       100.00
Temp_Min_C                                                                                 Temp_Min_C       100.00
Mes                                                                                               Mes       100.00
Velocidad_Viento                                                                     Velocidad_Viento       100.00
VolumenUtilDiarioMasa                                                           VolumenUtilDiarioMasa        63.64

In [33]:
#==========================================================================================
# CLASIFICACIÓN DE COBERTURA
#==========================================================================================

def clasificar_cobertura(x):

    if x >= 90:
        return "Excelente"

    elif x >= 70:
        return "Buena"

    elif x >= 50:
        return "Aceptable"

    elif x >= 20:
        return "Baja"

    else:
        return "Insuficiente"

cobertura["Nivel_Cobertura"] = (

    cobertura["% Cobertura"]

    .apply(clasificar_cobertura)

)

display(cobertura)

                                                                                             Variable  % Cobertura Nivel_Cobertura
ONI                                                                                               ONI       100.00       Excelente
PORCENTAJE DE LA POBLACION CON ACCESO A METODOS...  PORCENTAJE DE LA POBLACION CON ACCESO A METODO...       100.00       Excelente
Precipitacion_mm                                                                     Precipitacion_mm       100.00       Excelente
Radiacion_Solar                                                                       Radiacion_Solar       100.00       Excelente
irca                                                                                             irca       100.00       Excelente
Humedad_Relativa                                                                     Humedad_Relativa       100.00       Excelente
Temp_Min_C                                                                                 Temp_Min_C       100.00       Excelente
Mes                                                                                               Mes       100.00       Excelente
Velocidad_Viento                                                                     Velocidad_Viento       100.00       Excelente
VolumenUtilDiarioMasa                                                           VolumenUtilDiarioMasa        63.64       Aceptable

In [34]:
#==========================================================================================
# DECISIÓN DEL FRAMEWORK
#==========================================================================================

#------------------------------------------------------------------------------------------
# Umbral de viabilidad de la variable objetivo
#
# Se conserva el umbral definido en el Diseño Experimental.
#------------------------------------------------------------------------------------------

UMBRAL_COBERTURA = float(
    configuracion["Umbral_Cobertura_%"]
)


#------------------------------------------------------------------------------------------
# Umbral de cobertura para variables predictoras
#
# C13 no realiza imputación de predictoras.
# Por tanto, una predictora destinada a una LSTM debe estar completa para evitar
# pérdida sistemática de ventanas temporales.
#------------------------------------------------------------------------------------------

UMBRAL_COBERTURA_PREDICTOR = 100.0


#------------------------------------------------------------------------------------------
# Inicialización
#------------------------------------------------------------------------------------------

cobertura["Decision"] = "No aplica"


#------------------------------------------------------------------------------------------
# Identificación de predictoras
#------------------------------------------------------------------------------------------

es_predictora = cobertura[
    "Variable"
].isin(
    predictoras
)


#------------------------------------------------------------------------------------------
# Decisión sobre predictoras
#------------------------------------------------------------------------------------------

cobertura.loc[
    es_predictora
    &
    (
        cobertura["% Cobertura"]
        >= UMBRAL_COBERTURA_PREDICTOR
    ),
    "Decision"
] = "Utilizar"


cobertura.loc[
    es_predictora
    &
    (
        cobertura["% Cobertura"]
        < UMBRAL_COBERTURA_PREDICTOR
    ),
    "Decision"
] = "Excluir"


#------------------------------------------------------------------------------------------
# Identificación explícita de los objetivos
#------------------------------------------------------------------------------------------

cobertura.loc[
    cobertura["Variable"]
    == VARIABLE_OBJETIVO,
    "Decision"
] = "Objetivo científico"


cobertura.loc[
    cobertura["Variable"]
    == VARIABLE_OBJETIVO_MODELO,
    "Decision"
] = "Objetivo modelo"


#------------------------------------------------------------------------------------------
# Predictoras excluidas por cobertura
#------------------------------------------------------------------------------------------

predictoras_excluidas_cobertura = cobertura.loc[

    es_predictora
    &
    (
        cobertura["% Cobertura"]
        < UMBRAL_COBERTURA_PREDICTOR
    ),

    "Variable"

].tolist()


#------------------------------------------------------------------------------------------
# Controles
#------------------------------------------------------------------------------------------

print()

print("=" * 90)
print("DECISIÓN DEL FRAMEWORK")
print("=" * 90)

print()

print(
    f"Umbral objetivo    : "
    f"{UMBRAL_COBERTURA:.2f}%"
)

print(
    f"Umbral predictoras : "
    f"{UMBRAL_COBERTURA_PREDICTOR:.2f}%"
)

print()

print(
    "Predictoras excluidas por cobertura:"
)

if predictoras_excluidas_cobertura:

    for variable in predictoras_excluidas_cobertura:

        print(
            f"- {variable}"
        )

else:

    print(
        "- Ninguna"
    )

print()

display(
    cobertura
)

==========================================================================================
DECISIÓN DEL FRAMEWORK
==========================================================================================

Umbral objetivo    : 50.00%
Umbral predictoras : 100.00%

Predictoras excluidas por cobertura:
- Ninguna

                                                                                             Variable  % Cobertura Nivel_Cobertura         Decision
ONI                                                                                               ONI       100.00       Excelente         Utilizar
PORCENTAJE DE LA POBLACION CON ACCESO A METODOS...  PORCENTAJE DE LA POBLACION CON ACCESO A METODO...       100.00       Excelente         Utilizar
Precipitacion_mm                                                                     Precipitacion_mm       100.00       Excelente         Utilizar
Radiacion_Solar                                                                       Radiacion_Solar       100.00       Excelente         Utilizar
irca                                                                                             irca       100.00       Excelente         Utilizar
Humedad_Relativa                                                                     Humedad_Relativa       100.00       Excelente         Utilizar
Temp_Min_C                                                                                 Temp_Min_C       100.00       Excelente         Utilizar
Mes                                                                                               Mes       100.00       Excelente         Utilizar
Velocidad_Viento                                                                     Velocidad_Viento       100.00       Excelente         Utilizar
VolumenUtilDiarioMasa                                                           VolumenUtilDiarioMasa        63.64       Aceptable  Objetivo modelo

In [35]:
#==========================================================================================
# VALIDACIÓN DE LA VARIABLE OBJETIVO DEL MODELO
#==========================================================================================

fila_objetivo_modelo = cobertura.loc[
    cobertura["Variable"] == VARIABLE_OBJETIVO_MODELO
]

if fila_objetivo_modelo.empty:

    raise Exception(
        f"La variable objetivo del modelo "
        f"'{VARIABLE_OBJETIVO_MODELO}' no está disponible "
        f"en la tabla de cobertura."
    )

cobertura_objetivo_modelo = (
    fila_objetivo_modelo["% Cobertura"].iloc[0]
)

print()

print("=" * 90)
print("VALIDACIÓN DE LA VARIABLE OBJETIVO DEL MODELO")
print("=" * 90)

print()

print(
    f"Objetivo científico : {VARIABLE_OBJETIVO}"
)

print(
    f"Objetivo del modelo : {VARIABLE_OBJETIVO_MODELO}"
)

print(
    f"Cobertura modelo    : {cobertura_objetivo_modelo:.2f}%"
)

print(
    f"Umbral mínimo       : {UMBRAL_COBERTURA:.2f}%"
)

if cobertura_objetivo_modelo >= UMBRAL_COBERTURA:

    print()
    print("Resultado            : EXPERIMENTO VIABLE")

else:

    raise Exception(
        f"El experimento no es viable. "
        f"La variable objetivo del modelo "
        f"'{VARIABLE_OBJETIVO_MODELO}' "
        f"solo posee una cobertura del "
        f"{cobertura_objetivo_modelo:.2f}%."
    )

==========================================================================================
VALIDACIÓN DE LA VARIABLE OBJETIVO DEL MODELO
==========================================================================================

Objetivo científico : VolumenUtilDiarioMasa
Objetivo del modelo : VolumenUtilDiarioMasa
Cobertura modelo    : 63.64%
Umbral mínimo       : 50.00%

Resultado            : EXPERIMENTO VIABLE

## **M5. Construcción del Dataset Final del Experimento**

In [36]:
#==========================================================================================
# CONSTRUCCIÓN DEL DATASET FINAL DEL EXPERIMENTO
#==========================================================================================

#------------------------------------------------------------------------------------------
# Predictoras aprobadas por el Framework
#------------------------------------------------------------------------------------------

variables_aprobadas = cobertura.loc[
    cobertura["Decision"] == "Utilizar",
    "Variable"
].tolist()

predictoras_utilizadas = [
    variable
    for variable in predictoras
    if variable in variables_aprobadas
]

#------------------------------------------------------------------------------------------
# Dataset efectivo para Machine Learning
#
# Contiene exclusivamente:
# - Predictoras aprobadas
# - Variable objetivo real del modelo
#
# La variable objetivo científica no se incorpora a X.
#------------------------------------------------------------------------------------------

variables_utilizadas = list(
    dict.fromkeys(
        predictoras_utilizadas
        + [VARIABLE_OBJETIVO_MODELO]
    )
)

dataset_ml = dataset_ml[
    variables_utilizadas
].copy()

#------------------------------------------------------------------------------------------
# Controles
#------------------------------------------------------------------------------------------

print()

print("=" * 90)
print("DATASET FINAL DEL EXPERIMENTO")
print("=" * 90)

print()

print(
    f"Observaciones              : {dataset_ml.shape[0]}"
)

print(
    f"Variables                  : {dataset_ml.shape[1]}"
)

print(
    f"Predictoras utilizadas     : {len(predictoras_utilizadas)}"
)

print(
    f"Objetivo científico        : {VARIABLE_OBJETIVO}"
)

print(
    f"Objetivo del modelo        : {VARIABLE_OBJETIVO_MODELO}"
)

print(
    f"Objetivo científico en ML  : {VARIABLE_OBJETIVO in dataset_ml.columns}"
)

print(
    f"Objetivo modelo en ML      : {VARIABLE_OBJETIVO_MODELO in dataset_ml.columns}"
)

print()

print("Variables utilizadas:")

for variable in dataset_ml.columns:
    print("-", variable)

print()

display(
    dataset_ml.head()
)

==========================================================================================
DATASET FINAL DEL EXPERIMENTO
==========================================================================================

Observaciones              : 528
Variables                  : 10
Predictoras utilizadas     : 9
Objetivo científico        : VolumenUtilDiarioMasa
Objetivo del modelo        : VolumenUtilDiarioMasa
Objetivo científico en ML  : True
Objetivo modelo en ML      : True

Variables utilizadas:
- ONI
- PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS
- Precipitacion_mm
- Radiacion_Solar
- irca
- Humedad_Relativa
- Temp_Min_C
- Mes
- Velocidad_Viento
- VolumenUtilDiarioMasa

    ONI  PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS  Precipitacion_mm  Radiacion_Solar  irca  Humedad_Relativa  Temp_Min_C  Mes  Velocidad_Viento  VolumenUtilDiarioMasa
0  0.68                                               99.0                                     2.70            17.78   7.4             77.88        8.45    1              1.37                    NaN
1  0.57                                               99.0                                     2.22            17.16   7.4             78.83       13.72    2              1.14                    NaN
2  0.57                                               99.0                                     5.25            16.63   7.4             80.28       13.52    3              1.09                    NaN
3  0.82                                               99.0                                     6.16            16.56   7.4             80.32       12.81    4              1.07                    NaN
4  1.03                                               99.0                                     3.27            16.00   7.4             79.57       12.24    5              1.14                    NaN

## **M6. Transformación Automática del Dataset del Experimento**

In [37]:
#==========================================================================================
# SEPARACIÓN DE VARIABLES PREDICTORAS Y OBJETIVO
#==========================================================================================

#------------------------------------------------------------------------------------------
# Matriz predictora
#------------------------------------------------------------------------------------------

X = dataset_ml.drop(
    columns=[VARIABLE_OBJETIVO_MODELO]
).copy()

#------------------------------------------------------------------------------------------
# Variable objetivo real del modelo
#------------------------------------------------------------------------------------------

y = dataset_ml[
    VARIABLE_OBJETIVO_MODELO
].copy()

#------------------------------------------------------------------------------------------
# Controles
#------------------------------------------------------------------------------------------

print()

print("=" * 90)
print("SEPARACIÓN DE VARIABLES PREDICTORAS Y OBJETIVO")
print("=" * 90)

print()

print(
    f"Variables predictoras : {X.shape[1]}"
)

print(
    f"Variable objetivo     : {VARIABLE_OBJETIVO_MODELO}"
)

print(
    f"Observaciones X       : {X.shape[0]}"
)

print(
    f"Observaciones y       : {y.shape[0]}"
)

print(
    f"Tipo actual de y      : {y.dtype}"
)

print()

print("Distribución de y:")

print(
    y.value_counts(
        dropna=False
    )
)

==========================================================================================
SEPARACIÓN DE VARIABLES PREDICTORAS Y OBJETIVO
==========================================================================================

Variables predictoras : 9
Variable objetivo     : VolumenUtilDiarioMasa
Observaciones X       : 528
Observaciones y       : 528
Tipo actual de y      : float64

Distribución de y:
VolumenUtilDiarioMasa
NaN             192
3.753109e+08      4
3.492289e+08      4
3.222146e+08      4
3.082495e+08      4
               ...
4.360144e+08      4
4.204539e+08      4
4.060671e+08      4
4.159532e+08      4
4.252018e+08      4
Name: count, Length: 85, dtype: int64

In [38]:
#==========================================================================================
# CODIFICACIÓN DE LA VARIABLE OBJETIVO DEL MODELO
#==========================================================================================

MAPEO_OBJETIVO = None

if TIPO_PROBLEMA == "Clasificación":

    if VARIABLE_OBJETIVO_MODELO == "nivel_de_riesgo":

        MAPEO_OBJETIVO = {
            "Sin riesgo": 0,
            "Riesgo bajo": 1
        }

        clases_observadas = set(
            y.dropna().unique()
        )

        clases_esperadas = set(
            MAPEO_OBJETIVO.keys()
        )

        clases_no_reconocidas = (
            clases_observadas
            - clases_esperadas
        )

        if clases_no_reconocidas:

            raise Exception(
                "Se encontraron categorías no definidas "
                f"en el mapeo: {clases_no_reconocidas}"
            )

        y_original = y.copy()

        y = (
            y.map(MAPEO_OBJETIVO)
            .astype("int8")
        )

    else:

        raise Exception(
            "No existe un mapeo explícito definido para "
            f"la variable objetivo '{VARIABLE_OBJETIVO_MODELO}'."
        )

else:

    # En regresión el objetivo permanece numérico
    y_original = y.copy()


print()

print("=" * 90)
print("CODIFICACIÓN DE LA VARIABLE OBJETIVO")
print("=" * 90)

print()

print(
    f"Tipo de problema     : {TIPO_PROBLEMA}"
)

print(
    f"Variable objetivo    : {VARIABLE_OBJETIVO_MODELO}"
)

print(
    f"Mapeo aplicado       : {MAPEO_OBJETIVO}"
)

print(
    f"Tipo final de y      : {y.dtype}"
)

print()

print("Distribución final de y:")

print(
    y.value_counts(
        dropna=False
    ).sort_index()
)

==========================================================================================
CODIFICACIÓN DE LA VARIABLE OBJETIVO
==========================================================================================

Tipo de problema     : Regresión
Variable objetivo    : VolumenUtilDiarioMasa
Mapeo aplicado       : None
Tipo final de y      : float64

Distribución final de y:
VolumenUtilDiarioMasa
2.901419e+08      4
2.943357e+08      4
2.947298e+08      4
2.966614e+08      4
3.003818e+08      4
               ...
5.970354e+08      4
5.994538e+08      4
6.144494e+08      4
6.195856e+08      4
NaN             192
Name: count, Length: 85, dtype: int64

In [39]:
#==========================================================================================
# DIAGNÓSTICO ESTADÍSTICO DE VARIABLES PREDICTORAS
#==========================================================================================

import numpy as np
import pandas as pd

#------------------------------------------------------------------------------------------
# 1. ASIMETRÍA
#------------------------------------------------------------------------------------------

asimetria = pd.DataFrame({
    "Variable": X.columns,
    "Asimetria": X.skew().round(3)
}).reset_index(drop=True)

#------------------------------------------------------------------------------------------
# 2. DETECCIÓN DE VALORES ATÍPICOS (IQR)
#------------------------------------------------------------------------------------------

outliers = []

for columna in X.columns:

    # Variables binarias
    if X[columna].nunique() <= 2:

        cantidad = np.nan

    else:

        q1 = X[columna].quantile(0.25)
        q3 = X[columna].quantile(0.75)

        iqr = q3 - q1

        inferior = q1 - 1.5 * iqr
        superior = q3 + 1.5 * iqr

        cantidad = (
            (X[columna] < inferior)
            |
            (X[columna] > superior)
        ).sum()

    outliers.append(
        [
            columna,
            cantidad
        ]
    )

outliers = pd.DataFrame(
    outliers,
    columns=[
        "Variable",
        "Outliers"
    ]
)

#------------------------------------------------------------------------------------------
# 3. RECOMENDACIÓN DE PREPROCESAMIENTO
#------------------------------------------------------------------------------------------

def recomendacion(variable, asimetria):

    if X[variable].nunique() <= 2:

        return "Variable binaria. No requiere transformación."

    if abs(asimetria) < 0.5:

        return "No requiere transformación."

    elif abs(asimetria) < 1:

        return "Evaluar estandarización."

    else:

        return "Considerar escalamiento robusto."


diagnostico = asimetria.merge(
    outliers,
    on="Variable"
)

diagnostico["Recomendacion"] = diagnostico.apply(
    lambda fila: recomendacion(
        fila["Variable"],
        fila["Asimetria"]
    ),
    axis=1
)

#------------------------------------------------------------------------------------------
# CONTROLES
#------------------------------------------------------------------------------------------

print()

print("=" * 90)
print("DIAGNÓSTICO ESTADÍSTICO")
print("=" * 90)

print()

print(
    f"Variables predictoras diagnosticadas : {len(diagnostico)}"
)

print(
    f"Variables esperadas                  : {X.shape[1]}"
)

print(
    f"Objetivo científico incluido         : {VARIABLE_OBJETIVO in diagnostico['Variable'].values}"
)

print(
    f"Objetivo modelo incluido              : {VARIABLE_OBJETIVO_MODELO in diagnostico['Variable'].values}"
)

print()

display(diagnostico)

==========================================================================================
DIAGNÓSTICO ESTADÍSTICO
==========================================================================================

Variables predictoras diagnosticadas : 9
Variables esperadas                  : 9
Objetivo científico incluido         : False
Objetivo modelo incluido              : False

                                            Variable  Asimetria  Outliers                     Recomendacion
0                                                ONI      0.891        12          Evaluar estandarización.
1  PORCENTAJE DE LA POBLACION CON ACCESO A METODO...     -3.296        36  Considerar escalamiento robusto.
2                                   Precipitacion_mm      0.657         7          Evaluar estandarización.
3                                    Radiacion_Solar      0.436        16       No requiere transformación.
4                                               irca      1.018        12  Considerar escalamiento robusto.
5                                   Humedad_Relativa     -1.056         6  Considerar escalamiento robusto.
6                                         Temp_Min_C     -0.216         0       No requiere transformación.
7                                                Mes      0.000         0       No requiere transformación.
8                                   Velocidad_Viento      0.680         5          Evaluar estandarización.

In [40]:
#==========================================================================================
# SELECCIÓN AUTOMÁTICA DEL MÉTODO DE TRANSFORMACIÓN
#==========================================================================================

variables_asimetricas = diagnostico.loc[
    diagnostico["Asimetria"].abs() > 1
].shape[0]

variables_outliers = diagnostico.loc[
    diagnostico["Outliers"] > 10
].shape[0]

if (
    variables_asimetricas >= 2
    or
    variables_outliers >= 2
):

    metodo_transformacion = "RobustScaler"

else:

    metodo_transformacion = "StandardScaler"

print()

print("="*90)
print("DECISIÓN DEL FRAMEWORK")
print("="*90)

print()

print(f"Variables muy asimétricas : {variables_asimetricas}")
print(f"Variables con outliers    : {variables_outliers}")

print()

print(f"Método seleccionado : {metodo_transformacion}")

==========================================================================================
DECISIÓN DEL FRAMEWORK
==========================================================================================

Variables muy asimétricas : 3
Variables con outliers    : 4

Método seleccionado : RobustScaler

In [41]:
#==========================================================================================
# PREPARACIÓN AUTOMÁTICA DEL MÉTODO DE TRANSFORMACIÓN
# AJUSTE DIFERIDO A C14 PARA EVITAR FUGA DE INFORMACIÓN
#==========================================================================================

import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler

#------------------------------------------------------------------------------------------
# Matriz predictora
#------------------------------------------------------------------------------------------

X = dataset_ml.drop(
    columns=[VARIABLE_OBJETIVO_MODELO]
).copy()

#------------------------------------------------------------------------------------------
# Selección automática de la clase de escalador
#
# IMPORTANTE:
# El scaler NO se ajusta en C13.
# El ajuste se realizará en C14 exclusivamente con el conjunto de entrenamiento.
#------------------------------------------------------------------------------------------

if metodo_transformacion == "StandardScaler":

    clase_scaler = StandardScaler

elif metodo_transformacion == "RobustScaler":

    clase_scaler = RobustScaler

else:

    raise ValueError(
        f"Método de transformación no reconocido: {metodo_transformacion}"
    )

#------------------------------------------------------------------------------------------
# Dataset predictor preparado
#
# Se conserva sin escalar para construir posteriormente las secuencias temporales.
# El nombre X_transformado se mantiene por compatibilidad con las celdas posteriores.
#------------------------------------------------------------------------------------------

X_transformado = X.copy()

scaler = None

TRANSFORMACION_APLICADA = False
AJUSTE_SCALER_EN = "C14 - conjunto de entrenamiento"

#------------------------------------------------------------------------------------------
# Controles
#------------------------------------------------------------------------------------------

print()

print("=" * 90)
print("PREPARACIÓN DE LA TRANSFORMACIÓN")
print("=" * 90)

print()

print(
    f"Método seleccionado      : {metodo_transformacion}"
)

print(
    f"Transformación aplicada  : {TRANSFORMACION_APLICADA}"
)

print(
    f"Ajuste del scaler en      : {AJUSTE_SCALER_EN}"
)

print(
    f"Predictoras originales    : {X.shape}"
)

print(
    f"Predictoras preparadas     : {X_transformado.shape}"
)

print(
    f"Variable objetivo         : {VARIABLE_OBJETIVO_MODELO}"
)

print(
    f"Tipo de y                 : {y.dtype}"
)

print(
    f"Valores únicos de y       : {sorted(y.dropna().unique().tolist())}"
)

print()

display(
    X_transformado.head()
)

==========================================================================================
PREPARACIÓN DE LA TRANSFORMACIÓN
==========================================================================================

Método seleccionado      : RobustScaler
Transformación aplicada  : False
Ajuste del scaler en      : C14 - conjunto de entrenamiento
Predictoras originales    : (528, 9)
Predictoras preparadas     : (528, 9)
Variable objetivo         : VolumenUtilDiarioMasa
Tipo de y                 : float64
Valores únicos de y       : [290141870.9677419, 294335733.3333333, 294729838.7096774, 296661366.6666667, 300381750.0, 300844166.6666667, 307606161.2903226, 308249466.6666667, 314703548.3870968, 318710096.7741935, 318859483.8709677, 321075166.6666667, 321782800.0, 321908612.9032258, 322214612.9032258, 323125516.1290323, 328335333.3333333, 333583677.4193549, 336433612.9032258, 341265620.6896552, 349228892.8571429, 359512233.3333333, 365105645.1612903, 366243806.4516129, 375310870.9677419, 381478322.5806451, 385040666.6666667, 390054870.9677419, 392567870.9677419, 393645387.0967742, 399258666.6666667, 404057525.22251344, 406067148.63389605, 408355533.3333333, 410084325.54677624, 415953221.1842923, 419985419.3548387, 420179937.2385342, 420453907.316438, 425201780.0626455, 431375571.8475586, 431913246.9590105, 432436285.7142857, 434575580.6451613, 436014398.6951263, 453196074.1935484, 453861348.6660087, 454864354.8387097, 456232800.0, 461579258.0645161, 467863193.5483871, 470190161.2903226, 474543580.6451613, 474841700.0, 478472875.0, 481237600.0, 481637366.6666667, 486531533.3333333, 486848766.6666667, 492346387.0967742, 498158200.0, 499495096.7741935, 500117677.4193549, 504866451.6129032, 525531655.1724138, 532957096.7741935, 540964821.4285715, 544803032.2580645, 545696451.6129032, 549053833.3333334, 550557806.451613, 554029645.1612903, 555273322.5806452, 556572100.0, 558005533.3333334, 563669580.6451613, 564248741.9354838, 577965033.3333334, 580021806.451613, 594481666.6666666, 597035354.8387097, 599453806.451613, 614449366.6666666, 619585580.6451613]

    ONI  PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS  Precipitacion_mm  Radiacion_Solar  irca  Humedad_Relativa  Temp_Min_C  Mes  Velocidad_Viento
0  0.68                                               99.0                                     2.70            17.78   7.4             77.88        8.45    1              1.37
1  0.57                                               99.0                                     2.22            17.16   7.4             78.83       13.72    2              1.14
2  0.57                                               99.0                                     5.25            16.63   7.4             80.28       13.52    3              1.09
3  0.82                                               99.0                                     6.16            16.56   7.4             80.32       12.81    4              1.07
4  1.03                                               99.0                                     3.27            16.00   7.4             79.57       12.24    5              1.14

In [42]:
#==========================================================================================
# RECONSTRUCCIÓN DEL DATASET PREPARADO
# SIN ESCALAMIENTO + METADATOS TEMPORALES
#==========================================================================================

import pandas as pd

#------------------------------------------------------------------------------------------
# Dataset destinado al modelado
#
# Conserva:
# - Predictoras sin escalar
# - Objetivo real del modelo ya preparado
#
# El nombre dataset_transformado se mantiene por compatibilidad
# con las etapas posteriores del Framework.
#------------------------------------------------------------------------------------------

dataset_transformado = X_transformado.copy()

dataset_transformado[
    VARIABLE_OBJETIVO_MODELO
] = y.values

#------------------------------------------------------------------------------------------
# Metadatos temporales
#
# Nodo y Fecha NO son predictoras.
# Se conservan únicamente para construir secuencias dentro de cada nodo.
#------------------------------------------------------------------------------------------

columnas_temporales = [
    columna
    for columna in ["Nodo", "Fecha"]
    if columna in dataset.columns
]

if len(columnas_temporales) != 2:

    raise Exception(
        "El Dataset Maestro debe contener las columnas "
        "'Nodo' y 'Fecha' para construir secuencias temporales."
    )

metadata_temporal = dataset.loc[
    dataset_transformado.index,
    columnas_temporales
].copy()

metadata_temporal["Fecha"] = pd.to_datetime(
    metadata_temporal["Fecha"]
)

#------------------------------------------------------------------------------------------
# Validación de alineación
#------------------------------------------------------------------------------------------

if len(metadata_temporal) != len(dataset_transformado):

    raise Exception(
        "Los metadatos temporales no están alineados "
        "con el dataset preparado."
    )

#------------------------------------------------------------------------------------------
# Controles
#------------------------------------------------------------------------------------------

print()

print("=" * 90)
print("DATASET PREPARADO PARA SECUENCIAS")
print("=" * 90)

print()

print(
    f"Observaciones         : {dataset_transformado.shape[0]}"
)

print(
    f"Variables             : {dataset_transformado.shape[1]}"
)

print(
    f"Predictoras           : {X_transformado.shape[1]}"
)

print(
    f"Objetivo del modelo   : {VARIABLE_OBJETIVO_MODELO}"
)

print(
    f"Objetivo modelo existe: {VARIABLE_OBJETIVO_MODELO in dataset_transformado.columns}"
)

print(
    f"Objetivo científico X : {VARIABLE_OBJETIVO in X_transformado.columns}"
)

print(
    f"Metadatos temporales  : {columnas_temporales}"
)

print(
    f"Nodos                 : {metadata_temporal['Nodo'].nunique()}"
)

print(
    f"Fechas válidas        : {metadata_temporal['Fecha'].notna().sum()}"
)

print()

display(
    dataset_transformado.head()
)

==========================================================================================
DATASET PREPARADO PARA SECUENCIAS
==========================================================================================

Observaciones         : 528
Variables             : 10
Predictoras           : 9
Objetivo del modelo   : VolumenUtilDiarioMasa
Objetivo modelo existe: True
Objetivo científico X : False
Metadatos temporales  : ['Nodo', 'Fecha']
Nodos                 : 4
Fechas válidas        : 528

    ONI  PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS  Precipitacion_mm  Radiacion_Solar  irca  Humedad_Relativa  Temp_Min_C  Mes  Velocidad_Viento  VolumenUtilDiarioMasa
0  0.68                                               99.0                                     2.70            17.78   7.4             77.88        8.45    1              1.37                    NaN
1  0.57                                               99.0                                     2.22            17.16   7.4             78.83       13.72    2              1.14                    NaN
2  0.57                                               99.0                                     5.25            16.63   7.4             80.28       13.52    3              1.09                    NaN
3  0.82                                               99.0                                     6.16            16.56   7.4             80.32       12.81    4              1.07                    NaN
4  1.03                                               99.0                                     3.27            16.00   7.4             79.57       12.24    5              1.14                    NaN

In [43]:
#==========================================================================================
# EXPORTACIÓN DEL DATASET PREPARADO Y METADATOS TEMPORALES
#==========================================================================================

#------------------------------------------------------------------------------------------
# Dataset preparado para secuencias
#
# Se conserva el nombre histórico "transformado" por compatibilidad,
# aunque el escalamiento se realizará posteriormente en C14.
#------------------------------------------------------------------------------------------

dataset_transformado.to_parquet(
    "dataset_machine_learning_transformado.parquet",
    index=False
)

dataset_transformado.to_csv(
    "dataset_machine_learning_transformado.csv",
    index=False,
    encoding="utf-8-sig"
)

#------------------------------------------------------------------------------------------
# Metadatos temporales necesarios para construir secuencias por Nodo
#------------------------------------------------------------------------------------------

metadata_temporal.to_parquet(
    "metadata_temporal.parquet",
    index=False
)

metadata_temporal.to_csv(
    "metadata_temporal.csv",
    index=False,
    encoding="utf-8-sig"
)

print()

print("=" * 90)
print("EXPORTACIÓN")
print("=" * 90)

print()

print("Archivos generados:")

print("- dataset_machine_learning_transformado.parquet")
print("- dataset_machine_learning_transformado.csv")
print("- metadata_temporal.parquet")
print("- metadata_temporal.csv")

print()

print(
    f"Filas dataset          : {len(dataset_transformado)}"
)

print(
    f"Filas metadata temporal: {len(metadata_temporal)}"
)

==========================================================================================
EXPORTACIÓN
==========================================================================================

Archivos generados:
- dataset_machine_learning_transformado.parquet
- dataset_machine_learning_transformado.csv
- metadata_temporal.parquet
- metadata_temporal.csv

Filas dataset          : 528
Filas metadata temporal: 528

In [44]:
#==========================================================================================
# CONTROL DE TRANSFORMACIÓN
# EL SCALER SE AJUSTARÁ EXCLUSIVAMENTE EN C14
#==========================================================================================

import os

CARPETA_TRANSFORMACION = f"transformaciones/{EXPERIMENTO}"

os.makedirs(
    CARPETA_TRANSFORMACION,
    exist_ok=True
)

RUTA_SCALER = None
SCALER_AJUSTADO_EN_C13 = False

print()

print("=" * 90)
print("CONTROL DEL SCALER")
print("=" * 90)

print()

print(
    f"Método seleccionado     : {metodo_transformacion}"
)

print(
    f"Scaler ajustado en C13   : {SCALER_AJUSTADO_EN_C13}"
)

print(
    "Ajuste definitivo        : C14 - exclusivamente con entrenamiento"
)

print(
    "Archivo scaler.pkl       : NO generado en C13"
)

==========================================================================================
CONTROL DEL SCALER
==========================================================================================

Método seleccionado     : RobustScaler
Scaler ajustado en C13   : False
Ajuste definitivo        : C14 - exclusivamente con entrenamiento
Archivo scaler.pkl       : NO generado en C13

## **M7. Construcción de Secuencias Temporales**

In [45]:
#==========================================================================================
# CARGA DEL DATASET PREPARADO Y METADATOS TEMPORALES
#==========================================================================================

import pandas as pd

RUTA_DATASET = "dataset_machine_learning_transformado.parquet"
RUTA_METADATA = "metadata_temporal.parquet"

dataset_transformado = pd.read_parquet(
    RUTA_DATASET
)

metadata_temporal = pd.read_parquet(
    RUTA_METADATA
)

metadata_temporal["Fecha"] = pd.to_datetime(
    metadata_temporal["Fecha"]
)

if len(dataset_transformado) != len(metadata_temporal):

    raise Exception(
        "El dataset preparado y los metadatos temporales "
        "no tienen el mismo número de observaciones."
    )

print()

print("=" * 90)
print("DATOS PARA CONSTRUCCIÓN DE SECUENCIAS")
print("=" * 90)

print()

print(
    f"Observaciones dataset  : {len(dataset_transformado)}"
)

print(
    f"Variables dataset      : {dataset_transformado.shape[1]}"
)

print(
    f"Observaciones metadata : {len(metadata_temporal)}"
)

print(
    f"Nodos                  : {metadata_temporal['Nodo'].nunique()}"
)

print(
    f"Fechas válidas         : {metadata_temporal['Fecha'].notna().sum()}"
)

print()

display(
    metadata_temporal.head()
)

==========================================================================================
DATOS PARA CONSTRUCCIÓN DE SECUENCIAS
==========================================================================================

Observaciones dataset  : 528
Variables dataset      : 10
Observaciones metadata : 528
Nodos                  : 4
Fechas válidas         : 528

            Nodo      Fecha
0  Bogota_Sabana 2015-01-01
1  Bogota_Sabana 2015-02-01
2  Bogota_Sabana 2015-03-01
3  Bogota_Sabana 2015-04-01
4  Bogota_Sabana 2015-05-01

In [46]:
#==========================================================================================
# CONFIGURACIÓN TEMPORAL
#==========================================================================================

# Recuperar parámetros temporales del experimento activo
VENTANA = int(
    configuracion["Ventana"]
)

HORIZONTE = int(
    configuracion["Horizonte"]
)

print()

print("=" * 90)
print("CONFIGURACIÓN TEMPORAL")
print("=" * 90)

print()

print(f"Experimento : {EXPERIMENTO}")
print(f"Ventana     : {VENTANA}")
print(f"Horizonte   : {HORIZONTE}")

==========================================================================================
CONFIGURACIÓN TEMPORAL
==========================================================================================

Experimento : Exp04
Ventana     : 12
Horizonte   : 1

In [47]:
#==========================================================================================
# VALIDACIÓN DE NULOS Y ESTRUCTURA TEMPORAL ANTES DE CONSTRUIR SECUENCIAS
#==========================================================================================

import pandas as pd

#------------------------------------------------------------------------------------------
# Matriz predictora efectiva
#------------------------------------------------------------------------------------------

X_validacion = dataset_transformado.drop(
    columns=[VARIABLE_OBJETIVO_MODELO]
).copy()

#------------------------------------------------------------------------------------------
# Dataset auxiliar con Nodo y Fecha
#------------------------------------------------------------------------------------------

datos_validacion = pd.concat(
    [
        metadata_temporal[["Nodo", "Fecha"]].reset_index(drop=True),
        X_validacion.reset_index(drop=True)
    ],
    axis=1
)

datos_validacion["Fecha"] = pd.to_datetime(
    datos_validacion["Fecha"]
)

#------------------------------------------------------------------------------------------
# Nulos generales
#------------------------------------------------------------------------------------------

total_nulos_X = int(
    X_validacion.isna().sum().sum()
)

#------------------------------------------------------------------------------------------
# Validación por Nodo
#------------------------------------------------------------------------------------------

resumen_nodos = []

ventanas_potenciales = 0
ventanas_con_nulos = 0

for nodo, grupo in datos_validacion.groupby(
    "Nodo",
    sort=False
):

    grupo = grupo.sort_values(
        "Fecha"
    ).reset_index(drop=True)

    X_nodo = grupo[
        X_validacion.columns
    ]

    potenciales_nodo = (
        len(grupo)
        - VENTANA
        - HORIZONTE
        + 1
    )

    potenciales_nodo = max(
        0,
        potenciales_nodo
    )

    nulas_nodo = 0

    for i in range(
        potenciales_nodo
    ):

        ventana = X_nodo.iloc[
            i:i + VENTANA
        ]

        if ventana.isna().any().any():

            nulas_nodo += 1

    ventanas_potenciales += potenciales_nodo
    ventanas_con_nulos += nulas_nodo

    resumen_nodos.append(
        {
            "Nodo": nodo,
            "Observaciones": len(grupo),
            "Ventanas_Potenciales": potenciales_nodo,
            "Ventanas_con_NaN": nulas_nodo
        }
    )

resumen_nodos = pd.DataFrame(
    resumen_nodos
)

#------------------------------------------------------------------------------------------
# Controles
#------------------------------------------------------------------------------------------

print()

print("=" * 90)
print("VALIDACIÓN TEMPORAL Y DE NULOS")
print("=" * 90)

print()

print("Nulos por variable:")
print(
    X_validacion.isna().sum()
)

print()

print(
    f"Total de nulos en X       : {total_nulos_X}"
)

print(
    f"Nodos                     : {metadata_temporal['Nodo'].nunique()}"
)

print(
    f"Ventanas potenciales      : {ventanas_potenciales}"
)

print(
    f"Ventanas con algún NaN    : {ventanas_con_nulos}"
)

print(
    f"Objetivo excluido de X    : {VARIABLE_OBJETIVO_MODELO not in X_validacion.columns}"
)

print(
    f"Predictoras en validación : {X_validacion.shape[1]}"
)

print()

display(
    resumen_nodos
)

==========================================================================================
VALIDACIÓN TEMPORAL Y DE NULOS
==========================================================================================

Nulos por variable:
ONI                                                                         0
PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS    0
Precipitacion_mm                                                            0
Radiacion_Solar                                                             0
irca                                                                        0
Humedad_Relativa                                                            0
Temp_Min_C                                                                  0
Mes                                                                         0
Velocidad_Viento                                                            0
dtype: int64

Total de nulos en X       : 0
Nodos                     : 4
Ventanas potenciales      : 480
Ventanas con algún NaN    : 0
Objetivo excluido de X    : True
Predictoras en validación : 9

               Nodo  Observaciones  Ventanas_Potenciales  Ventanas_con_NaN
0     Bogota_Sabana            132                   120                 0
1          Sopo_Sur            132                   120                 0
2   Tocancipa_Media            132                   120                 0
3  Villapinzon_Alta            132                   120                 0

In [48]:
#==========================================================================================
# CONSTRUCCIÓN DE SECUENCIAS TEMPORALES POR NODO
#==========================================================================================

import numpy as np
import pandas as pd

#------------------------------------------------------------------------------------------
# Variables predictoras y objetivo
#------------------------------------------------------------------------------------------

X = dataset_transformado.drop(
    columns=[VARIABLE_OBJETIVO_MODELO]
).copy()

y = dataset_transformado[
    VARIABLE_OBJETIVO_MODELO
].copy()

variables_predictoras_secuencia = X.columns.tolist()

#------------------------------------------------------------------------------------------
# Integración temporal
#
# Nodo y Fecha se utilizan exclusivamente para ordenar y agrupar.
# NO forman parte de las variables predictoras.
#------------------------------------------------------------------------------------------

datos_secuencias = pd.concat(
    [
        metadata_temporal[
            ["Nodo", "Fecha"]
        ].reset_index(drop=True),

        dataset_transformado.reset_index(drop=True)
    ],
    axis=1
)

datos_secuencias["Fecha"] = pd.to_datetime(
    datos_secuencias["Fecha"]
)

#------------------------------------------------------------------------------------------
# Contenedores
#------------------------------------------------------------------------------------------

secuencias_X = []
secuencias_y = []

metadata_secuencias_detalle = []

secuencias_potenciales = 0
secuencias_omitidas = 0

resumen_por_nodo = []

#------------------------------------------------------------------------------------------
# Construcción independiente por Nodo
#------------------------------------------------------------------------------------------

for nodo, grupo in datos_secuencias.groupby(
    "Nodo",
    sort=False
):

    grupo = grupo.sort_values(
        "Fecha"
    ).reset_index(drop=True)

    X_nodo = grupo[
        variables_predictoras_secuencia
    ]

    y_nodo = grupo[
        VARIABLE_OBJETIVO_MODELO
    ]

    potenciales_nodo = (
        len(grupo)
        - VENTANA
        - HORIZONTE
        + 1
    )

    potenciales_nodo = max(
        0,
        potenciales_nodo
    )

    validas_nodo = 0
    omitidas_nodo = 0

    secuencias_potenciales += potenciales_nodo

    for i in range(
        potenciales_nodo
    ):

        indice_objetivo = (
            i
            + VENTANA
            + HORIZONTE
            - 1
        )

        ventana_X = X_nodo.iloc[
            i:i + VENTANA
        ]

        objetivo = y_nodo.iloc[
            indice_objetivo
        ]

        #----------------------------------------------------------------------
        # Omitir únicamente secuencias incompletas
        #----------------------------------------------------------------------

        if (
            ventana_X.isna().any().any()
            or
            pd.isna(objetivo)
        ):

            secuencias_omitidas += 1
            omitidas_nodo += 1

            continue

        secuencias_X.append(
            ventana_X.to_numpy()
        )

        secuencias_y.append(
            objetivo
        )

        metadata_secuencias_detalle.append(
            {
                "Nodo": nodo,
                "Fecha_Inicio": grupo.loc[
                    i,
                    "Fecha"
                ],
                "Fecha_Fin": grupo.loc[
                    i + VENTANA - 1,
                    "Fecha"
                ],
                "Fecha_Objetivo": grupo.loc[
                    indice_objetivo,
                    "Fecha"
                ]
            }
        )

        validas_nodo += 1

    resumen_por_nodo.append(
        {
            "Nodo": nodo,
            "Observaciones": len(grupo),
            "Secuencias_Potenciales": potenciales_nodo,
            "Secuencias_Omitidas": omitidas_nodo,
            "Secuencias_Validas": validas_nodo
        }
    )

#------------------------------------------------------------------------------------------
# Metadatos de las secuencias
#------------------------------------------------------------------------------------------

metadata_secuencias_detalle = pd.DataFrame(
    metadata_secuencias_detalle
)

resumen_por_nodo = pd.DataFrame(
    resumen_por_nodo
)

#------------------------------------------------------------------------------------------
# Controles
#------------------------------------------------------------------------------------------

print()

print("=" * 90)
print("SECUENCIAS TEMPORALES POR NODO")
print("=" * 90)

print()

print(
    f"Variable objetivo       : {VARIABLE_OBJETIVO_MODELO}"
)

print(
    f"Variables predictoras   : {X.shape[1]}"
)

print(
    f"Nodos procesados        : {resumen_por_nodo.shape[0]}"
)

print(
    f"Secuencias potenciales  : {secuencias_potenciales}"
)

print(
    f"Secuencias omitidas     : {secuencias_omitidas}"
)

print(
    f"Secuencias válidas      : {len(secuencias_X)}"
)

print()

print("Distribución del objetivo:")

print(
    pd.Series(
        secuencias_y,
        name=VARIABLE_OBJETIVO_MODELO
    ).value_counts().sort_index()
)

print()

display(
    resumen_por_nodo
)

==========================================================================================
SECUENCIAS TEMPORALES POR NODO
==========================================================================================

Variable objetivo       : VolumenUtilDiarioMasa
Variables predictoras   : 9
Nodos procesados        : 4
Secuencias potenciales  : 480
Secuencias omitidas     : 144
Secuencias válidas      : 336

Distribución del objetivo:
VolumenUtilDiarioMasa
2.901419e+08    4
2.943357e+08    4
2.947298e+08    4
2.966614e+08    4
3.003818e+08    4
               ..
5.944817e+08    4
5.970354e+08    4
5.994538e+08    4
6.144494e+08    4
6.195856e+08    4
Name: count, Length: 84, dtype: int64

               Nodo  Observaciones  Secuencias_Potenciales  Secuencias_Omitidas  Secuencias_Validas
0     Bogota_Sabana            132                     120                   36                  84
1          Sopo_Sur            132                     120                   36                  84
2   Tocancipa_Media            132                     120                   36                  84
3  Villapinzon_Alta            132                     120                   36                  84

In [49]:
#==========================================================================================
# RESUMEN DE LAS SECUENCIAS
#==========================================================================================

print()

print("=" * 90)
print("RESUMEN")
print("=" * 90)

print()

print(
    f"Longitud de cada secuencia : {VENTANA}"
)

print(
    f"Variables predictoras      : {X.shape[1]}"
)

print(
    f"Total de secuencias        : {len(secuencias_X)}"
)

==========================================================================================
RESUMEN
==========================================================================================

Longitud de cada secuencia : 12
Variables predictoras      : 9
Total de secuencias        : 336

In [50]:
#==========================================================================================
# PRIMERA SECUENCIA
#==========================================================================================

primera = pd.DataFrame(
    secuencias_X[0],
    columns=X.columns
)

print()

print("="*90)
print("PRIMERA SECUENCIA")
print("="*90)

print()

display(primera)

print()

print("Valor objetivo")

print(
    secuencias_y[0]
)

==========================================================================================
PRIMERA SECUENCIA
==========================================================================================

     ONI  PORCENTAJE DE LA POBLACION CON ACCESO A METODOS DE SANEAMIENTO ADECUADOS  Precipitacion_mm  Radiacion_Solar  irca  Humedad_Relativa  Temp_Min_C   Mes  Velocidad_Viento
0  -0.81                                               99.0                                     2.47            17.15   6.3             81.21       11.55   1.0              0.91
1  -0.63                                               99.0                                     2.39            16.61   6.3             80.65       11.68   2.0              1.12
2  -0.70                                               99.0                                     3.51            17.19   6.3             79.16       12.83   3.0              1.09
3  -0.39                                               99.0                                     9.22            15.46   6.3             84.90       13.10   4.0              0.95
4  -0.09                                               99.0                                     9.83            15.78   6.3             83.64       12.53   5.0              0.85
5   0.10                                               99.0                                     6.50            16.29   6.3             80.20       11.74   6.0              1.28
6   0.17                                               99.0                                     5.75            16.33   6.3             79.30       12.22   7.0              1.35
7   0.14                                               99.0                                     4.73            18.23   6.3             77.65        9.89   8.0              1.77
8   0.51                                               99.0                                     4.47            18.10   6.3             77.27       11.98   9.0              1.24
9   0.95                                               99.0                                     6.77            17.59   6.3             83.56       13.06  10.0              0.89
10  0.96                                               99.0                                     5.62            16.25   6.3             84.64       13.63  11.0              0.80
11  0.99                                               99.0                                     1.11            18.79   6.3             78.49       10.99  12.0              1.17

Valor objetivo
375310870.9677419

In [51]:
#==========================================================================================
# EXPORTACIÓN DE LAS SECUENCIAS TEMPORALES
#==========================================================================================

import pandas as pd
import numpy as np

#------------------------------------------------------------------------------------------
# Recuperar configuración activa
#------------------------------------------------------------------------------------------

TIPO_PROBLEMA = configuracion["Tipo_Problema"]
MODELO = configuracion["Modelo"]

#------------------------------------------------------------------------------------------
# Conversión a arreglos NumPy
#------------------------------------------------------------------------------------------

X_array = np.asarray(
    secuencias_X
)

y_array = np.asarray(
    secuencias_y
)

#------------------------------------------------------------------------------------------
# Validación de correspondencia
#------------------------------------------------------------------------------------------

if not (
    len(X_array)
    == len(y_array)
    == len(metadata_secuencias_detalle)
):

    raise Exception(
        "X, y y los metadatos de secuencia "
        "no tienen el mismo número de registros."
    )

#------------------------------------------------------------------------------------------
# Identificador explícito de cada secuencia
#------------------------------------------------------------------------------------------

metadata_secuencias_detalle = (
    metadata_secuencias_detalle
    .reset_index(drop=True)
    .copy()
)

metadata_secuencias_detalle.insert(
    0,
    "Indice_Secuencia",
    np.arange(
        len(metadata_secuencias_detalle)
    )
)

#------------------------------------------------------------------------------------------
# Exportación de arreglos
#------------------------------------------------------------------------------------------

np.save(
    "secuencias_X.npy",
    X_array
)

np.save(
    "secuencias_y.npy",
    y_array
)

#------------------------------------------------------------------------------------------
# Metadata general del experimento
#------------------------------------------------------------------------------------------

metadata = pd.DataFrame({

    "Parametro": [

        "Experimento",
        "Dominio",
        "Tipo Problema",
        "Modelo",
        "Variable Objetivo",
        "Variable Objetivo Cientifico",
        "Ventana",
        "Horizonte",
        "Variables Predictoras",
        "Variables Modelo",
        "Numero de Secuencias",
        "Método de Transformación",
        "Transformación Aplicada en C13",
        "Ajuste del Scaler"

    ],

    "Valor": [

        EXPERIMENTO,
        DOMINIO,
        TIPO_PROBLEMA,
        MODELO,

        # y efectiva entregada a C14
        VARIABLE_OBJETIVO_MODELO,

        # Trazabilidad científica
        VARIABLE_OBJETIVO,

        VENTANA,
        HORIZONTE,

        ";".join(
            X.columns
        ),

        X.shape[1],

        len(secuencias_X),

        metodo_transformacion,

        False,

        "C14 - conjunto de entrenamiento"

    ]

})

metadata.to_csv(
    "metadata_secuencias.csv",
    index=False,
    encoding="utf-8-sig"
)

#------------------------------------------------------------------------------------------
# Metadata individual de cada secuencia
#------------------------------------------------------------------------------------------

metadata_secuencias_detalle.to_csv(
    "metadata_secuencias_detalle.csv",
    index=False,
    encoding="utf-8-sig"
)

metadata_secuencias_detalle.to_parquet(
    "metadata_secuencias_detalle.parquet",
    index=False
)

#------------------------------------------------------------------------------------------
# Controles
#------------------------------------------------------------------------------------------

print()

print("=" * 90)
print("EXPORTACIÓN")
print("=" * 90)

print()

print("Archivos generados:")
print("- secuencias_X.npy")
print("- secuencias_y.npy")
print("- metadata_secuencias.csv")
print("- metadata_secuencias_detalle.csv")
print("- metadata_secuencias_detalle.parquet")

print()

print(
    f"Shape X exportado       : {X_array.shape}"
)

print(
    f"Shape y exportado       : {y_array.shape}"
)

print(
    f"Metadata por secuencia  : {metadata_secuencias_detalle.shape}"
)

print(
    f"Tipo y exportado        : {y_array.dtype}"
)

print(
    f"Valores únicos de y     : {np.unique(y_array).tolist()}"
)

print(
    f"Objetivo operativo      : {VARIABLE_OBJETIVO_MODELO}"
)

print(
    f"Objetivo científico     : {VARIABLE_OBJETIVO}"
)

print(
    f"Escalamiento en C13     : False"
)

print()

display(
    metadata_secuencias_detalle.head()
)

==========================================================================================
EXPORTACIÓN
==========================================================================================

Archivos generados:
- secuencias_X.npy
- secuencias_y.npy
- metadata_secuencias.csv
- metadata_secuencias_detalle.csv
- metadata_secuencias_detalle.parquet

Shape X exportado       : (336, 12, 9)
Shape y exportado       : (336,)
Metadata por secuencia  : (336, 5)
Tipo y exportado        : float64
Valores únicos de y     : [290141870.9677419, 294335733.3333333, 294729838.7096774, 296661366.6666667, 300381750.0, 300844166.6666667, 307606161.2903226, 308249466.6666667, 314703548.3870968, 318710096.7741935, 318859483.8709677, 321075166.6666667, 321782800.0, 321908612.9032258, 322214612.9032258, 323125516.1290323, 328335333.3333333, 333583677.4193549, 336433612.9032258, 341265620.6896552, 349228892.8571429, 359512233.3333333, 365105645.1612903, 366243806.4516129, 375310870.9677419, 381478322.5806451, 385040666.6666667, 390054870.9677419, 392567870.9677419, 393645387.0967742, 399258666.6666667, 404057525.22251344, 406067148.63389605, 408355533.3333333, 410084325.54677624, 415953221.1842923, 419985419.3548387, 420179937.2385342, 420453907.316438, 425201780.0626455, 431375571.8475586, 431913246.9590105, 432436285.7142857, 434575580.6451613, 436014398.6951263, 453196074.1935484, 453861348.6660087, 454864354.8387097, 456232800.0, 461579258.0645161, 467863193.5483871, 470190161.2903226, 474543580.6451613, 474841700.0, 478472875.0, 481237600.0, 481637366.6666667, 486531533.3333333, 486848766.6666667, 492346387.0967742, 498158200.0, 499495096.7741935, 500117677.4193549, 504866451.6129032, 525531655.1724138, 532957096.7741935, 540964821.4285715, 544803032.2580645, 545696451.6129032, 549053833.3333334, 550557806.451613, 554029645.1612903, 555273322.5806452, 556572100.0, 558005533.3333334, 563669580.6451613, 564248741.9354838, 577965033.3333334, 580021806.451613, 594481666.6666666, 597035354.8387097, 599453806.451613, 614449366.6666666, 619585580.6451613]
Objetivo operativo      : VolumenUtilDiarioMasa
Objetivo científico     : VolumenUtilDiarioMasa
Escalamiento en C13     : False

   Indice_Secuencia           Nodo Fecha_Inicio  Fecha_Fin Fecha_Objetivo
0                 0  Bogota_Sabana   2018-01-01 2018-12-01     2019-01-01
1                 1  Bogota_Sabana   2018-02-01 2019-01-01     2019-02-01
2                 2  Bogota_Sabana   2018-03-01 2019-02-01     2019-03-01
3                 3  Bogota_Sabana   2018-04-01 2019-03-01     2019-04-01
4                 4  Bogota_Sabana   2018-05-01 2019-04-01     2019-05-01

In [52]:
#==========================================================================================
# DIAGNÓSTICO DE SECUENCIAS POTENCIALES, VÁLIDAS Y OMITIDAS
# RESPETANDO LA ESTRUCTURA POR NODO
#==========================================================================================

import pandas as pd

registros_diagnostico = []

#------------------------------------------------------------------------------------------
# Evaluación independiente por Nodo
#------------------------------------------------------------------------------------------

for nodo, grupo in datos_secuencias.groupby(
    "Nodo",
    sort=False
):

    grupo = grupo.sort_values(
        "Fecha"
    ).reset_index(drop=True)

    X_nodo = grupo[
        variables_predictoras_secuencia
    ]

    y_nodo = grupo[
        VARIABLE_OBJETIVO_MODELO
    ]

    potenciales_nodo = (
        len(grupo)
        - VENTANA
        - HORIZONTE
        + 1
    )

    potenciales_nodo = max(
        0,
        potenciales_nodo
    )

    for i in range(
        potenciales_nodo
    ):

        indice_objetivo = (
            i
            + VENTANA
            + HORIZONTE
            - 1
        )

        ventana_X = X_nodo.iloc[
            i:i + VENTANA
        ]

        objetivo = y_nodo.iloc[
            indice_objetivo
        ]

        ventana_con_nan = (
            ventana_X.isna().any().any()
        )

        objetivo_nan = pd.isna(
            objetivo
        )

        valida = not (
            ventana_con_nan
            or objetivo_nan
        )

        registros_diagnostico.append(
            {
                "Nodo": nodo,
                "Fecha_Inicio": grupo.loc[
                    i,
                    "Fecha"
                ],
                "Fecha_Objetivo": grupo.loc[
                    indice_objetivo,
                    "Fecha"
                ],
                "Objetivo": objetivo,
                "Ventana_con_NaN": ventana_con_nan,
                "Objetivo_NaN": objetivo_nan,
                "Estado": (
                    "Valida"
                    if valida
                    else "Omitida"
                )
            }
        )

#------------------------------------------------------------------------------------------
# Dataset diagnóstico
#------------------------------------------------------------------------------------------

diagnostico_clases = pd.DataFrame(
    registros_diagnostico
)

#------------------------------------------------------------------------------------------
# Controles generales
#------------------------------------------------------------------------------------------

print()

print("=" * 90)
print("DIAGNÓSTICO DE SECUENCIAS")
print("=" * 90)

print()

print(
    f"Secuencias potenciales : {len(diagnostico_clases)}"
)

print(
    f"Secuencias válidas     : {(diagnostico_clases['Estado'] == 'Valida').sum()}"
)

print(
    f"Secuencias omitidas    : {(diagnostico_clases['Estado'] == 'Omitida').sum()}"
)

#------------------------------------------------------------------------------------------
# Diagnóstico específico según tipo de problema
#------------------------------------------------------------------------------------------

if str(TIPO_PROBLEMA).lower().startswith(
    "clas"
):

    print()
    print("Distribución de objetivos potenciales:")

    print(
        diagnostico_clases[
            "Objetivo"
        ].value_counts(
            dropna=False
        ).sort_index()
    )

    print()
    print("Distribución en secuencias VÁLIDAS:")

    print(
        diagnostico_clases.loc[
            diagnostico_clases["Estado"] == "Valida",
            "Objetivo"
        ].value_counts(
            dropna=False
        ).sort_index()
    )

    print()
    print("Cruce clase × estado:")

    print(
        pd.crosstab(
            diagnostico_clases["Objetivo"],
            diagnostico_clases["Estado"],
            margins=True
        )
    )

else:

    print()
    print("Resumen del objetivo en secuencias válidas:")

    print(
        diagnostico_clases.loc[
            diagnostico_clases["Estado"] == "Valida",
            "Objetivo"
        ].describe()
    )

==========================================================================================
DIAGNÓSTICO DE SECUENCIAS
==========================================================================================

Secuencias potenciales : 480
Secuencias válidas     : 336
Secuencias omitidas    : 144

Resumen del objetivo en secuencias válidas:
count    3.360000e+02
mean     4.375035e+08
std      9.357910e+07
min      2.901419e+08
25%      3.569414e+08
50%      4.321748e+08
75%      5.013049e+08
max      6.195856e+08
Name: Objetivo, dtype: float64

In [53]:
#==========================================================================================
# INTEGRIDAD TEMPORAL DE LAS SECUENCIAS
#==========================================================================================

import numpy as np
import pandas as pd

#------------------------------------------------------------------------------------------
# Recalcular cuántas secuencias son realmente esperables por Nodo
#
# Una secuencia será válida solamente cuando:
#
# 1. exista la ventana temporal completa;
# 2. todas las predictoras de la ventana tengan datos;
# 3. exista el valor objetivo en el horizonte correspondiente.
#
# Esto permite trabajar correctamente tanto con:
# - objetivos con cobertura completa, como Exp01;
# - objetivos con cobertura parcial, como Exp04.
#------------------------------------------------------------------------------------------

control_nodos = []

for nodo, grupo in datos_secuencias.groupby(
    "Nodo",
    sort=False
):

    grupo = (
        grupo
        .sort_values("Fecha")
        .reset_index(drop=True)
    )

    observaciones_nodo = len(
        grupo
    )

    secuencias_potenciales = max(
        0,
        observaciones_nodo
        - VENTANA
        - HORIZONTE
        + 1
    )

    secuencias_validas_esperadas = 0

    #--------------------------------------------------------------------------
    # Evaluar cada ventana potencial
    #--------------------------------------------------------------------------

    for i in range(
        secuencias_potenciales
    ):

        indice_objetivo = (
            i
            + VENTANA
            + HORIZONTE
            - 1
        )

        ventana_x = grupo.iloc[
            i:i + VENTANA
        ][
            X.columns
        ]

        objetivo = grupo.iloc[
            indice_objetivo
        ][
            VARIABLE_OBJETIVO_MODELO
        ]

        ventana_valida = (
            not ventana_x
            .isna()
            .any()
            .any()
        )

        objetivo_valido = (
            pd.notna(objetivo)
        )

        if (
            ventana_valida
            and objetivo_valido
        ):

            secuencias_validas_esperadas += 1

    #--------------------------------------------------------------------------
    # Secuencias realmente generadas para el Nodo
    #--------------------------------------------------------------------------

    secuencias_obtenidas = int(
        (
            metadata_secuencias_detalle[
                "Nodo"
            ]
            == nodo
        ).sum()
    )

    control_nodos.append({

        "Nodo":
            nodo,

        "Observaciones":
            observaciones_nodo,

        "Potenciales":
            secuencias_potenciales,

        "Esperadas_Validas":
            secuencias_validas_esperadas,

        "Obtenidas":
            secuencias_obtenidas,

        "Conteo_Correcto":
            (
                secuencias_validas_esperadas
                ==
                secuencias_obtenidas
            )

    })

#------------------------------------------------------------------------------------------
# Tabla de control
#------------------------------------------------------------------------------------------

control_nodos = pd.DataFrame(
    control_nodos
)

#------------------------------------------------------------------------------------------
# Controles globales
#------------------------------------------------------------------------------------------

alineacion_global = (
    len(X_array)
    ==
    len(y_array)
    ==
    len(metadata_secuencias_detalle)
)

fechas_completas = (
    metadata_secuencias_detalle[
        [
            "Nodo",
            "Fecha_Inicio",
            "Fecha_Fin",
            "Fecha_Objetivo"
        ]
    ]
    .notna()
    .all()
    .all()
)

orden_temporal_correcto = (

    (
        metadata_secuencias_detalle[
            "Fecha_Inicio"
        ]
        <=
        metadata_secuencias_detalle[
            "Fecha_Fin"
        ]
    )
    &
    (
        metadata_secuencias_detalle[
            "Fecha_Fin"
        ]
        <
        metadata_secuencias_detalle[
            "Fecha_Objetivo"
        ]
    )

).all()

nodos_fuente = set(
    datos_secuencias[
        "Nodo"
    ].unique()
)

nodos_secuencias = set(
    metadata_secuencias_detalle[
        "Nodo"
    ].unique()
)

nodos_coinciden = (
    nodos_fuente
    ==
    nodos_secuencias
)

conteo_correcto_por_nodo = (
    control_nodos[
        "Conteo_Correcto"
    ]
    .all()
)

#------------------------------------------------------------------------------------------
# Índice secuencial, si ya fue incorporado durante la exportación
#------------------------------------------------------------------------------------------

if (
    "Indice_Secuencia"
    in metadata_secuencias_detalle.columns
):

    indices_secuenciales = np.array_equal(

        metadata_secuencias_detalle[
            "Indice_Secuencia"
        ].to_numpy(),

        np.arange(
            len(metadata_secuencias_detalle)
        )

    )

else:

    indices_secuenciales = True

#------------------------------------------------------------------------------------------
# Integridad global
#------------------------------------------------------------------------------------------

integridad_global = all([

    alineacion_global,
    fechas_completas,
    orden_temporal_correcto,
    nodos_coinciden,
    conteo_correcto_por_nodo,
    indices_secuenciales

])

#------------------------------------------------------------------------------------------
# Reporte
#------------------------------------------------------------------------------------------

print()

print("=" * 90)
print("INTEGRIDAD TEMPORAL DE LAS SECUENCIAS")
print("=" * 90)

print()

print(
    f"Secuencias en X             : {len(X_array)}"
)

print(
    f"Objetivos en y              : {len(y_array)}"
)

print(
    f"Registros metadata          : {len(metadata_secuencias_detalle)}"
)

print(
    f"Índices secuenciales        : {indices_secuenciales}"
)

print(
    f"Fechas completas            : {fechas_completas}"
)

print(
    f"Orden temporal correcto     : {orden_temporal_correcto}"
)

print(
    f"Nodos coinciden             : {nodos_coinciden}"
)

print(
    f"Conteo correcto por Nodo    : {conteo_correcto_por_nodo}"
)

print()

display(
    control_nodos
)

print()

print(
    f"INTEGRIDAD GLOBAL           : {integridad_global}"
)

==========================================================================================
INTEGRIDAD TEMPORAL DE LAS SECUENCIAS
==========================================================================================

Secuencias en X             : 336
Objetivos en y              : 336
Registros metadata          : 336
Índices secuenciales        : True
Fechas completas            : True
Orden temporal correcto     : True
Nodos coinciden             : True
Conteo correcto por Nodo    : True

               Nodo  Observaciones  Potenciales  Esperadas_Validas  Obtenidas  Conteo_Correcto
0     Bogota_Sabana            132          120                 84         84             True
1          Sopo_Sur            132          120                 84         84             True
2   Tocancipa_Media            132          120                 84         84             True
3  Villapinzon_Alta            132          120                 84         84             True

INTEGRIDAD GLOBAL           : True

In [54]:
#==========================================================================================
# CONTROL DE PREDICTORAS EXCLUIDAS POR COBERTURA
#==========================================================================================

#------------------------------------------------------------------------------------------
# Predictoras efectivamente utilizadas en las secuencias
#------------------------------------------------------------------------------------------

predictoras_modelo = X.columns.tolist()

#------------------------------------------------------------------------------------------
# Validación de exclusiones
#------------------------------------------------------------------------------------------

excluidas_presentes_en_X = [
    variable
    for variable in predictoras_excluidas_cobertura
    if variable in predictoras_modelo
]

exclusion_correcta = (
    len(excluidas_presentes_en_X) == 0
)

#------------------------------------------------------------------------------------------
# Controles
#------------------------------------------------------------------------------------------

print()

print("=" * 90)
print("CONTROL DE PREDICTORAS EXCLUIDAS")
print("=" * 90)

print()

print(
    f"Predictoras originales seleccionadas : {len(predictoras)}"
)

print(
    f"Predictoras utilizadas en secuencias : {len(predictoras_modelo)}"
)

print()

print("Predictoras excluidas por cobertura:")

if predictoras_excluidas_cobertura:

    for variable in predictoras_excluidas_cobertura:
        print(
            f"- {variable}"
        )

else:

    print("- Ninguna")

print()

print(
    f"Excluidas presentes todavía en X     : {excluidas_presentes_en_X}"
)

print(
    f"Exclusión aplicada correctamente      : {exclusion_correcta}"
)

==========================================================================================
CONTROL DE PREDICTORAS EXCLUIDAS
==========================================================================================

Predictoras originales seleccionadas : 9
Predictoras utilizadas en secuencias : 9

Predictoras excluidas por cobertura:
- Ninguna

Excluidas presentes todavía en X     : []
Exclusión aplicada correctamente      : True

In [55]:
#==========================================================================================
# RESUMEN TEMPORAL DE LAS SECUENCIAS GENERADAS
#==========================================================================================

import pandas as pd
import numpy as np

#------------------------------------------------------------------------------------------
# Integración de metadata y objetivo
#------------------------------------------------------------------------------------------

resumen_secuencias = (
    metadata_secuencias_detalle
    .copy()
    .reset_index(drop=True)
)

resumen_secuencias[
    "Objetivo"
] = y_array

#------------------------------------------------------------------------------------------
# Resumen por Nodo
#------------------------------------------------------------------------------------------

resumen_temporal_nodos = (
    resumen_secuencias
    .groupby(
        "Nodo",
        sort=False
    )
    .agg(
        Secuencias=(
            "Indice_Secuencia",
            "size"
        ),
        Primera_Fecha_Inicio=(
            "Fecha_Inicio",
            "min"
        ),
        Primera_Fecha_Objetivo=(
            "Fecha_Objetivo",
            "min"
        ),
        Ultima_Fecha_Objetivo=(
            "Fecha_Objetivo",
            "max"
        )
    )
    .reset_index()
)

#------------------------------------------------------------------------------------------
# Controles
#------------------------------------------------------------------------------------------

nodos_fuente = set(
    metadata_temporal["Nodo"].unique()
)

nodos_secuencias = set(
    metadata_secuencias_detalle["Nodo"].unique()
)

nodos_coinciden = (
    nodos_fuente
    ==
    nodos_secuencias
)

total_por_nodos = int(
    resumen_temporal_nodos[
        "Secuencias"
    ].sum()
)

conteo_coincide = (
    total_por_nodos
    ==
    len(X_array)
)

print()

print("=" * 90)
print("RESUMEN TEMPORAL DE SECUENCIAS")
print("=" * 90)

print()

print(
    f"Nodos fuente               : {len(nodos_fuente)}"
)

print(
    f"Nodos en secuencias        : {len(nodos_secuencias)}"
)

print(
    f"Nodos coinciden            : {nodos_coinciden}"
)

print(
    f"Secuencias por nodos       : {total_por_nodos}"
)

print(
    f"Secuencias en X            : {len(X_array)}"
)

print(
    f"Conteo global coincide     : {conteo_coincide}"
)

print()

display(
    resumen_temporal_nodos
)

#------------------------------------------------------------------------------------------
# Distribución del objetivo por Nodo
# Solo para clasificación
#------------------------------------------------------------------------------------------

if str(TIPO_PROBLEMA).lower().startswith(
    "clas"
):

    print()
    print("Distribución del objetivo por Nodo:")
    print()

    distribucion_nodo = pd.crosstab(
        resumen_secuencias["Nodo"],
        resumen_secuencias["Objetivo"]
    )

    display(
        distribucion_nodo
    )

==========================================================================================
RESUMEN TEMPORAL DE SECUENCIAS
==========================================================================================

Nodos fuente               : 4
Nodos en secuencias        : 4
Nodos coinciden            : True
Secuencias por nodos       : 336
Secuencias en X            : 336
Conteo global coincide     : True

               Nodo  Secuencias Primera_Fecha_Inicio Primera_Fecha_Objetivo Ultima_Fecha_Objetivo
0     Bogota_Sabana          84           2018-01-01             2019-01-01            2025-12-01
1          Sopo_Sur          84           2018-01-01             2019-01-01            2025-12-01
2   Tocancipa_Media          84           2018-01-01             2019-01-01            2025-12-01
3  Villapinzon_Alta          84           2018-01-01             2019-01-01            2025-12-01

In [56]:
#==========================================================================================
# VALIDACIÓN INTEGRAL DEL FRAMEWORK
#==========================================================================================

import numpy as np
import pandas as pd

#------------------------------------------------------------------------------------------
# Controles estructurales
#------------------------------------------------------------------------------------------

controles_framework = {

    "Alineacion_X_y":
        len(X_array) == len(y_array),

    "Alineacion_metadata":
        len(X_array) == len(metadata_secuencias_detalle),

    "Integridad_temporal":
        bool(integridad_global),

    "Exclusiones_cobertura":
        bool(exclusion_correcta),

    "Sin_NaN_en_X":
        not pd.isna(X_array).any(),

    "Sin_NaN_en_y":
        not pd.isna(y_array).any(),

    "Objetivo_modelo_fuera_de_X":
        VARIABLE_OBJETIVO_MODELO not in X.columns,

    "Objetivo_cientifico_fuera_de_X":
        VARIABLE_OBJETIVO not in X.columns,

    "Escalamiento_no_aplicado_en_C13":
        not bool(
            globals().get(
                "TRANSFORMACION_APLICADA",
                False
            )
        )
}

#------------------------------------------------------------------------------------------
# Validación adicional según tipo de problema
#------------------------------------------------------------------------------------------

if str(TIPO_PROBLEMA).lower().startswith(
    "clas"
):

    clases_objetivo = np.unique(
        y_array
    )

    controles_framework[
        "Clasificacion_con_dos_o_mas_clases"
    ] = (
        len(clases_objetivo) >= 2
    )

else:

    clases_objetivo = None

#------------------------------------------------------------------------------------------
# Resultado global
#------------------------------------------------------------------------------------------

resultado_framework = all(
    controles_framework.values()
)

#------------------------------------------------------------------------------------------
# Reporte
#------------------------------------------------------------------------------------------

print()

print("=" * 90)
print("VALIDACIÓN INTEGRAL DEL FRAMEWORK")
print("=" * 90)

print()

print(
    f"Dominio                    : {DOMINIO}"
)

print(
    f"Objetivo científico        : {VARIABLE_OBJETIVO}"
)

print(
    f"Objetivo del modelo        : {VARIABLE_OBJETIVO_MODELO}"
)

print(
    f"Tipo de problema           : {TIPO_PROBLEMA}"
)

print(
    f"Ventana temporal           : {VENTANA}"
)

print(
    f"Horizonte                  : {HORIZONTE}"
)

print(
    f"Variables predictoras      : {X.shape[1]}"
)

print(
    f"Secuencias generadas       : {len(X_array)}"
)

print(
    f"Nodos                      : {metadata_secuencias_detalle['Nodo'].nunique()}"
)

print(
    f"Método de transformación   : {metodo_transformacion}"
)

print(
    "Escalamiento aplicado C13 : False"
)

if clases_objetivo is not None:

    print(
        f"Clases objetivo            : {clases_objetivo.tolist()}"
    )

print()

print("Controles:")

for control, estado in controles_framework.items():

    print(
        f"- {control:<38}: {estado}"
    )

print()

if resultado_framework:

    print(
        "Resultado : VALIDACIÓN EXITOSA"
    )

else:

    raise Exception(
        "La validación integral del Framework detectó inconsistencias."
    )

==========================================================================================
VALIDACIÓN INTEGRAL DEL FRAMEWORK
==========================================================================================

Dominio                    : Gestión Hídrica
Objetivo científico        : VolumenUtilDiarioMasa
Objetivo del modelo        : VolumenUtilDiarioMasa
Tipo de problema           : Regresión
Ventana temporal           : 12
Horizonte                  : 1
Variables predictoras      : 9
Secuencias generadas       : 336
Nodos                      : 4
Método de transformación   : RobustScaler
Escalamiento aplicado C13 : False

Controles:
- Alineacion_X_y                        : True
- Alineacion_metadata                   : True
- Integridad_temporal                   : True
- Exclusiones_cobertura                 : True
- Sin_NaN_en_X                          : True
- Sin_NaN_en_y                          : True
- Objetivo_modelo_fuera_de_X            : True
- Objetivo_cientifico_fuera_de_X        : True
- Escalamiento_no_aplicado_en_C13       : True

Resultado : VALIDACIÓN EXITOSA

## **M8. Consolidación del Framework de Preparación para Machine Learning**

In [57]:
#==========================================================================================
# CONSOLIDACIÓN DEL FRAMEWORK DE PREPARACIÓN PARA MACHINE LEARNING
#==========================================================================================

print()

print("=" * 90)
print("FRAMEWORK DE PREPARACIÓN PARA MACHINE LEARNING")
print("=" * 90)

print()

print(
    f"Experimento                 : {EXPERIMENTO}"
)

print(
    f"Dominio                     : {DOMINIO}"
)

print(
    f"Objetivo científico         : {VARIABLE_OBJETIVO}"
)

print(
    f"Objetivo del modelo         : {VARIABLE_OBJETIVO_MODELO}"
)

print(
    f"Tipo de problema            : {TIPO_PROBLEMA}"
)

print(
    f"Modelo                      : {MODELO}"
)

print()

print(
    f"Ventana temporal            : {VENTANA}"
)

print(
    f"Horizonte                   : {HORIZONTE}"
)

print(
    f"Nodos                       : {metadata_secuencias_detalle['Nodo'].nunique()}"
)

print()

print(
    f"Observaciones originales    : {len(dataset_transformado)}"
)

print(
    f"Predictoras seleccionadas   : {len(predictoras)}"
)

print(
    f"Predictoras utilizadas      : {X.shape[1]}"
)

print(
    f"Secuencias generadas        : {len(X_array)}"
)

print()

print(
    f"Método de transformación    : {metodo_transformacion}"
)

print(
    "Transformación aplicada C13: False"
)

print(
    "Ajuste definitivo scaler   : C14 - conjunto de entrenamiento"
)

print()

print("Productos generados:")

print(
    "✔ dataset_machine_learning_transformado.parquet"
)

print(
    "✔ dataset_machine_learning_transformado.csv"
)

print(
    "✔ metadata_temporal.parquet"
)

print(
    "✔ metadata_temporal.csv"
)

print(
    "✔ secuencias_X.npy"
)

print(
    "✔ secuencias_y.npy"
)

print(
    "✔ metadata_secuencias.csv"
)

print(
    "✔ metadata_secuencias_detalle.csv"
)

print(
    "✔ metadata_secuencias_detalle.parquet"
)

print()

if resultado_framework:

    print(
        "Estado del Framework      : FINALIZADO Y VALIDADO"
    )

else:

    raise Exception(
        "El Framework no puede consolidarse "
        "porque la validación integral no fue exitosa."
    )

==========================================================================================
FRAMEWORK DE PREPARACIÓN PARA MACHINE LEARNING
==========================================================================================

Experimento                 : Exp04
Dominio                     : Gestión Hídrica
Objetivo científico         : VolumenUtilDiarioMasa
Objetivo del modelo         : VolumenUtilDiarioMasa
Tipo de problema            : Regresión
Modelo                      : LSTM

Ventana temporal            : 12
Horizonte                   : 1
Nodos                       : 4

Observaciones originales    : 528
Predictoras seleccionadas   : 9
Predictoras utilizadas      : 9
Secuencias generadas        : 336

Método de transformación    : RobustScaler
Transformación aplicada C13: False
Ajuste definitivo scaler   : C14 - conjunto de entrenamiento

Productos generados:
✔ dataset_machine_learning_transformado.parquet
✔ dataset_machine_learning_transformado.csv
✔ metadata_temporal.parquet
✔ metadata_temporal.csv
✔ secuencias_X.npy
✔ secuencias_y.npy
✔ metadata_secuencias.csv
✔ metadata_secuencias_detalle.csv
✔ metadata_secuencias_detalle.parquet

Estado del Framework      : FINALIZADO Y VALIDADO

In [58]:
#==========================================================================================
# RECUPERACIÓN DEL MÉTODO DE TRANSFORMACIÓN YA VALIDADO
#==========================================================================================

METODO_TRANSFORMACION = metodo_transformacion

print(f"Método de transformación registrado : {METODO_TRANSFORMACION}")

Método de transformación registrado : RobustScaler

In [59]:
#==========================================================================================
# REGISTRO DEL EXPERIMENTO DE PREPARACIÓN
#==========================================================================================

registro = pd.DataFrame({

    "Parametro": [

        "Experimento",
        "Dominio",
        "Tipo de Problema",
        "Modelo",

        # Objetivo operativo entregado a C14
        "Variable Objetivo",

        # Trazabilidad científica
        "Variable Objetivo Cientifico",

        "Ventana Temporal",
        "Horizonte",

        "Variables Predictoras",
        "Lista Variables Predictoras",

        "Observaciones",
        "Número de Secuencias",
        "Nodos",

        # Nombre requerido por C14
        "Método de Transformación",

        "Transformación Aplicada en C13",
        "Ajuste del Scaler"

    ],

    "Valor": [

        EXPERIMENTO,
        DOMINIO,
        TIPO_PROBLEMA,
        MODELO,

        VARIABLE_OBJETIVO_MODELO,
        VARIABLE_OBJETIVO,

        VENTANA,
        HORIZONTE,

        X.shape[1],

        ";".join(
            X.columns
        ),

        len(dataset_transformado),
        len(X_array),

        metadata_secuencias_detalle[
            "Nodo"
        ].nunique(),

        METODO_TRANSFORMACION,

        False,

        "C14 - conjunto de entrenamiento"

    ]

})

print()

print("=" * 90)
print("REGISTRO DEL EXPERIMENTO")
print("=" * 90)

print()

display(
    registro
)

==========================================================================================
REGISTRO DEL EXPERIMENTO
==========================================================================================

                         Parametro                                              Valor
0                      Experimento                                              Exp04
1                          Dominio                                    Gestión Hídrica
2                 Tipo de Problema                                          Regresión
3                           Modelo                                               LSTM
4                Variable Objetivo                              VolumenUtilDiarioMasa
5     Variable Objetivo Cientifico                              VolumenUtilDiarioMasa
6                 Ventana Temporal                                                 12
7                        Horizonte                                                  1
8            Variables Predictoras                                                  9
9      Lista Variables Predictoras  ONI;PORCENTAJE DE LA POBLACION CON ACCESO A ME...
10                   Observaciones                                                528
11            Número de Secuencias                                                336
12                           Nodos                                                  4
13        Método de Transformación                                       RobustScaler
14  Transformación Aplicada en C13                                              False
15               Ajuste del Scaler                    C14 - conjunto de entrenamiento

In [60]:
#==========================================================================================
# EXPORTACIÓN DEL REGISTRO
#==========================================================================================

registro.to_csv(
    "registro_preparacion.csv",
    index=False,
    encoding="utf-8-sig"
)

registro.to_excel(
    "registro_preparacion.xlsx",
    index=False
)

print()

print("="*90)
print("EXPORTACIÓN")
print("="*90)

print()

print("Archivos generados")

print()

print("- registro_preparacion.csv")
print("- registro_preparacion.xlsx")

==========================================================================================
EXPORTACIÓN
==========================================================================================

Archivos generados

- registro_preparacion.csv
- registro_preparacion.xlsx

In [61]:
#==========================================================================================
# VALIDACIÓN FINAL DE ARTEFACTOS
#==========================================================================================

import os
import numpy as np
import pandas as pd

#------------------------------------------------------------------------------------------
# Artefactos obligatorios generados por C13
#------------------------------------------------------------------------------------------

archivos_obligatorios = [

    "dataset_machine_learning_transformado.parquet",
    "dataset_machine_learning_transformado.csv",

    "metadata_temporal.parquet",
    "metadata_temporal.csv",

    "secuencias_X.npy",
    "secuencias_y.npy",

    "metadata_secuencias.csv",
    "metadata_secuencias_detalle.csv",
    "metadata_secuencias_detalle.parquet",

    "registro_preparacion.csv",
    "registro_preparacion.xlsx"

]

#------------------------------------------------------------------------------------------
# Existencia de archivos
#------------------------------------------------------------------------------------------

estado_archivos = {
    archivo: os.path.exists(archivo)
    for archivo in archivos_obligatorios
}

#------------------------------------------------------------------------------------------
# Carga de artefactos principales
#------------------------------------------------------------------------------------------

X_seq = np.load(
    "secuencias_X.npy"
)

y_seq = np.load(
    "secuencias_y.npy"
)

metadata_seq = pd.read_parquet(
    "metadata_secuencias_detalle.parquet"
)

registro_validacion = pd.read_csv(
    "registro_preparacion.csv"
)

#------------------------------------------------------------------------------------------
# Controles estructurales
#------------------------------------------------------------------------------------------

controles_finales = {

    "Todos_los_archivos_existen":
        all(estado_archivos.values()),

    "Alineacion_X_y":
        len(X_seq) == len(y_seq),

    "Alineacion_X_metadata":
        len(X_seq) == len(metadata_seq),

    "Shape_ventana_correcto":
        X_seq.shape[1] == VENTANA,

    "Numero_predictoras_correcto":
        X_seq.shape[2] == X.shape[1],

    "Sin_NaN_en_X":
        not pd.isna(X_seq).any(),

    "Sin_NaN_en_y":
        not pd.isna(y_seq).any(),

    "Metadata_sin_nulos_temporales":
        metadata_seq[
            [
                "Nodo",
                "Fecha_Inicio",
                "Fecha_Fin",
                "Fecha_Objetivo"
            ]
        ]
        .notna()
        .all()
        .all(),

    "Scaler_no_ajustado_en_C13":
        not bool(
            globals().get(
                "SCALER_AJUSTADO_EN_C13",
                False
            )
        ),

    "Framework_validado":
        bool(resultado_framework)

}

#------------------------------------------------------------------------------------------
# Validación del registro para C14
#------------------------------------------------------------------------------------------

registro_dict = (
    registro_validacion
    .set_index("Parametro")["Valor"]
    .to_dict()
)

controles_finales[
    "Objetivo_operativo_registrado"
] = (
    registro_dict.get(
        "Variable Objetivo"
    )
    ==
    VARIABLE_OBJETIVO_MODELO
)

controles_finales[
    "Metodo_transformacion_registrado"
] = (
    registro_dict.get(
        "Método de Transformación"
    )
    ==
    METODO_TRANSFORMACION
)

#------------------------------------------------------------------------------------------
# Resultado global
#------------------------------------------------------------------------------------------

validacion_final = all(
    controles_finales.values()
)

#------------------------------------------------------------------------------------------
# Reporte
#------------------------------------------------------------------------------------------

print()

print("=" * 90)
print("VALIDACIÓN FINAL DE ARTEFACTOS")
print("=" * 90)

print()

print("Archivos obligatorios:")
print()

for archivo, existe in estado_archivos.items():

    print(
        f"{archivo:<60} : {existe}"
    )

print()

print(
    f"Shape secuencias_X         : {X_seq.shape}"
)

print(
    f"Shape secuencias_y         : {y_seq.shape}"
)

print(
    f"Metadata de secuencias     : {metadata_seq.shape}"
)

print(
    f"NaN en X                   : {pd.isna(X_seq).sum()}"
)

print(
    f"NaN en y                   : {pd.isna(y_seq).sum()}"
)

print(
    f"Scaler generado en C13     : False"
)

print(
    f"Ajuste del scaler          : C14 - conjunto de entrenamiento"
)

print()

print("Controles finales:")
print()

for control, estado in controles_finales.items():

    print(
        f"- {control:<40}: {estado}"
    )

print()

if validacion_final:

    print(
        "Resultado final : C13 COMPLETADO Y VALIDADO"
    )

else:

    raise Exception(
        "La validación final de artefactos detectó inconsistencias."
    )

==========================================================================================
VALIDACIÓN FINAL DE ARTEFACTOS
==========================================================================================

Archivos obligatorios:

dataset_machine_learning_transformado.parquet                : True
dataset_machine_learning_transformado.csv                    : True
metadata_temporal.parquet                                    : True
metadata_temporal.csv                                        : True
secuencias_X.npy                                             : True
secuencias_y.npy                                             : True
metadata_secuencias.csv                                      : True
metadata_secuencias_detalle.csv                              : True
metadata_secuencias_detalle.parquet                          : True
registro_preparacion.csv                                     : True
registro_preparacion.xlsx                                    : True

Shape secuencias_X         : (336, 12, 9)
Shape secuencias_y         : (336,)
Metadata de secuencias     : (336, 5)
NaN en X                   : 0
NaN en y                   : 0
Scaler generado en C13     : False
Ajuste del scaler          : C14 - conjunto de entrenamiento

Controles finales:

- Todos_los_archivos_existen              : True
- Alineacion_X_y                          : True
- Alineacion_X_metadata                   : True
- Shape_ventana_correcto                  : True
- Numero_predictoras_correcto             : True
- Sin_NaN_en_X                            : True
- Sin_NaN_en_y                            : True
- Metadata_sin_nulos_temporales           : True
- Scaler_no_ajustado_en_C13               : True
- Framework_validado                      : True
- Objetivo_operativo_registrado           : True
- Metodo_transformacion_registrado        : True

Resultado final : C13 COMPLETADO Y VALIDADO