# **CAPA ONI**

# **Objetivo de la Capa**

Desarrollar una capa de información climática basada en el Índice Oceánico del Niño (ONI), estandarizada bajo la arquitectura del Framework V7, con el propósito de incorporar la variabilidad climática de gran escala como variable exógena en los modelos de predicción hidrológica. Esta capa permite representar la influencia de los fenómenos El Niño, La Niña y condiciones Neutrales sobre la dinámica hidrológica de la cuenca del río Bogotá, facilitando la integración de señales climáticas globales con las variables hidrológicas, meteorológicas y ambientales utilizadas por el modelo LSTM.

#  **Justificación Científica**

El comportamiento hidrológico de una cuenca no depende exclusivamente de las condiciones locales de precipitación, temperatura o caudal, sino que también está influenciado por procesos climáticos de gran escala asociados a la variabilidad océano-atmósfera. Uno de los principales mecanismos que explica esta interacción es el fenómeno ENSO (El Niño–Oscilación del Sur), cuya intensidad es cuantificada mediante el Índice Oceánico del Niño (ONI), calculado a partir de las anomalías de temperatura superficial del océano Pacífico ecuatorial en la región Niño 3.4.

Diversos estudios han demostrado que las fases cálidas (El Niño) y frías (La Niña) modifican los patrones de precipitación, la disponibilidad hídrica y la ocurrencia de eventos extremos en Colombia, generando efectos directos sobre los niveles de los ríos, los embalses y la calidad del agua. Por esta razón, la incorporación del ONI dentro del Framework V7 permite incluir una variable climática de carácter predictivo que antecede temporalmente muchas de las respuestas hidrológicas observadas.

La estandarización de esta serie temporal bajo principios de gobierno del dato garantiza su interoperabilidad con las demás capas del Framework, permitiendo que el modelo LSTM aprenda relaciones temporales entre las anomalías oceánicas y el comportamiento hidrológico de la cuenca del río Bogotá, fortaleciendo así la capacidad predictiva del sistema frente a escenarios de variabilidad climática.

# **Alcance de la capa**

La capa ONI comprende la adquisición, estandarización, validación y documentación de la serie temporal mensual del Índice Oceánico del Niño (ONI), obtenida a partir de la información oficial publicada por la National Oceanic and Atmospheric Administration (NOAA). El proceso incluye la extracción automática de la información, la normalización de fechas, la clasificación de los estados ENSO (Niño, Niña y Neutral), la incorporación de metadatos, mecanismos de auditoría, indicadores de calidad y elementos de gobierno del dato definidos por el Framework V7.

El alcance de esta capa se limita a representar la señal climática global asociada al fenómeno ENSO y no pretende modelar directamente variables hidrológicas o meteorológicas locales. Su función principal consiste en aportar una variable exógena de carácter climático que será integrada posteriormente con las capas de clima, hidrología, calidad del agua, embalses y demás componentes del Framework para la construcción del conjunto de datos maestro que alimentará el modelo predictivo basado en redes neuronales LSTM.

#  **Capa**

*   **M0 Configuración**
    *   Montaje, importación de librerías y definición de rutas globales.
*   **M1 Lectura**
    *   Conexión e ingesta del archivo original.
*   **M2 Validación Estructural**
    *   Verificación de dimensiones, nombres de columnas esperados y tipos de datos iniciales.
*   **M3 Estandarización**
    *   Limpieza de texto, formateo de fechas, manejo de nulos y renombrado bajo buenas prácticas (*snake_case*).
*   **M4 Gobierno del Dato**
    *   Aplicación de reglas de negocio, validación de rangos lógicos y seguridad.
*   **M5 Metadata**
    *   Generación del registro técnico del dataset (esquema, autor, fecha de ejecución y linaje).
*   **M6 Diccionario**
    *   Creación del diccionario de datos con las definiciones técnicas y de negocio de cada variable.
*   **M7 Auditoría**
    *   Control de registros (filas procesadas vs. descartadas) y logs de errores.
*   **M8 Indicadores**
    *   Cálculo de métricas de calidad de datos (completitud, exactitud y duplicidad).
*   **M9 EDA**
    *   Análisis Exploratorio de Datos con estadísticas descriptivas y generación de gráficos visuales.
*   **M10 README**
    *   Documentación general del proceso (este componente).
*   **Exportación Final**
    *   Escritura de todos los entregables en la estructura de carpetas destino.

---

# **Estructura de Archivos Generada**

```text
04_Capa_ONI/
├── 01_Capa_Oni_V1.xlsx               ← Evidencia original (Datos crudos)
├── 02_Capa_ONI_Framework.xlsx        ← Dataset estandarizado y limpio (Listo para usar)
├── 03_Metadata.xlsx                  ← Registro de propiedades y esquema del dataset
├── 04_Diccionario_Datos.xlsx         ← Definición técnica y de negocio de las variables
├── 05_Auditoria.xlsx                 ← Logs de procesamiento y control de registros
├── 06_Indicadores.xlsx               ← Métricas de calidad del dato
├── 07_EDA.xlsx                       ← Reporte estadístico del Análisis Exploratorio
├── 08_README.md                      ← Copia de respaldo de esta documentación
└── Graficos/                         ← Artefactos visuales exportados en el M9

## **M0 – Configuración**

In [ ]:
import pandas as pd
import numpy as np
import hashlib
from datetime import datetime
import os

# ============================================================
# FRAMEWORK V7
# FRAMEWORK CORE
# GENERADOR UNIVERSAL DE CAPAS
# ============================================================

NOMBRE_CAPA = "ONI"

CODIGO_CAPA = "ONI"

VERSION = "1.0"

RESPONSABLE = "Juan Carlos Riatiga"

FUENTE = "NOAA - Climate Prediction Center (CPC)"

URL_FUENTE = "https://www.cpc.ncep.noaa.gov/"

ARCHIVO = "https://raw.githubusercontent.com/jriatiga/dataset/refs/heads/main/proyectoGradoV4/04_Capa_ONI/01_Capa_Oni_V1.xlsx"

## **M1 – Lectura**

In [ ]:
# ============================================================
# M1 – Lectura
# ============================================================

df = pd.read_excel(ARCHIVO)

print("=" * 70)
print("CAPA:", NOMBRE_CAPA)
print("=" * 70)

print("\nPrimeros registros")
print(df.head())

print("\nDimensiones")
print(df.shape)

print("\nColumnas")
print(df.columns.tolist())

======================================================================
CAPA: ONI
======================================================================

Primeros registros
       Fecha   ONI Estado_ENSO
0 2015-01-31  0.68        Niño
1 2015-02-28  0.57        Niño
2 2015-03-31  0.57        Niño
3 2015-04-30  0.82        Niño
4 2015-05-31  1.03        Niño

Dimensiones
(135, 3)

Columnas
['Fecha', 'ONI', 'Estado_ENSO']

## **M2 – Validación estructural**

In [ ]:
print(df.dtypes)

Fecha          datetime64[ns]
ONI                   float64
Estado_ENSO            object
dtype: object

In [ ]:
print(type(df.loc[0, "Fecha"]))

print()

print(df["Fecha"].head())

<class 'pandas._libs.tslibs.timestamps.Timestamp'>

0   2015-01-31
1   2015-02-28
2   2015-03-31
3   2015-04-30
4   2015-05-31
Name: Fecha, dtype: datetime64[ns]

In [ ]:
df["Fecha"] = pd.to_datetime(df["Fecha"])

print("Después de la conversión:\n")

print(df["Fecha"].head())

print()

print(df["Fecha"].dtype)

Después de la conversión:

0   2015-01-31
1   2015-02-28
2   2015-03-31
3   2015-04-30
4   2015-05-31
Name: Fecha, dtype: datetime64[ns]

datetime64[ns]

In [ ]:
print(df["ONI"].describe())

count    135.000000
mean       0.159407
std        0.932565
min       -1.360000
25%       -0.545000
50%       -0.020000
75%        0.645000
max        2.770000
Name: ONI, dtype: float64

In [ ]:
print(df["Estado_ENSO"].value_counts())

Estado_ENSO
Neutral    52
Niño       44
Niña       39
Name: count, dtype: int64

## **M3 – Estandarización**

In [ ]:
# Crear identificadores

df.insert(
    0,
    "ID_Registro",
    [
        f"{CODIGO_CAPA}-{str(i).zfill(7)}"
        for i in range(1, len(df)+1)
    ]
)

df["ID_Capa"] = CODIGO_CAPA

In [ ]:
# Ordenar columnas

columnas_control = [
    "ID_Registro",
    "ID_Capa"
]

otras_columnas = [
    c
    for c in df.columns
    if c not in columnas_control
]

df = df[columnas_control + otras_columnas]

In [ ]:
# Normalización de tipos

df["Fecha"] = pd.to_datetime(df["Fecha"])

df["ONI"] = df["ONI"].astype(float)

df["Estado_ENSO"] = df["Estado_ENSO"].astype(str)

In [ ]:
# Eliminar espacios

df.columns = df.columns.str.strip()

df["Estado_ENSO"] = df["Estado_ENSO"].str.strip()

In [ ]:
# Ordenar registros

df = (
    df
    .sort_values(by="Fecha")
    .reset_index(drop=True)
)

In [ ]:
print(df.head())

print()

print(df.columns)

print()

print(df.dtypes)

   ID_Registro ID_Capa      Fecha   ONI Estado_ENSO
0  ONI-0000001     ONI 2015-01-31  0.68        Niño
1  ONI-0000002     ONI 2015-02-28  0.57        Niño
2  ONI-0000003     ONI 2015-03-31  0.57        Niño
3  ONI-0000004     ONI 2015-04-30  0.82        Niño
4  ONI-0000005     ONI 2015-05-31  1.03        Niño

Index(['ID_Registro', 'ID_Capa', 'Fecha', 'ONI', 'Estado_ENSO'], dtype='object')

ID_Registro            object
ID_Capa                object
Fecha          datetime64[ns]
ONI                   float64
Estado_ENSO            object
dtype: object

Este M3 queda completamente alineado con las capas de Clima, Hidrología y Calidad del Agua, manteniendo la consistencia metodológica del Framework V7. La diferencia es que aquí no se requiere ninguna estandarización adicional porque el dataset ya viene mensual, limpio y con la clasificación ENSO incorporada.

## **M4 – Gobierno del Dato**

In [ ]:
# Fecha ETL

fecha = datetime.now()

df["Fecha_ETL"] = fecha.strftime("%Y-%m-%d")

df["Hora_ETL"] = fecha.strftime("%H:%M:%S")

In [ ]:
# Versión del Framework

df["Version_Framework"] = VERSION

In [ ]:
# Estado del registro

df["Estado_Registro"] = "VALIDADO"

In [ ]:
# Responsable

df["Responsable"] = RESPONSABLE

In [ ]:
# Hash de integridad

def generar_hash(fila):

    texto = "".join(fila.astype(str))

    return hashlib.md5(texto.encode()).hexdigest()


df["Hash"] = (
    df.astype(str)
      .apply(generar_hash, axis=1)
)

In [ ]:
print(df.head())

print()

print(df.columns)

print()

print(df.dtypes)

   ID_Registro ID_Capa      Fecha   ONI Estado_ENSO   Fecha_ETL  Hora_ETL  \
0  ONI-0000001     ONI 2015-01-31  0.68        Niño  2026-07-15  20:27:23
1  ONI-0000002     ONI 2015-02-28  0.57        Niño  2026-07-15  20:27:23
2  ONI-0000003     ONI 2015-03-31  0.57        Niño  2026-07-15  20:27:23
3  ONI-0000004     ONI 2015-04-30  0.82        Niño  2026-07-15  20:27:23
4  ONI-0000005     ONI 2015-05-31  1.03        Niño  2026-07-15  20:27:23

  Version_Framework Estado_Registro          Responsable  \
0               1.0        VALIDADO  Juan Carlos Riatiga
1               1.0        VALIDADO  Juan Carlos Riatiga
2               1.0        VALIDADO  Juan Carlos Riatiga
3               1.0        VALIDADO  Juan Carlos Riatiga
4               1.0        VALIDADO  Juan Carlos Riatiga

                               Hash
0  adfed55b480618a3f14a0c98cee347e9
1  b774d95bce4a3acffd159977dbbca976
2  cfb259363abf39b6f0b72d8ddfc8b17f
3  c7344792ac0d349c3d3554060926afdd
4  7a626cdfafdb271107e484c098e2200b

Index(['ID_Registro', 'ID_Capa', 'Fecha', 'ONI', 'Estado_ENSO', 'Fecha_ETL',
       'Hora_ETL', 'Version_Framework', 'Estado_Registro', 'Responsable',
       'Hash'],
      dtype='object')

ID_Registro                  object
ID_Capa                      object
Fecha                datetime64[ns]
ONI                         float64
Estado_ENSO                  object
Fecha_ETL                    object
Hora_ETL                     object
Version_Framework            object
Estado_Registro              object
Responsable                  object
Hash                         object
dtype: object

## **M5 – Metadata**

In [ ]:
# ============================================================
# METADATA
# ============================================================

metadata = pd.DataFrame({

    "Propiedad":[

        "Nombre Capa",
        "Código",
        "Versión",
        "Fuente",
        "URL Fuente",
        "Archivo",
        "Responsable",
        "Fecha ETL",
        "Hora ETL",
        "Número Registros",
        "Número Variables",
        "Cobertura Temporal",
        "Valor Mínimo ONI",
        "Valor Máximo ONI",
        "Estados ENSO"

    ],

    "Valor":[

        NOMBRE_CAPA,
        CODIGO_CAPA,
        VERSION,
        FUENTE,
        URL_FUENTE,
        ARCHIVO,
        RESPONSABLE,
        df["Fecha_ETL"].iloc[0],
        df["Hora_ETL"].iloc[0],
        len(df),
        len(df.columns),
        f"{df['Fecha'].min().date()} - {df['Fecha'].max().date()}",
        df["ONI"].min(),
        df["ONI"].max(),
        df["Estado_ENSO"].nunique()

    ]

})

metadata

             Propiedad                                              Valor
0          Nombre Capa                                                ONI
1               Código                                                ONI
2              Versión                                                1.0
3               Fuente             NOAA - Climate Prediction Center (CPC)
4           URL Fuente                     https://www.cpc.ncep.noaa.gov/
5              Archivo  https://raw.githubusercontent.com/jriatiga/dat...
6          Responsable                                Juan Carlos Riatiga
7            Fecha ETL                                         2026-07-15
8             Hora ETL                                           20:27:23
9     Número Registros                                                135
10    Número Variables                                                 11
11  Cobertura Temporal                            2015-01-31 - 2026-03-31
12    Valor Mínimo ONI                                              -1.36
13    Valor Máximo ONI                                               2.77
14        Estados ENSO                                                  3

In [ ]:
metadata.to_excel(

    "03_Metadata.xlsx",

    index=False

)

print("Metadata generado correctamente.")

Metadata generado correctamente.

In [ ]:
metadata

             Propiedad                                              Valor
0          Nombre Capa                                                ONI
1               Código                                                ONI
2              Versión                                                1.0
3               Fuente             NOAA - Climate Prediction Center (CPC)
4           URL Fuente                     https://www.cpc.ncep.noaa.gov/
5              Archivo  https://raw.githubusercontent.com/jriatiga/dat...
6          Responsable                                Juan Carlos Riatiga
7            Fecha ETL                                         2026-07-15
8             Hora ETL                                           20:27:23
9     Número Registros                                                135
10    Número Variables                                                 11
11  Cobertura Temporal                            2015-01-31 - 2026-03-31
12    Valor Mínimo ONI                                              -1.36
13    Valor Máximo ONI                                               2.77
14        Estados ENSO                                                  3

Como el ONI es una serie climática categorizada, para agregar un último indicador que no existe en las otras capas porque aquí sí aporta valor científico:

Así el metadata almacenará automáticamente algo como:
{'Neutral': 52, 'Niño': 44, 'Niña': 39}

In [ ]:
metadata.loc[len(metadata)] = [

    "Distribución ENSO",

    df["Estado_ENSO"].value_counts().to_dict()

]

## **M6 – Diccionario de Datos**

In [ ]:
# ============================================================
# DICCIONARIO DE DATOS
# ============================================================

diccionario = pd.DataFrame({

    "Variable": df.columns,

    "Tipo_Dato": df.dtypes.astype(str).values,

    "Descripción": [

        "Identificador único del registro.",

        "Código de la capa del Framework.",

        "Fecha correspondiente al registro mensual del índice ONI.",

        "Valor del Índice Oceánico Niño (Oceanic Niño Index).",

        "Clasificación del estado ENSO (Niño, Niña o Neutral).",

        "Fecha de ejecución del proceso ETL.",

        "Hora de ejecución del proceso ETL.",

        "Versión del Framework.",

        "Estado del registro dentro del proceso ETL.",

        "Responsable del procesamiento.",

        "Hash MD5 utilizado para garantizar la integridad del registro."

    ]

})

diccionario

,Variable,Tipo_Dato,Descripción
0,ID_Registro,object,Identificador único del registro.
1,ID_Capa,object,Código de la capa del Framework.
2,Fecha,datetime64[ns],Fecha correspondiente al registro mensual del ...
3,ONI,float64,Valor del Índice Oceánico Niño (Oceanic Niño I...
4,Estado_ENSO,object,"Clasificación del estado ENSO (Niño, Niña o Ne..."
5,Fecha_ETL,object,Fecha de ejecución del proceso ETL.
6,Hora_ETL,object,Hora de ejecución del proceso ETL.
7,Version_Framework,object,Versión del Framework.
8,Estado_Registro,object,Estado del registro dentro del proceso ETL.
9,Responsable,object,Responsable del procesamiento.
10,Hash,object,Hash MD5 utilizado para garantizar la integrid...

In [ ]:
diccionario.to_excel(

    "04_Diccionario_Datos.xlsx",

    index=False

)

print("Diccionario generado correctamente.")

Diccionario generado correctamente.

In [ ]:
diccionario

,Variable,Tipo_Dato,Descripción
0,ID_Registro,object,Identificador único del registro.
1,ID_Capa,object,Código de la capa del Framework.
2,Fecha,datetime64[ns],Fecha correspondiente al registro mensual del ...
3,ONI,float64,Valor del Índice Oceánico Niño (Oceanic Niño I...
4,Estado_ENSO,object,"Clasificación del estado ENSO (Niño, Niña o Ne..."
5,Fecha_ETL,object,Fecha de ejecución del proceso ETL.
6,Hora_ETL,object,Hora de ejecución del proceso ETL.
7,Version_Framework,object,Versión del Framework.
8,Estado_Registro,object,Estado del registro dentro del proceso ETL.
9,Responsable,object,Responsable del procesamiento.
10,Hash,object,Hash MD5 utilizado para garantizar la integrid...

## **M7 – Auditoría**

In [ ]:
# ============================================================
# AUDITORÍA DE LA CAPA ONI
# ============================================================

print("="*70)
print("AUDITORÍA DE LA CAPA ONI")
print("="*70)

print()

print("Primeros registros")
print(df.head())

print()

print("Últimos registros")
print(df.tail())

======================================================================
AUDITORÍA DE LA CAPA ONI
======================================================================

Primeros registros
   ID_Registro ID_Capa      Fecha   ONI Estado_ENSO   Fecha_ETL  Hora_ETL  \
0  ONI-0000001     ONI 2015-01-31  0.68        Niño  2026-07-15  20:27:23
1  ONI-0000002     ONI 2015-02-28  0.57        Niño  2026-07-15  20:27:23
2  ONI-0000003     ONI 2015-03-31  0.57        Niño  2026-07-15  20:27:23
3  ONI-0000004     ONI 2015-04-30  0.82        Niño  2026-07-15  20:27:23
4  ONI-0000005     ONI 2015-05-31  1.03        Niño  2026-07-15  20:27:23

  Version_Framework Estado_Registro          Responsable  \
0               1.0        VALIDADO  Juan Carlos Riatiga
1               1.0        VALIDADO  Juan Carlos Riatiga
2               1.0        VALIDADO  Juan Carlos Riatiga
3               1.0        VALIDADO  Juan Carlos Riatiga
4               1.0        VALIDADO  Juan Carlos Riatiga

                               Hash
0  adfed55b480618a3f14a0c98cee347e9
1  b774d95bce4a3acffd159977dbbca976
2  cfb259363abf39b6f0b72d8ddfc8b17f
3  c7344792ac0d349c3d3554060926afdd
4  7a626cdfafdb271107e484c098e2200b

Últimos registros
     ID_Registro ID_Capa      Fecha   ONI Estado_ENSO   Fecha_ETL  Hora_ETL  \
130  ONI-0000131     ONI 2025-11-30 -0.64        Niña  2026-07-15  20:27:23
131  ONI-0000132     ONI 2025-12-31 -0.57        Niña  2026-07-15  20:27:23
132  ONI-0000133     ONI 2026-01-31 -0.41     Neutral  2026-07-15  20:27:23
133  ONI-0000134     ONI 2026-02-28 -0.12     Neutral  2026-07-15  20:27:23
134  ONI-0000135     ONI 2026-03-31  0.09     Neutral  2026-07-15  20:27:23

    Version_Framework Estado_Registro          Responsable  \
130               1.0        VALIDADO  Juan Carlos Riatiga
131               1.0        VALIDADO  Juan Carlos Riatiga
132               1.0        VALIDADO  Juan Carlos Riatiga
133               1.0        VALIDADO  Juan Carlos Riatiga
134               1.0        VALIDADO  Juan Carlos Riatiga

                                 Hash
130  1ba07f783c53e16597e228840904e17e
131  e881435bbb17ca8cab179e20fdeb35ad
132  b1f1ba945f9908c949d77541a164f9c0
133  ae22761dd1be4b546c485959337dfeca
134  5ca7b9f074e785dfd1f49712115fa743

In [ ]:
# ============================================================
# TIPOS DE DATOS
# ============================================================

print("="*70)
print("TIPOS DE DATOS")
print("="*70)

print(df.dtypes)

print()

print("="*70)
print("USO DE MEMORIA")
print("="*70)

print(df.memory_usage(deep=True))

======================================================================
TIPOS DE DATOS
======================================================================
ID_Registro                  object
ID_Capa                      object
Fecha                datetime64[ns]
ONI                         float64
Estado_ENSO                  object
Fecha_ETL                    object
Hora_ETL                     object
Version_Framework            object
Estado_Registro              object
Responsable                  object
Hash                         object
dtype: object

======================================================================
USO DE MEMORIA
======================================================================
Index                  132
ID_Registro           8100
ID_Capa               7020
Fecha                 1080
ONI                   1080
Estado_ENSO           9137
Fecha_ETL             7965
Hora_ETL              7695
Version_Framework     7020
Estado_Registro       7695
Responsable           9180
Hash                 10935
dtype: int64

In [ ]:
# ============================================================
# VALORES NULOS
# ============================================================

print("="*70)
print("VALORES NULOS")
print("="*70)

print(df.isnull().sum())

======================================================================
VALORES NULOS
======================================================================
ID_Registro          0
ID_Capa              0
Fecha                0
ONI                  0
Estado_ENSO          0
Fecha_ETL            0
Hora_ETL             0
Version_Framework    0
Estado_Registro      0
Responsable          0
Hash                 0
dtype: int64

In [ ]:
# ============================================================
# REGISTROS DUPLICADOS
# ============================================================

print("="*70)
print("REGISTROS DUPLICADOS")
print("="*70)

print(df.duplicated().sum())

======================================================================
REGISTROS DUPLICADOS
======================================================================
0

In [ ]:
# ============================================================
# COBERTURA TEMPORAL
# ============================================================

print("="*70)
print("COBERTURA TEMPORAL")
print("="*70)

print("Inicio :", df["Fecha"].min())
print("Fin    :", df["Fecha"].max())

print()

print("Número de meses :", len(df))

======================================================================
COBERTURA TEMPORAL
======================================================================
Inicio : 2015-01-31 00:00:00
Fin    : 2026-03-31 00:00:00

Número de meses : 135

In [ ]:
# ============================================================
# ESTADÍSTICAS DEL ONI
# ============================================================

print("="*70)
print("ESTADÍSTICAS DEL ONI")
print("="*70)

print(df["ONI"].describe())

======================================================================
ESTADÍSTICAS DEL ONI
======================================================================
count    135.000000
mean       0.159407
std        0.932565
min       -1.360000
25%       -0.545000
50%       -0.020000
75%        0.645000
max        2.770000
Name: ONI, dtype: float64

In [ ]:
# ============================================================
# EVENTOS ENSO
# ============================================================

print("="*70)
print("EVENTOS ENSO")
print("="*70)

print(df["Estado_ENSO"].value_counts())

print()

print(df["Estado_ENSO"].value_counts(normalize=True)*100)

======================================================================
EVENTOS ENSO
======================================================================
Estado_ENSO
Neutral    52
Niño       44
Niña       39
Name: count, dtype: int64

Estado_ENSO
Neutral    38.518519
Niño       32.592593
Niña       28.888889
Name: proportion, dtype: float64

In [ ]:
# ============================================================
# INTEGRIDAD HASH
# ============================================================

print("="*70)
print("INTEGRIDAD HASH")
print("="*70)

print("Hashes únicos :", df["Hash"].nunique())
print("Registros     :", len(df))

======================================================================
INTEGRIDAD HASH
======================================================================
Hashes únicos : 135
Registros     : 135

In [ ]:
# ============================================================
# RESUMEN DE AUDITORÍA
# ============================================================

auditoria = pd.DataFrame({

    "Indicador":[

        "Registros",
        "Variables",
        "Valores Nulos",
        "Duplicados",
        "Cobertura (Meses)",
        "Valor mínimo ONI",
        "Valor máximo ONI",
        "Eventos Niño",
        "Eventos Niña",
        "Eventos Neutrales",
        "Hashes Únicos"

    ],

    "Valor":[

        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        len(df),
        df["ONI"].min(),
        df["ONI"].max(),
        (df["Estado_ENSO"]=="Niño").sum(),
        (df["Estado_ENSO"]=="Niña").sum(),
        (df["Estado_ENSO"]=="Neutral").sum(),
        df["Hash"].nunique()

    ]

})

auditoria

            Indicador   Valor
0           Registros  135.00
1           Variables   11.00
2       Valores Nulos    0.00
3          Duplicados    0.00
4   Cobertura (Meses)  135.00
5    Valor mínimo ONI   -1.36
6    Valor máximo ONI    2.77
7        Eventos Niño   44.00
8        Eventos Niña   39.00
9   Eventos Neutrales   52.00
10      Hashes Únicos  135.00

In [ ]:
auditoria.to_excel(

    "05_Auditoria.xlsx",

    index=False

)

print("Auditoría generada correctamente.")

Auditoría generada correctamente.

## **M8 – Indicadores**

In [ ]:
# ============================================================
# INDICADORES DE CALIDAD DEL DATASET
# ============================================================

indicadores = pd.DataFrame({

    "Indicador":[

        "Registros",
        "Variables",
        "Valores Nulos",
        "Duplicados",
        "Cobertura Temporal (Meses)",
        "Fecha Inicial",
        "Fecha Final",
        "Valor Mínimo ONI",
        "Valor Máximo ONI",
        "Promedio ONI",
        "Desviación Estándar ONI",
        "Eventos Niño",
        "Eventos Niña",
        "Eventos Neutrales",
        "Hashes Únicos"

    ],

    "Valor":[

        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        len(df),
        df["Fecha"].min().date(),
        df["Fecha"].max().date(),
        df["ONI"].min(),
        df["ONI"].max(),
        round(df["ONI"].mean(),3),
        round(df["ONI"].std(),3),
        (df["Estado_ENSO"]=="Niño").sum(),
        (df["Estado_ENSO"]=="Niña").sum(),
        (df["Estado_ENSO"]=="Neutral").sum(),
        df["Hash"].nunique()

    ]

})

indicadores

                     Indicador       Valor
0                    Registros         135
1                    Variables          11
2                Valores Nulos           0
3                   Duplicados           0
4   Cobertura Temporal (Meses)         135
5                Fecha Inicial  2015-01-31
6                  Fecha Final  2026-03-31
7             Valor Mínimo ONI       -1.36
8             Valor Máximo ONI        2.77
9                 Promedio ONI       0.159
10     Desviación Estándar ONI       0.933
11                Eventos Niño          44
12                Eventos Niña          39
13           Eventos Neutrales          52
14               Hashes Únicos         135

In [ ]:
print("="*70)
print("INDICADORES DE LA CAPA ONI")
print("="*70)

print(indicadores)

======================================================================
INDICADORES DE LA CAPA ONI
======================================================================
                     Indicador       Valor
0                    Registros         135
1                    Variables          11
2                Valores Nulos           0
3                   Duplicados           0
4   Cobertura Temporal (Meses)         135
5                Fecha Inicial  2015-01-31
6                  Fecha Final  2026-03-31
7             Valor Mínimo ONI       -1.36
8             Valor Máximo ONI        2.77
9                 Promedio ONI       0.159
10     Desviación Estándar ONI       0.933
11                Eventos Niño          44
12                Eventos Niña          39
13           Eventos Neutrales          52
14               Hashes Únicos         135

Este conjunto de indicadores es suficiente para una serie climática como el ONI y mantiene la consistencia metodológica con el resto de las capas del Framework V7. Posteriormente, en M9 (EDA) profundizaremos con las estadísticas descriptivas y el análisis exploratorio de la variable ONI.

In [ ]:
indicadores.to_excel(

    "06_Indicadores.xlsx",

    index=False

)

print("Indicadores exportados correctamente.")

Indicadores exportados correctamente.

## **M9 – Análisis Exploratorio de Datos (EDA)**

In [ ]:
print("="*70)
print("ESTADÍSTICAS DESCRIPTIVAS")
print("="*70)

print(df.describe(include="all"))

======================================================================
ESTADÍSTICAS DESCRIPTIVAS
======================================================================
        ID_Registro ID_Capa                Fecha         ONI Estado_ENSO  \
count           135     135                  135  135.000000         135
unique          135       1                  NaN         NaN           3
top     ONI-0000001     ONI                  NaN         NaN     Neutral
freq              1     135                  NaN         NaN          52
mean            NaN     NaN  2020-08-30 04:26:40    0.159407         NaN
min             NaN     NaN  2015-01-31 00:00:00   -1.360000         NaN
25%             NaN     NaN  2017-11-15 00:00:00   -0.545000         NaN
50%             NaN     NaN  2020-08-31 00:00:00   -0.020000         NaN
75%             NaN     NaN  2023-06-15 00:00:00    0.645000         NaN
max             NaN     NaN  2026-03-31 00:00:00    2.770000         NaN
std             NaN     NaN                  NaN    0.932565         NaN

         Fecha_ETL  Hora_ETL Version_Framework Estado_Registro  \
count          135       135               135             135
unique           1         1                 1               1
top     2026-07-15  20:27:23               1.0        VALIDADO
freq           135       135               135             135
mean           NaN       NaN               NaN             NaN
min            NaN       NaN               NaN             NaN
25%            NaN       NaN               NaN             NaN
50%            NaN       NaN               NaN             NaN
75%            NaN       NaN               NaN             NaN
max            NaN       NaN               NaN             NaN
std            NaN       NaN               NaN             NaN

                Responsable                              Hash
count                   135                               135
unique                    1                               135
top     Juan Carlos Riatiga  adfed55b480618a3f14a0c98cee347e9
freq                    135                                 1
mean                    NaN                               NaN
min                     NaN                               NaN
25%                     NaN                               NaN
50%                     NaN                               NaN
75%                     NaN                               NaN
max                     NaN                               NaN
std                     NaN                               NaN

In [ ]:
print("="*70)
print("VALORES ÚNICOS")
print("="*70)

print(df.nunique())

======================================================================
VALORES ÚNICOS
======================================================================
ID_Registro          135
ID_Capa                1
Fecha                135
ONI                  113
Estado_ENSO            3
Fecha_ETL              1
Hora_ETL               1
Version_Framework      1
Estado_Registro        1
Responsable            1
Hash                 135
dtype: int64

In [ ]:
print("="*70)
print("DISTRIBUCIÓN DE EVENTOS ENSO")
print("="*70)

print(df["Estado_ENSO"].value_counts())

======================================================================
DISTRIBUCIÓN DE EVENTOS ENSO
======================================================================
Estado_ENSO
Neutral    52
Niño       44
Niña       39
Name: count, dtype: int64

In [ ]:
print("="*70)
print("PORCENTAJE DE EVENTOS ENSO")
print("="*70)

print(

    round(

        df["Estado_ENSO"].value_counts(normalize=True)*100,

        2

    )

)

======================================================================
PORCENTAJE DE EVENTOS ENSO
======================================================================
Estado_ENSO
Neutral    38.52
Niño       32.59
Niña       28.89
Name: proportion, dtype: float64

In [ ]:
print("="*70)
print("RANGO TEMPORAL")
print("="*70)

print(df["Fecha"].min())

print(df["Fecha"].max())

======================================================================
RANGO TEMPORAL
======================================================================
2015-01-31 00:00:00
2026-03-31 00:00:00

In [ ]:
print("="*70)
print("VARIABLE ONI")
print("="*70)

print("Mínimo :", df["ONI"].min())
print("Máximo :", df["ONI"].max())
print("Media  :", round(df["ONI"].mean(),3))
print("Mediana:", round(df["ONI"].median(),3))
print("Std    :", round(df["ONI"].std(),3))

======================================================================
VARIABLE ONI
======================================================================
Mínimo : -1.36
Máximo : 2.77
Media  : 0.159
Mediana: -0.02
Std    : 0.933

In [ ]:
print("="*70)
print("INTEGRIDAD HASH")
print("="*70)

print("Hashes únicos:")
print(df["Hash"].nunique())

print()

print("Registros:")
print(len(df))

======================================================================
INTEGRIDAD HASH
======================================================================
Hashes únicos:
135

Registros:
135

In [ ]:
print("="*70)
print("RESUMEN DEL EDA")
print("="*70)

print(f"Total registros        : {len(df)}")
print(f"Serie mensual continua : {len(df)} meses")
print(f"Cobertura temporal     : {df['Fecha'].min().date()} a {df['Fecha'].max().date()}")
print(f"Eventos Niño           : {(df['Estado_ENSO']=='Niño').sum()}")
print(f"Eventos Niña           : {(df['Estado_ENSO']=='Niña').sum()}")
print(f"Eventos Neutrales      : {(df['Estado_ENSO']=='Neutral').sum()}")
print(f"Valores nulos          : {df.isnull().sum().sum()}")
print(f"Duplicados             : {df.duplicated().sum()}")

======================================================================
RESUMEN DEL EDA
======================================================================
Total registros        : 135
Serie mensual continua : 135 meses
Cobertura temporal     : 2015-01-31 a 2026-03-31
Eventos Niño           : 44
Eventos Niña           : 39
Eventos Neutrales      : 52
Valores nulos          : 0
Duplicados             : 0

In [ ]:
import pandas as pd

# ============================================================
# RESUMEN DEL EDA PARA EXPORTACIÓN
# ============================================================

# Crear un DataFrame para el resumen del EDA
eda_summary = pd.DataFrame({
    "Métrica": [
        "Total Registros",
        "Serie Mensual Continua (Meses)",
        "Cobertura Temporal (Inicio)",
        "Cobertura Temporal (Fin)",
        "Eventos Niño",
        "Eventos Niña",
        "Eventos Neutrales",
        "Valores Nulos",
        "Duplicados",
        "ONI Mínimo",
        "ONI Máximo",
        "ONI Media",
        "ONI Mediana",
        "ONI Desviación Estándar"
    ],
    "Valor": [
        len(df),
        len(df),
        df['Fecha'].min().date(),
        df['Fecha'].max().date(),
        (df['Estado_ENSO']=='Niño').sum(),
        (df['Estado_ENSO']=='Niña').sum(),
        (df['Estado_ENSO']=='Neutral').sum(),
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        df["ONI"].min(),
        df["ONI"].max(),
        round(df["ONI"].mean(), 3),
        round(df["ONI"].median(), 3),
        round(df["ONI"].std(), 3)
    ]
})

# Agregar las estadísticas descriptivas de ONI
oni_desc = df["ONI"].describe().rename("ONI").reset_index()
oni_desc.columns = ["Métrica", "Valor"]

# Agregar la distribución de Estado_ENSO
enso_dist = df["Estado_ENSO"].value_counts().rename_axis('Métrica').reset_index(name='Valor')
enso_dist["Métrica"] = "Eventos " + enso_dist["Métrica"]

# Para el 07_EDA.xlsx, es común tener estadísticas descriptivas para columnas numéricas y conteos de valores para categóricas.
# Crearemos una salida más completa para el archivo EDA.xlsx.

eda_report_df = pd.DataFrame({
    "Section": [
        "General Summary", "General Summary", "General Summary", "General Summary", "General Summary",
        "General Summary", "General Summary", "General Summary", "General Summary", "General Summary",
        "ONI Statistics", "ONI Statistics", "ONI Statistics", "ONI Statistics", "ONI Statistics", "ONI Statistics", "ONI Statistics", "ONI Statistics",
        "ENSO Distribution", "ENSO Distribution", "ENSO Distribution"
    ],
    "Metric": [
        "Total Records", "Continuous Monthly Series (Months)", "Temporal Coverage (Start)", "Temporal Coverage (End)",
        "Null Values", "Duplicates", "Unique Hashes",
        "Number of Niño Events", "Number of Niña Events", "Number of Neutral Events",
        "ONI Count", "ONI Mean", "ONI Std", "ONI Min", "ONI 25%", "ONI 50%", "ONI 75%", "ONI Max",
        "Neutral Count", "Niño Count", "Niña Count"
    ],
    "Value": [
        len(df),
        len(df),
        str(df['Fecha'].min().date()),
        str(df['Fecha'].max().date()),
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        df['Hash'].nunique(),
        (df['Estado_ENSO']=='Niño').sum(),
        (df['Estado_ENSO']=='Niña').sum(),
        (df['Estado_ENSO']=='Neutral').sum(),
        df["ONI"].describe().loc["count"],
        round(df["ONI"].describe().loc["mean"], 3),
        round(df["ONI"].describe().loc["std"], 3),
        df["ONI"].describe().loc["min"],
        df["ONI"].describe().loc["25%"],
        df["ONI"].describe().loc["50%"],
        df["ONI"].describe().loc["75%"],
        df["ONI"].describe().loc["max"],
        df["Estado_ENSO"].value_counts().get('Neutral', 0),
        df["Estado_ENSO"].value_counts().get('Niño', 0),
        df["Estado_ENSO"].value_counts().get('Niña', 0)
    ]
})


output_eda_file = "07_EDA.xlsx"
eda_report_df.to_excel(output_eda_file, index=False)

print("Reporte EDA generado correctamente en:", output_eda_file)

Reporte EDA generado correctamente en: 07_EDA.xlsx

A diferencia de las capas de Clima, Hidrología y Calidad del Agua, el EDA de ONI no requiere análisis espaciales (estaciones, municipios, coordenadas) porque representa una serie climática global. Su valor para el Framework reside en la continuidad temporal, la distribución de las fases ENSO y la variabilidad del índice, aspectos que serán utilizados como variable exógena en el modelo LSTM. Esto mantiene la consistencia metodológica entre capas sin incorporar análisis que no aportan información para esta naturaleza de datos.

## **M10 – README**

In [ ]:
# ============================================================
# M10 – README
# ============================================================

readme = f"""# FRAMEWORK V7

# CAPA: {NOMBRE_CAPA}

## Descripción

Esta capa contiene la serie temporal mensual del
Índice Oceánico del Niño (ONI), obtenida desde
la NOAA (National Oceanic and Atmospheric Administration).

El ONI representa la anomalía de temperatura
superficial del océano Pacífico ecuatorial en la
región Niño 3.4 y constituye uno de los principales
indicadores de los eventos ENSO
(El Niño – Oscilación del Sur).

La serie fue estandarizada para el Framework V7,
permitiendo su integración con las demás capas
hidrológicas, climáticas y ambientales del modelo.

------------------------------------------------------------

## Fuente oficial

{FUENTE}

{URL_FUENTE}

------------------------------------------------------------

## Archivo procesado

{ARCHIVO}

------------------------------------------------------------

## Cobertura temporal

Inicio :
{df["Fecha"].min().date()}

Fin :
{df["Fecha"].max().date()}

------------------------------------------------------------

## Registros

{len(df)}

------------------------------------------------------------

## Variables

{len(df.columns)}

Columnas:

"""

for c in df.columns:
    readme += f"- {c}\n"

readme += f"""

------------------------------------------------------------

## Variables principales

• Fecha

• ONI

• Estado_ENSO

------------------------------------------------------------

## Información de Gobierno del Dato

Versión Framework :
{VERSION}

Responsable :
{RESPONSABLE}

Fecha ETL :
{df['Fecha_ETL'].iloc[0]}

Hora ETL :
{df['Hora_ETL'].iloc[0]}

------------------------------------------------------------

## Calidad del dato

Valores nulos :
{df.isnull().sum().sum()}

Duplicados :
{df.duplicated().sum()}

Hashes únicos :
{df['Hash'].nunique()}

------------------------------------------------------------

## Clasificación ENSO

{df["Estado_ENSO"].value_counts().to_string()}

------------------------------------------------------------

## Objetivo

Proporcionar una serie temporal estandarizada del
Índice Oceánico del Niño (ONI) para incorporar la
variabilidad climática de gran escala como variable
explicativa dentro del Framework V7 y del modelo
predictivo basado en LSTM.

------------------------------------------------------------

Generado automáticamente por Framework V7.
"""

with open(
    "08_README.md",
    "w",
    encoding="utf-8"
) as f:
    f.write(readme)

print("README generado correctamente.")

README generado correctamente.

## **Exportación Final**

In [ ]:
# ============================================================
# EXPORTACIÓN FINAL DEL FRAMEWORK
# ============================================================

nombre_salida = "02_Capa_ONI_Framework.xlsx"

df.to_excel(
    nombre_salida,
    index=False
)

print("="*70)
print("CAPA FRAMEWORK GENERADA CORRECTAMENTE")
print("="*70)

print(f"Archivo generado : {nombre_salida}")
print(f"Registros        : {len(df)}")
print(f"Variables        : {len(df.columns)}")

print("\nColumnas finales:")

for c in df.columns:
    print("-", c)

print("\nProceso finalizado.")