# **FRAMEWORK V7 DATASET MAESTRO - DISEÑO EXPERIMENTAL**

In [ ]:
# Funciones modulares reutilizables para diseno experimental
from pathlib import Path
import sys

PROJECT_SRC = Path.cwd() / "src"
if PROJECT_SRC.exists() and str(PROJECT_SRC) not in sys.path:
    sys.path.insert(0, str(PROJECT_SRC))

from framework_v7.pipeline.experiment_design import (
    active_predictors,
    design_summary,
    experiment_plan,
    experiment_status_summary,
    load_design_artifacts,
)

## **M0 – Configuración**

Objetivo:

Definir los experimentos oficiales utilizados para validar el
Framework de Ingeniería de Datos y Ciencia de Datos aplicado
a la Gestión Inteligente del Recurso Hídrico.

## **M1 Objetivo**

El objetivo del Diseño Experimental es establecer el conjunto de experimentos utilizados para validar el funcionamiento del Framework, definiendo las variables objetivo, las variables predictoras, la configuración de modelado y los criterios de evaluación aplicables a cada caso de estudio.

## **M2 Variables del Dominio**

In [24]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jriatiga/FRAMEWORK_V7/refs/heads/main/DATA/MASTER/C11_MASTER/Preparacion_Machine_Learning/ipm/variables_machine_learning.csv'
df_variables = pd.read_csv(url)

display(df_variables.head(20))

,Ranking,Variable,Tipo,Relaciones_Fuertes,Indice_Redundancia,Nivel_Redundancia,Diagnostico_Redundancia,VIF,Estado_VIF,Diagnostico_VIF,...,Importancia,Peso,Puntaje_Conocimiento_Dominio,% Cobertura,Puntaje_Calidad,Puntaje_Redundancia,Puntaje_Multicolinealidad,IPML,Nivel_IPML,Estado_Final
0,1,Precipitacion_mm,Numérica,0,0.000,Muy Baja,Variable prácticamente independiente.,1.898,Baja,Variable con baja dependencia estructural.,...,Muy Alta,3,1.000,100.0,1.0,1.000,1.00,1.0000,Muy Alta,Seleccionada
1,2,ONI,Numérica,0,0.000,Muy Baja,Variable prácticamente independiente.,1.265,Baja,Variable con baja dependencia estructural.,...,Muy Alta,3,1.000,100.0,1.0,1.000,1.00,1.0000,Muy Alta,Seleccionada
2,3,Radiacion_Solar,Numérica,0,0.000,Muy Baja,Variable prácticamente independiente.,1.704,Baja,Variable con baja dependencia estructural.,...,Muy Alta,3,1.000,100.0,1.0,1.000,1.00,1.0000,Muy Alta,Seleccionada
3,4,Humedad_Relativa,Numérica,0,0.000,Muy Baja,Variable prácticamente independiente.,7.128,Moderada,Existe una dependencia moderada aceptable para...,...,Muy Alta,3,1.000,100.0,1.0,1.000,0.75,0.9500,Muy Alta,Seleccionada
4,8,Temp_Min_C,Numérica,0,0.000,Muy Baja,Variable prácticamente independiente.,10.573,Alta,Presenta una dependencia considerable con otra...,...,Muy Alta,3,1.000,100.0,1.0,1.000,0.50,0.9000,Muy Alta,Seleccionada
5,10,Mes,Numérica,0,0.000,Muy Baja,Variable prácticamente independiente.,1.152,Baja,Variable con baja dependencia estructural.,...,Alta,2,0.667,100.0,1.0,1.000,1.00,0.8668,Alta,Seleccionada
6,11,Velocidad_Viento,Numérica,0,0.000,Muy Baja,Variable prácticamente independiente.,1.477,Baja,Variable con baja dependencia estructural.,...,Alta,2,0.667,100.0,1.0,1.000,1.00,0.8668,Alta,Seleccionada
7,12,irca,Numérica,1,0.167,Muy Baja,Variable prácticamente independiente.,13.982,Alta,Presenta una dependencia considerable con otra...,...,Muy Alta,3,1.000,100.0,1.0,0.833,0.50,0.8499,Alta,Seleccionada
8,13,VolumenUtilDiarioMasa,Numérica,1,0.167,Muy Baja,Variable prácticamente independiente.,11.557,Alta,Presenta una dependencia considerable con otra...,...,Muy Alta,3,1.000,100.0,1.0,0.833,0.50,0.8499,Alta,Seleccionada

## **M3 Variables Objetivo**

In [ ]:
display(df_variables.head())

,Ranking,Variable,Tipo,Relaciones_Fuertes,Indice_Redundancia,Nivel_Redundancia,Diagnostico_Redundancia,VIF,Estado_VIF,Diagnostico_VIF,...,Importancia,Peso,Puntaje_Conocimiento_Dominio,% Cobertura,Puntaje_Calidad,Puntaje_Redundancia,Puntaje_Multicolinealidad,IPML,Nivel_IPML,Estado_Final
0,1,Precipitacion_mm,Numérica,0,0.0,Muy Baja,Variable prácticamente independiente.,1.898,Baja,Variable con baja dependencia estructural.,...,Muy Alta,3,1.0,100.0,1.0,1.0,1.00,1.00,Muy Alta,Seleccionada
1,2,ONI,Numérica,0,0.0,Muy Baja,Variable prácticamente independiente.,1.265,Baja,Variable con baja dependencia estructural.,...,Muy Alta,3,1.0,100.0,1.0,1.0,1.00,1.00,Muy Alta,Seleccionada
2,3,Radiacion_Solar,Numérica,0,0.0,Muy Baja,Variable prácticamente independiente.,1.704,Baja,Variable con baja dependencia estructural.,...,Muy Alta,3,1.0,100.0,1.0,1.0,1.00,1.00,Muy Alta,Seleccionada
3,4,Humedad_Relativa,Numérica,0,0.0,Muy Baja,Variable prácticamente independiente.,7.128,Moderada,Existe una dependencia moderada aceptable para...,...,Muy Alta,3,1.0,100.0,1.0,1.0,0.75,0.95,Muy Alta,Seleccionada
4,8,Temp_Min_C,Numérica,0,0.0,Muy Baja,Variable prácticamente independiente.,10.573,Alta,Presenta una dependencia considerable con otra...,...,Muy Alta,3,1.0,100.0,1.0,1.0,0.50,0.90,Muy Alta,Seleccionada

## **M4 Variables Predictoras**

In [ ]:
#==========================================================
# M4 - VARIABLES PREDICTORAS
#==========================================================

print("="*90)
print("M4 - VARIABLES PREDICTORAS")
print("="*90)
print()

#----------------------------------------------------------
# Variables seleccionadas por IPML
#----------------------------------------------------------

variables_predictoras = list(
    df_variables.loc[
        df_variables["Estado_Final"]=="Seleccionada",
        "Variable"
    ]
)

print("Número de variables predictoras:")

print(len(variables_predictoras))

print()

for i,v in enumerate(variables_predictoras,1):

    print(f"{i:02d}. {v}")

==========================================================================================
M4 - VARIABLES PREDICTORAS
==========================================================================================

Número de variables predictoras:
9

01. Precipitacion_mm
02. ONI
03. Radiacion_Solar
04. Humedad_Relativa
05. Temp_Min_C
06. Mes
07. Velocidad_Viento
08. irca
09. VolumenUtilDiarioMasa

In [ ]:
#----------------------------------------------------------
# Tabla de Variables Predictoras
#----------------------------------------------------------

tabla_predictoras = pd.DataFrame({

    "Orden":range(1,len(variables_predictoras)+1),

    "Variable":variables_predictoras

})

display(tabla_predictoras)

   Orden               Variable
0      1       Precipitacion_mm
1      2                    ONI
2      3        Radiacion_Solar
3      4       Humedad_Relativa
4      5             Temp_Min_C
5      6                    Mes
6      7       Velocidad_Viento
7      8                   irca
8      9  VolumenUtilDiarioMasa

In [ ]:
#----------------------------------------------------------
# Exportación
#----------------------------------------------------------

tabla_predictoras.to_csv(

    "variables_predictoras.csv",

    index=False

)

tabla_predictoras.to_excel(

    "variables_predictoras.xlsx",

    index=False

)

print()

print("Variables predictoras exportadas.")

Variables predictoras exportadas.

## **M5 – Catálogo de Experimentos**

Definir formalmente los experimentos que serán ejecutados para validar el Framework, estableciendo la variable objetivo, el tipo de problema, la configuración general y el propósito científico de cada uno.

Este módulo constituye el plan experimental oficial del Framework.

In [ ]:
#==========================================================
# M5 - CATÁLOGO DE EXPERIMENTOS
#==========================================================

print("="*90)
print("M5 - CATÁLOGO DE EXPERIMENTOS")
print("="*90)

experimentos = pd.DataFrame([

{
"Experimento":"Exp01",
"Dominio":"Gestión Hídrica",
"Pregunta_Investigacion":"¿Es posible anticipar el riesgo sanitario del agua mediante información climática e hidrológica?",
"Objetivo_Experimento":"Evaluar la capacidad del Framework para predecir el IRCA e identificar variables asociadas al riesgo sanitario del agua.",
"Variable_Objetivo":"irca",
"Tipo_Problema":"Clasificación",
"Ventana":12,
"Horizonte":1,
"Modelo":"LSTM",
"Estado":"Ejecutado"
},

{
"Experimento":"Exp02",
"Dominio":"Gestión Hídrica",
"Pregunta_Investigacion":"¿Qué factores permiten anticipar el estado general de la calidad del agua?",
"Objetivo_Experimento":"Evaluar la capacidad del Framework para predecir la calidad general del recurso hídrico.",
"Variable_Objetivo":"CALIDAD_AGUA",
"Tipo_Problema":"Clasificación",
"Ventana":12,
"Horizonte":1,
"Modelo":"LSTM",
"Estado":"Pendiente"
},

{
"Experimento":"Exp03",
"Dominio":"Gestión Hídrica",
"Pregunta_Investigacion":"¿Es posible anticipar la disminución del nivel mínimo del recurso hídrico?",
"Objetivo_Experimento":"Evaluar la capacidad predictiva del Framework sobre la disponibilidad del recurso hídrico.",
"Variable_Objetivo":"Nivel_Minimo",
"Tipo_Problema":"Regresión",
"Ventana":12,
"Horizonte":1,
"Modelo":"LSTM",
"Estado":"Pendiente"
},

{
"Experimento":"Exp04",
"Dominio":"Gestión Hídrica",
"Pregunta_Investigacion":"¿Qué variables afectan el volumen útil disponible del sistema?",
"Objetivo_Experimento":"Evaluar la predicción del volumen útil disponible para apoyar la gestión del recurso.",
"Variable_Objetivo":"VolumenUtilDiarioMasa",
"Tipo_Problema":"Regresión",
"Ventana":12,
"Horizonte":1,
"Modelo":"LSTM",
"Estado":"Pendiente"
},

{
"Experimento":"Exp05",
"Dominio":"Gestión Hídrica",
"Pregunta_Investigacion":"¿Es posible anticipar procesos de contaminación orgánica del agua?",
"Objetivo_Experimento":"Evaluar el comportamiento predictivo de la Demanda Bioquímica de Oxígeno (DBO5).",
"Variable_Objetivo":"DBO5",
"Tipo_Problema":"Regresión",
"Ventana":12,
"Horizonte":1,
"Modelo":"LSTM",
"Estado":"Pendiente"
},

{
"Experimento":"Exp06",
"Dominio":"Gestión Hídrica",
"Pregunta_Investigacion":"¿Qué variables explican la contaminación química del recurso hídrico?",
"Objetivo_Experimento":"Evaluar el comportamiento predictivo de la Demanda Química de Oxígeno (DQO).",
"Variable_Objetivo":"DQO",
"Tipo_Problema":"Regresión",
"Ventana":12,
"Horizonte":1,
"Modelo":"LSTM",
"Estado":"Pendiente"
},

{
"Experimento":"Exp07",
"Dominio":"Gestión Hídrica",
"Pregunta_Investigacion":"¿Qué factores afectan el equilibrio ecológico del recurso hídrico?",
"Objetivo_Experimento":"Evaluar la capacidad del Framework para predecir el Oxígeno Disuelto como indicador ecológico.",
"Variable_Objetivo":"Oxigeno_Disuelto",
"Tipo_Problema":"Regresión",
"Ventana":12,
"Horizonte":1,
"Modelo":"LSTM",
"Estado":"Pendiente"
},

{
"Experimento":"Exp08",
"Dominio":"Gestión Hídrica",
"Pregunta_Investigacion":"¿Es posible anticipar cambios fisicoquímicos del agua?",
"Objetivo_Experimento":"Evaluar el comportamiento predictivo del pH como indicador de calidad del agua.",
"Variable_Objetivo":"pH",
"Tipo_Problema":"Regresión",
"Ventana":12,
"Horizonte":1,
"Modelo":"LSTM",
"Estado":"Pendiente"
}

])

display(experimentos)

==========================================================================================
M5 - CATÁLOGO DE EXPERIMENTOS
==========================================================================================

,Experimento,Dominio,Pregunta_Investigacion,Objetivo_Experimento,Variable_Objetivo,Tipo_Problema,Ventana,Horizonte,Modelo,Estado
0,Exp01,Gestión Hídrica,¿Es posible anticipar el riesgo sanitario del ...,Evaluar la capacidad del Framework para predec...,irca,Clasificación,12,1,LSTM,Ejecutado
1,Exp02,Gestión Hídrica,¿Qué factores permiten anticipar el estado gen...,Evaluar la capacidad del Framework para predec...,CALIDAD_AGUA,Clasificación,12,1,LSTM,Pendiente
2,Exp03,Gestión Hídrica,¿Es posible anticipar la disminución del nivel...,Evaluar la capacidad predictiva del Framework ...,Nivel_Minimo,Regresión,12,1,LSTM,Pendiente
3,Exp04,Gestión Hídrica,¿Qué variables afectan el volumen útil disponi...,Evaluar la predicción del volumen útil disponi...,VolumenUtilDiarioMasa,Regresión,12,1,LSTM,Pendiente
4,Exp05,Gestión Hídrica,¿Es posible anticipar procesos de contaminació...,Evaluar el comportamiento predictivo de la Dem...,DBO5,Regresión,12,1,LSTM,Pendiente
5,Exp06,Gestión Hídrica,¿Qué variables explican la contaminación quími...,Evaluar el comportamiento predictivo de la Dem...,DQO,Regresión,12,1,LSTM,Pendiente
6,Exp07,Gestión Hídrica,¿Qué factores afectan el equilibrio ecológico ...,Evaluar la capacidad del Framework para predec...,Oxigeno_Disuelto,Regresión,12,1,LSTM,Pendiente
7,Exp08,Gestión Hídrica,¿Es posible anticipar cambios fisicoquímicos d...,Evaluar el comportamiento predictivo del pH co...,pH,Regresión,12,1,LSTM,Pendiente

In [ ]:
experimentos.to_csv(

    "catalogo_experimentos.csv",

    index=False

)

experimentos.to_excel(

    "catalogo_experimentos.xlsx",

    index=False

)

print()

print("Catálogo Experimental exportado correctamente.")

Catálogo Experimental exportado correctamente.

## **M6 – Configuración Experimental**

In [ ]:
#==========================================================
# M6 - CONFIGURACIÓN EXPERIMENTAL
#==========================================================

print("="*90)
print("M6 - CONFIGURACIÓN EXPERIMENTAL")
print("="*90)

configuracion = pd.DataFrame([

{
"Experimento":"Exp01",
"Modelo":"LSTM",
"Ventana":12,
"Horizonte":1,
"Transformacion":"MinMaxScaler",
"Optimizador":"Adam",
"LearningRate":0.001,
"BatchSize":32,
"Epochs":100,
"EarlyStopping":10,
"Loss":"binary_crossentropy",
"Metrica":"Accuracy"
},

{
"Experimento":"Exp02",
"Modelo":"LSTM",
"Ventana":12,
"Horizonte":1,
"Transformacion":"MinMaxScaler",
"Optimizador":"Adam",
"LearningRate":0.001,
"BatchSize":32,
"Epochs":100,
"EarlyStopping":10,
"Loss":"binary_crossentropy",
"Metrica":"Accuracy"
},

{
"Experimento":"Exp03",
"Modelo":"LSTM",
"Ventana":12,
"Horizonte":1,
"Transformacion":"MinMaxScaler",
"Optimizador":"Adam",
"LearningRate":0.001,
"BatchSize":32,
"Epochs":100,
"EarlyStopping":10,
"Loss":"mse",
"Metrica":"RMSE"
},

{
"Experimento":"Exp04",
"Modelo":"LSTM",
"Ventana":12,
"Horizonte":1,
"Transformacion":"MinMaxScaler",
"Optimizador":"Adam",
"LearningRate":0.001,
"BatchSize":32,
"Epochs":100,
"EarlyStopping":10,
"Loss":"mse",
"Metrica":"RMSE"
}

])

display(configuracion)

==========================================================================================
M6 - CONFIGURACIÓN EXPERIMENTAL
==========================================================================================

,Experimento,Modelo,Ventana,Horizonte,Transformacion,Optimizador,LearningRate,BatchSize,Epochs,EarlyStopping,Loss,Metrica
0,Exp01,LSTM,12,1,MinMaxScaler,Adam,0.001,32,100,10,binary_crossentropy,Accuracy
1,Exp02,LSTM,12,1,MinMaxScaler,Adam,0.001,32,100,10,binary_crossentropy,Accuracy
2,Exp03,LSTM,12,1,MinMaxScaler,Adam,0.001,32,100,10,mse,RMSE
3,Exp04,LSTM,12,1,MinMaxScaler,Adam,0.001,32,100,10,mse,RMSE

In [ ]:
configuracion.to_csv(

    "configuracion_experimentos.csv",

    index=False

)

configuracion.to_excel(

    "configuracion_experimentos.xlsx",

    index=False

)

print()

print("Configuración Experimental exportada.")

Configuración Experimental exportada.

## **M7 – Criterios de Evaluación**

In [ ]:
#==========================================================
# M7 - CRITERIOS DE EVALUACIÓN
#==========================================================

print("="*90)
print("M7 - CRITERIOS DE EVALUACIÓN")
print("="*90)

clasificacion = experimentos.loc[
    experimentos["Tipo_Problema"]=="Clasificación"
]

regresion = experimentos.loc[
    experimentos["Tipo_Problema"]=="Regresión"
]

print()

print("Experimentos de Clasificación :",len(clasificacion))

print("Experimentos de Regresión     :",len(regresion))

==========================================================================================
M7 - CRITERIOS DE EVALUACIÓN
==========================================================================================

Experimentos de Clasificación : 2
Experimentos de Regresión     : 6

In [ ]:
# Criterios para Clasificación

criterios_clasificacion = pd.DataFrame({

"Metrica":[

"Accuracy",

"Precision",

"Recall",

"F1-Score",

"Accuracy Balanceada"

],

"Valor_Minimo":[

0.85,

0.70,

0.70,

0.70,

0.70

],

"Descripcion":[

"Exactitud global",

"Capacidad para evitar falsos positivos",

"Capacidad para detectar positivos",

"Equilibrio entre Precision y Recall",

"Control del desbalance"

]

})

display(criterios_clasificacion)

               Metrica  Valor_Minimo                             Descripcion
0             Accuracy          0.85                        Exactitud global
1            Precision          0.70  Capacidad para evitar falsos positivos
2               Recall          0.70       Capacidad para detectar positivos
3             F1-Score          0.70     Equilibrio entre Precision y Recall
4  Accuracy Balanceada          0.70                  Control del desbalance

In [ ]:
# Criterios para Regresión

criterios_regresion = pd.DataFrame({

"Metrica":[

"MAE",

"RMSE",

"R2"

],

"Criterio":[

"Minimizar",

"Minimizar",

"Mayor o igual a 0.70"

],

"Descripcion":[

"Error Absoluto Medio",

"Raíz del Error Cuadrático Medio",

"Coeficiente de Determinación"

]

})

display(criterios_regresion)

  Metrica              Criterio                      Descripcion
0     MAE             Minimizar             Error Absoluto Medio
1    RMSE             Minimizar  Raíz del Error Cuadrático Medio
2      R2  Mayor o igual a 0.70     Coeficiente de Determinación

In [ ]:
# Reglas del Framework

reglas_framework = [

"Accuracy >= 0.85",

"Precision >= 0.70",

"Recall >= 0.70",

"F1 >= 0.70",

"Accuracy Balanceada >= 0.70"

]

print()

print("="*90)

print("REGLAS DEL FRAMEWORK")

print("="*90)

print()

for regla in reglas_framework:

    print("•",regla)

==========================================================================================
REGLAS DEL FRAMEWORK
==========================================================================================

• Accuracy >= 0.85
• Precision >= 0.70
• Recall >= 0.70
• F1 >= 0.70
• Accuracy Balanceada >= 0.70

In [ ]:
criterios_clasificacion.to_csv(

    "criterios_clasificacion.csv",

    index=False

)

criterios_regresion.to_csv(

    "criterios_regresion.csv",

    index=False

)

criterios_clasificacion.to_excel(

    "criterios_clasificacion.xlsx",

    index=False

)

criterios_regresion.to_excel(

    "criterios_regresion.xlsx",

    index=False
)

print()

print("Criterios exportados correctamente.")

Criterios exportados correctamente.

## **M8 – Estado de los Experimentos**

In [ ]:
import numpy as np
#==========================================================
# M8 - ESTADO DE LOS EXPERIMENTOS
#==========================================================

print("="*90)
print("M8 - ESTADO DE LOS EXPERIMENTOS")
print("="*90)

estado_experimentos = experimentos.copy()

estado_experimentos["Estado_Modelo"] = ""

estado_experimentos["Accuracy"] = np.nan

estado_experimentos["Precision"] = np.nan

estado_experimentos["Recall"] = np.nan

estado_experimentos["F1"] = np.nan

estado_experimentos["Fecha_Ejecucion"] = ""

estado_experimentos["Observaciones"] = ""

display(estado_experimentos)

==========================================================================================
M8 - ESTADO DE LOS EXPERIMENTOS
==========================================================================================

,Experimento,Variable_Objetivo,Tipo_Problema,Dominio,Ventana,Horizonte,Modelo,Estado,Objetivo,Estado_Modelo,Accuracy,Precision,Recall,F1,Fecha_Ejecucion,Observaciones
0,Exp01,irca,Clasificación,Gestión Hídrica,12,1,LSTM,Ejecutado,Evaluar la capacidad del Framework para predec...,,NaN,NaN,NaN,NaN,,
1,Exp02,CALIDAD_AGUA,Clasificación,Gestión Hídrica,12,1,LSTM,Pendiente,Evaluar el comportamiento general de la calida...,,NaN,NaN,NaN,NaN,,
2,Exp03,Nivel_Minimo,Regresión,Gestión Hídrica,12,1,LSTM,Pendiente,Validar la capacidad predictiva sobre la dispo...,,NaN,NaN,NaN,NaN,,
3,Exp04,VolumenUtilDiarioMasa,Regresión,Gestión Hídrica,12,1,LSTM,Pendiente,Validar la predicción del volumen útil disponi...,,NaN,NaN,NaN,NaN,,
4,Exp05,DBO5,Regresión,Gestión Hídrica,12,1,LSTM,Pendiente,Evaluar contaminación orgánica.,,NaN,NaN,NaN,NaN,,
5,Exp06,DQO,Regresión,Gestión Hídrica,12,1,LSTM,Pendiente,Evaluar contaminación química.,,NaN,NaN,NaN,NaN,,
6,Exp07,Oxigeno_Disuelto,Regresión,Gestión Hídrica,12,1,LSTM,Pendiente,Evaluar el estado ecológico del recurso.,,NaN,NaN,NaN,NaN,,
7,Exp08,pH,Regresión,Gestión Hídrica,12,1,LSTM,Pendiente,Evaluar el comportamiento fisicoquímico del agua.,,NaN,NaN,NaN,NaN,,

In [ ]:
estado_experimentos.to_csv(

    "estado_experimentos.csv",

    index=False

)

estado_experimentos.to_excel(

    "estado_experimentos.xlsx",

    index=False

)

print()

print("Estado de experimentos exportado.")

Estado de experimentos exportado.

## **M9 – Exportación del Diseño Experimental**

In [ ]:
#==========================================================
# M9 - EXPORTACIÓN DEL DISEÑO EXPERIMENTAL
#==========================================================

import os

CARPETA_SALIDA = "DISEÑO_EXPERIMENTAL"

os.makedirs(

    CARPETA_SALIDA,

    exist_ok=True

)

print()

print("="*90)
print("EXPORTACIÓN DEL DISEÑO EXPERIMENTAL")
print("="*90)

print()

print(f"Carpeta creada: {CARPETA_SALIDA}")

==========================================================================================
EXPORTACIÓN DEL DISEÑO EXPERIMENTAL
==========================================================================================

Carpeta creada: DISEÑO_EXPERIMENTAL

In [ ]:
import shutil

archivos = [

"catalogo_experimentos.csv",
"catalogo_experimentos.xlsx",

"configuracion_experimentos.csv",
"configuracion_experimentos.xlsx",

"criterios_clasificacion.csv",
"criterios_clasificacion.xlsx",

"criterios_regresion.csv",
"criterios_regresion.xlsx",

"estado_experimentos.csv",
"estado_experimentos.xlsx",

"variables_predictoras.csv",
"variables_predictoras.xlsx",

"variables_objetivo.csv",
"variables_objetivo.xlsx"

]

for archivo in archivos:

    if os.path.exists(archivo):

        shutil.copy(

            archivo,

            os.path.join(

                CARPETA_SALIDA,

                archivo

            )

        )

print()

print("Archivos exportados correctamente.")

Archivos exportados correctamente.

In [ ]:
readme = f"""
# DISEÑO EXPERIMENTAL DEL FRAMEWORK V7

Este directorio contiene la configuración oficial utilizada por el Framework.

Contenido

• Variables objetivo

• Variables predictoras

• Catálogo experimental

• Configuración experimental

• Criterios de evaluación

• Estado de los experimentos

Estos archivos son consumidos automáticamente por:

FW7_C13_MachineLearning.ipynb

FW7_C14_Modelado.ipynb

FW7_C15_Evaluacion_Modelos.ipynb

"""

with open(

    os.path.join(

        CARPETA_SALIDA,

        "README.md"

    ),

    "w",

    encoding="utf-8"

) as f:

    f.write(readme)

print("README generado.")

README generado.